import type { Article } from '../types';

/**
 * Categoría «Accidentes y desastres»: incidentes con armas nucleares, accidentes de
 * instalaciones nucleares, accidentes de criticidad y falsas alarmas.
 */
export const ARTICLES: Article[] = [
  // ───────────────────────────── PALOMARES ─────────────────────────────
  {
    id: 'palomares',
    title: 'El accidente de Palomares (1966)',
    cat: 'acc',
    order: 1,
    summary: 'El 17 de enero de 1966, un bombardero B-52 estadounidense chocó con su avión cisterna sobre Palomares (Almería) y dejó caer cuatro bombas termonucleares. Dos esparcieron plutonio sobre el pueblo y una se perdió en el mar durante ochenta días.',
    tags: ['Palomares', 'Almería', 'Cuevas del Almanzora', 'España', 'B-52', 'KC-135', 'B28', 'Flecha Rota', 'Broken Arrow', 'Francisco Simó', 'Paco el de la bomba', 'Fraga', 'baño de Fraga', 'Alvin', 'plutonio', 'CIEMAT', 'Chrome Dome', '1966'],
    blocks: [
      { t: 'p', text: 'En plena [[carrera-armamentistica|Guerra Fría]], el Mando Aéreo Estratégico de Estados Unidos mantenía siempre en el aire una parte de su flota de bombarderos B-52 cargados con armas termonucleares. La operación se llamaba **Chrome Dome**: si un ataque soviético destruía las bases en tierra, esos aviones podrían seguir hacia sus objetivos. Una de sus rutas cruzaba el Atlántico, sobrevolaba España y patrullaba el Mediterráneo cerca de la frontera soviética antes de volver. Para hacer un recorrido tan largo, los bombarderos repostaban en vuelo sobre territorio español con aviones cisterna KC-135 que despegaban de la base de Morón de la Frontera (Sevilla), una de las instalaciones abiertas a Estados Unidos tras los Pactos de Madrid de 1953.' },
      { t: 'facts', rows: [
        ['Fecha', '17 de enero de 1966, a media mañana'],
        ['Lugar', 'Palomares, pedanía de Cuevas del Almanzora (Almería)'],
        ['Aviones', 'Bombardero B-52G (base de Seymour Johnson, Carolina del Norte) y avión cisterna KC-135 (base de Morón)'],
        ['Víctimas mortales', '7 tripulantes: los 4 del KC-135 y 3 de los 7 del B-52. Ningún vecino murió'],
        ['Armas', '4 bombas termonucleares B28, de entre 1 y 1,5 Mt cada una según las fuentes'],
        ['Explosión nuclear', 'Ninguna'],
        ['Contaminación', 'Plutonio dispersado por dos de las bombas sobre unas 200 hectáreas'],
        ['Bomba perdida', 'Cayó al mar; recuperada el 7 de abril de 1966 a unos 870 m de profundidad'],
      ] },
      { t: 'h', text: 'La colisión' },
      { t: 'p', text: 'El bombardero volvía de su patrulla y se acercaba al avión cisterna a unos 9500 metros de altura sobre la costa de Almería. Durante la maniobra de aproximación, el B-52 llegó demasiado deprisa y chocó con el KC-135. El cisterna, cargado de combustible, estalló y sus cuatro tripulantes murieron en el acto. El bombardero se partió en el aire. De sus siete tripulantes, cuatro lograron saltar en paracaídas; tres de ellos cayeron al mar y fueron rescatados por pescadores de la zona. Los restos ardiendo de ambos aviones cayeron sobre Palomares, entonces un pueblo agrícola de pocos cientos de habitantes dedicado a los tomates y otros cultivos de regadío. Fue casi un milagro que ningún vecino resultara herido.' },
      { t: 'h', text: 'Las cuatro bombas' },
      { t: 'p', text: 'El B-52 llevaba cuatro [[bomba-de-hidrogeno|bombas termonucleares]] del modelo **B28**, cada una cientos de veces más potente que la de [[hiroshima|Hiroshima]]. Ninguna produjo una explosión nuclear: las armas estaban diseñadas para no detonar en un accidente y, además, no habían sido armadas. Pero corrieron suertes muy distintas:' },
      { t: 'list', ordered: true, items: [
        '**La primera** cayó con su paracaídas abierto cerca del cauce seco del río Almanzora, junto a la playa, y fue localizada enseguida prácticamente intacta.',
        '**La segunda** cayó sin paracaídas en unas colinas cercanas al pueblo. El explosivo convencional que contenía estalló con el golpe, abrió un cráter y pulverizó parte del plutonio, que el viento esparció.',
        '**La tercera** cayó en un campo de cultivo a las afueras del pueblo. Su explosivo convencional también estalló y dispersó plutonio y uranio en forma de polvo fino.',
        '**La cuarta** desapareció. Durante días, la Fuerza Aérea estadounidense la buscó en tierra sin encontrarla.',
      ] },
      { t: 'h', text: 'La búsqueda en el mar y «Paco el de la bomba»' },
      { t: 'p', text: 'La pista decisiva la dio un pescador de Águilas, **Francisco Simó Orts**, que faenaba frente a la costa en el momento del accidente. Simó contó que había visto caer al mar un gran paracaídas del que colgaba un objeto alargado, y señaló el punto aproximado. Al principio los militares estadounidenses dudaron de su testimonio, pero acabó siendo crucial. Desde entonces se le conoció en toda la comarca como **«Paco el de la bomba»**.' },
      { t: 'p', text: 'La Armada de Estados Unidos organizó una de las mayores operaciones de búsqueda submarina de su historia hasta entonces: más de treinta barcos, miles de marinos y buceadores y los mejores medios técnicos de la época, entre ellos los minisubmarinos **Alvin** y **Aluminaut**. A mediados de marzo, el Alvin localizó la bomba envuelta en su paracaídas en una ladera submarina, a unos 770 metros de profundidad, cerca del lugar señalado por Simó. Un primer intento de izarla falló: el cable se rompió y la bomba se deslizó pendiente abajo. Tuvo que ser localizada de nuevo y, el **7 de abril de 1966**, tras 80 días de búsqueda, un robot submarino controlado por cable, el CURV, logró engancharla a unos 870 metros y subirla a la superficie. Fue mostrada a la prensa en la cubierta de un buque estadounidense, una imagen insólita en aquella época. Simó reclamó después una recompensa por el hallazgo y se quejó durante años de no haber recibido el reconocimiento que creía merecer.' },
      { t: 'h', text: 'El baño de Fraga' },
      { t: 'p', text: 'El accidente amenazaba dos cosas que el régimen de Franco consideraba vitales: la naciente industria turística de la costa mediterránea y las exportaciones agrícolas. El Gobierno mantuvo al principio un silencio casi total y la prensa española dio la información con cuentagotas. Para demostrar que el mar no era peligroso, el **8 de marzo de 1966** el ministro de Información y Turismo, **Manuel Fraga Iribarne**, y el embajador estadounidense, **Angier Biddle Duke**, se bañaron ante las cámaras en la playa de Quitapellejos, en Palomares. Las imágenes del ministro en bañador en las frías aguas de marzo, difundidas por el NO-DO, se convirtieron en uno de los recuerdos más célebres de la época. Lo que pocos sabían es que la cuarta bomba seguía todavía en el fondo del mar a unos kilómetros de allí.' },
      { t: 'h', text: 'La descontaminación' },
      { t: 'p', text: 'El plutonio es poco peligroso fuera del cuerpo, pero muy dañino si se inhala en forma de polvo fino; véase [[plutonio|plutonio]]. Las autoridades de ambos países acordaron una limpieza que hoy se considera insuficiente. Cientos de militares estadounidenses, muchos sin más protección que su uniforme, retiraron la capa superior de tierra de las zonas más contaminadas y la metieron en barriles; unas 1400 toneladas fueron embarcadas hacia el centro nuclear de Savannah River, en Carolina del Sur. En las zonas con menos contaminación, la tierra se aró y se regó para diluir el plutonio en profundidad. Se destruyeron las cosechas de tomate y Estados Unidos pagó indemnizaciones a los agricultores.' },
      { t: 'p', text: 'La Junta de Energía Nuclear española, y después su sucesor, el **CIEMAT**, iniciaron un programa de vigilancia del suelo, de los alimentos y de los vecinos (el **Proyecto Indalo**) que se ha mantenido durante décadas. Los análisis han detectado plutonio en una parte de los habitantes, en cantidades pequeñas, sin que se haya demostrado un aumento claro de enfermedades; aun así, el estigma y la inquietud nunca desaparecieron del todo.' },
      { t: 'h', text: 'Un problema sin cerrar' },
      { t: 'p', text: 'A principios del siglo XXI, nuevos estudios del CIEMAT mostraron que seguía habiendo zonas contaminadas, en algunos casos donde se habían construido o se iban a construir viviendas. En 2007 el Estado expropió y valló unas 40 hectáreas. Se calcula que quedan del orden de 50 000 metros cúbicos de tierra con plutonio. Además, una parte del plutonio se va transformando con los años en americio-241, otro isótopo radiactivo, por lo que la actividad de algunas zonas aumenta ligeramente con el tiempo. En octubre de 2015, el secretario de Estado John Kerry y el ministro José Manuel García-Margallo firmaron una declaración de intenciones para que Estados Unidos retirara la tierra contaminada, pero el acuerdo vinculante no llegó a firmarse y la limpieza sigue pendiente. En la década de 2010, varios veteranos estadounidenses que participaron en la limpieza de 1966 denunciaron problemas de salud y reclamaron que se reconociera su exposición.' },
      { t: 'h', text: 'Consecuencias' },
      { t: 'list', items: [
        'España prohibió que los aviones con armas nucleares sobrevolaran su territorio, y Estados Unidos reorganizó sus rutas. Dos años después, el [[thule|accidente de Thule]] puso fin a las patrullas aéreas permanentes.',
        'El accidente pesó en la renegociación de los acuerdos sobre las bases. Con el Tratado de Amistad y Cooperación de 1976, Estados Unidos se comprometió a no almacenar armas nucleares en España, y el referéndum sobre la OTAN de 1986 incluyó la prohibición de instalarlas.',
        'Fue uno de los incidentes que los militares estadounidenses llaman **Broken Arrow** («flecha rota»): un accidente con un arma nuclear que no supone riesgo de guerra.',
        'Dos de las carcasas de las bombas se conservan en el Museo Nacional de Ciencia e Historia Nuclear de Albuquerque (Nuevo México).',
      ] },
      { t: 'timeline', items: [
        { date: '17 ene 1966', text: 'Colisión del B-52 y el KC-135 sobre Palomares. Caen cuatro bombas B28.' },
        { date: '17–18 ene 1966', text: 'Se localizan en tierra tres de las bombas; dos han dispersado plutonio.' },
        { date: 'Feb 1966', text: 'Se intensifica la búsqueda en el mar a partir del testimonio de Francisco Simó.' },
        { date: '8 mar 1966', text: 'Baño de Manuel Fraga y del embajador Duke en la playa de Quitapellejos.' },
        { date: 'Mediados mar 1966', text: 'El minisubmarino Alvin localiza la bomba a unos 770 m de profundidad.' },
        { date: '7 abr 1966', text: 'La bomba es izada a la superficie por el robot CURV.' },
        { date: '1966', text: 'Unas 1400 toneladas de tierra contaminada se envían a Estados Unidos.' },
        { date: '2007', text: 'El Estado expropia y valla unas 40 hectáreas todavía contaminadas.' },
        { date: 'Oct 2015', text: 'Declaración de intenciones España–EE. UU. para completar la limpieza, aún sin ejecutar.' },
      ] },
      { t: 'sim', preset: 'B28 (EE. UU.)', label: 'Simular la potencia de una B28 (lo que no llegó a ocurrir)' },
    ],
    related: ['thule', 'goldsboro', 'plutonio', 'bomba-de-hidrogeno', 'bomba-de-caida-libre', 'carrera-armamentistica'],
  },

  // ───────────────────────────── THULE ─────────────────────────────
  {
    id: 'thule',
    title: 'El accidente de Thule (1968)',
    cat: 'acc',
    order: 2,
    summary: 'Un B-52 con cuatro bombas termonucleares se incendió y se estrelló sobre el hielo marino de Groenlandia, cerca de la base aérea de Thule. El accidente acabó con las patrullas permanentes de bombarderos nucleares.',
    tags: ['Thule', 'Groenlandia', 'Dinamarca', 'B-52', 'B28', 'Crested Ice', 'Flecha Rota', 'Chrome Dome', 'Pituffik', 'plutonio', '1968'],
    blocks: [
      { t: 'p', text: 'La base aérea de Thule (hoy Pituffik), en el noroeste de Groenlandia, albergaba uno de los grandes radares de alerta temprana contra misiles soviéticos. Como un ataque por sorpresa podía empezar destruyéndolo, el Mando Aéreo Estratégico mantenía un B-52 en vuelo sobre la zona para confirmar visualmente si la base seguía en pie. Era una de las misiones de la operación Chrome Dome, la misma a la que pertenecía el avión de [[palomares|Palomares]].' },
      { t: 'facts', rows: [
        ['Fecha', '21 de enero de 1968'],
        ['Lugar', 'Hielo de la bahía de North Star, a unos 12 km de la base de Thule (Groenlandia)'],
        ['Avión', 'B-52G de la base de Plattsburgh (Nueva York)'],
        ['Armas', '4 bombas termonucleares B28'],
        ['Víctimas', '1 tripulante muerto; 6 supervivientes'],
        ['Explosión nuclear', 'Ninguna; el explosivo convencional de las cuatro bombas estalló'],
      ] },
      { t: 'h', text: 'El accidente' },
      { t: 'p', text: 'Antes del vuelo, un tripulante había colocado unos cojines de espuma junto a una salida de aire caliente bajo un asiento de la cabina. Durante la misión se prendieron. El humo llenó el avión, la tripulación no consiguió apagar el fuego y, sin electricidad, el piloto ordenó abandonar el aparato cuando estaban cerca de la base. Seis de los siete hombres saltaron y sobrevivieron, algunos tras horas a temperaturas de decenas de grados bajo cero; el tercer piloto, Leonard Svitenko, murió. El B-52 se estrelló a gran velocidad sobre el hielo marino. El explosivo convencional de las cuatro bombas estalló con el impacto y el combustible ardió durante horas, de modo que el plutonio y otros materiales se esparcieron sobre varios kilómetros de hielo.' },
      { t: 'h', text: 'La limpieza en la noche polar' },
      { t: 'p', text: 'La operación de limpieza, llamada **Crested Ice**, se hizo en pleno invierno ártico, con oscuridad casi permanente, temperaturas de hasta −40 °C y viento constante. Había prisa: si el hielo se fundía en primavera, los restos y la contaminación acabarían en el fondo del mar. Militares estadounidenses y trabajadores daneses de la base recogieron los restos del avión y de las bombas y el hielo y la nieve contaminados, que se metieron en depósitos y se enviaron a Estados Unidos. Una parte del material atravesó el hielo y quedó en el fondo de la bahía.' },
      { t: 'h', text: 'Un escándalo político en Dinamarca' },
      { t: 'p', text: 'Dinamarca, a la que pertenecía Groenlandia, tenía una política oficial que prohibía las armas nucleares en su territorio. El accidente demostró que aviones con bombas atómicas volaban sobre la isla. En 1995 se supo que en 1957 el primer ministro H. C. Hansen había dado a entender a Estados Unidos, de forma tácita, que no pondría objeciones. Cientos de antiguos trabajadores daneses de la base, que atribuían sus enfermedades a la limpieza, reclamaron indemnizaciones y el Gobierno danés acabó pagándoles una compensación. En 2008, un reportaje de la BBC afirmó que una parte de una de las bombas nunca se recuperó; los gobiernos estadounidense y danés sostienen que todo el material quedó contabilizado.' },
      { t: 'h', text: 'Consecuencias' },
      { t: 'p', text: 'Tras [[palomares|Palomares]] y Thule, los responsables estadounidenses concluyeron que el riesgo de las patrullas aéreas permanentes con armas nucleares superaba su valor militar, más aún cuando los [[misil-balistico|misiles balísticos]] intercontinentales y los submarinos ya garantizaban la capacidad de respuesta de la [[triada-nuclear|tríada nuclear]]. Chrome Dome se canceló ese mismo año. El accidente también impulsó mejoras en la seguridad de las armas, como explosivos convencionales más insensibles a golpes e incendios.' },
      { t: 'sim', preset: 'B28 (EE. UU.)', label: 'Simular la potencia de una B28' },
    ],
    related: ['palomares', 'goldsboro', 'triada-nuclear', 'bomba-de-caida-libre', 'plutonio'],
  },

  // ───────────────────────────── GOLDSBORO ─────────────────────────────
  {
    id: 'goldsboro',
    title: 'El accidente de Goldsboro (1961)',
    cat: 'acc',
    order: 3,
    summary: 'Un B-52 se desintegró en el aire sobre Carolina del Norte y dejó caer dos bombas de 3,8 megatones. En una de ellas, sólo un interruptor impidió que completara la secuencia de armado.',
    tags: ['Goldsboro', 'Carolina del Norte', 'B-52', 'Mark 39', 'Mk 39', 'Flecha Rota', 'Parker Jones', 'Eric Schlosser', 'Command and Control', '1961'],
    blocks: [
      { t: 'p', text: 'Poco después de la medianoche del **24 de enero de 1961**, un B-52G de la base de Seymour Johnson, en Carolina del Norte (la misma de la que despegaría años después el avión de [[palomares|Palomares]]), sufrió una gran fuga de combustible en un ala durante una misión de alerta aérea. Mientras intentaba volver a la base, perdió el control y se partió en el aire a unos 3000 metros de altura, cerca de la ciudad de Goldsboro. Tres de los ocho tripulantes murieron. En la bodega llevaba dos bombas termonucleares **Mark 39**, de unos 3,8 megatones cada una: unas 250 veces la potencia de la bomba de [[hiroshima|Hiroshima]].' },
      { t: 'facts', rows: [
        ['Fecha', '24 de enero de 1961'],
        ['Lugar', 'Faro, cerca de Goldsboro (Carolina del Norte, EE. UU.)'],
        ['Armas', '2 bombas termonucleares Mark 39 de 3,8 Mt'],
        ['Víctimas', '3 tripulantes muertos'],
        ['Explosión nuclear', 'Ninguna'],
        ['Material no recuperado', 'Parte de una de las bombas sigue enterrada en un campo'],
      ] },
      { t: 'h', text: 'Las dos bombas' },
      { t: 'p', text: 'Al romperse el avión, las fuerzas del accidente activaron mecanismos que normalmente sólo se accionan en un lanzamiento real. Una de las bombas se comportó casi como si hubiera sido lanzada a propósito: se abrió su paracaídas y descendió hasta quedar clavada en un campo, con el paracaídas enredado en un árbol. Al examinarla, los técnicos comprobaron que varios de sus dispositivos de seguridad se habían activado. Lo que impidió que la secuencia continuara fue un interruptor de seguridad de la cabina que seguía en posición «seguro».' },
      { t: 'p', text: 'La otra bomba cayó sin paracaídas a gran velocidad sobre un terreno pantanoso y se desintegró. Se recuperaron muchos de sus componentes, pero una parte de la etapa termonuclear quedó enterrada a gran profundidad en el lodo y nunca se extrajo. La Fuerza Aérea compró los derechos sobre el terreno para impedir que se excave.' },
      { t: 'h', text: 'Lo que se supo después' },
      { t: 'p', text: 'Durante décadas, las autoridades sostuvieron que nunca hubo riesgo de explosión. En 1969, un ingeniero del laboratorio de armas Sandia, Parker F. Jones, revisó el caso en un informe interno titulado *Goldsborough Revisited*. Su conclusión fue que un único interruptor de baja tensión, de diseño sencillo y vulnerable a fallos eléctricos, era lo que había separado a Estados Unidos de una catástrofe. El documento fue desclasificado en 2013 a petición del periodista Eric Schlosser, que lo usó en su libro *Command and Control*, dedicado a los accidentes con armas nucleares estadounidenses.' },
      { t: 'p', text: 'El caso de Goldsboro, junto con otros, impulsó una profunda revisión de la seguridad de las armas: dispositivos que sólo permiten el armado si el arma experimenta la secuencia de condiciones de un lanzamiento real, cerraduras electrónicas que exigen un código autorizado y explosivos convencionales más estables. Ni Goldsboro ni [[palomares|Palomares]] estuvieron cerca de una guerra, pero ambos muestran que la seguridad de un arsenal depende de que no falle nada en miles de operaciones rutinarias.' },
    ],
    related: ['palomares', 'thule', 'damascus-titan', 'bomba-de-hidrogeno', 'carrera-armamentistica'],
  },

  // ───────────────────────────── DAMASCUS ─────────────────────────────
  {
    id: 'damascus-titan',
    title: 'El accidente del Titan II en Damascus (1980)',
    cat: 'acc',
    order: 4,
    summary: 'Un dado de llave que cayó por el silo de un misil Titan II en Arkansas perforó su depósito de combustible. Horas después, la explosión lanzó fuera del silo la ojiva de 9 megatones, que no detonó.',
    tags: ['Damascus', 'Arkansas', 'Titan II', 'W53', 'silo', 'misil balístico', 'combustible hipergólico', 'David Livingston', 'Command and Control', '1980'],
    blocks: [
      { t: 'p', text: 'El **Titan II** fue el mayor [[misil-balistico|misil balístico intercontinental]] estadounidense de la Guerra Fría. Llevaba la ojiva W53, de unos 9 megatones, y usaba combustibles **hipergólicos**: un combustible y un oxidante líquidos que arden en cuanto entran en contacto, sin necesidad de encendido. Eso permitía guardar el misil cargado y lanzarlo en un minuto, pero hacía que cualquier fuga fuera extremadamente peligrosa. En 1965, un incendio durante unas obras en un silo de Titan II cerca de Searcy, también en Arkansas, había matado a 53 trabajadores.' },
      { t: 'facts', rows: [
        ['Fecha', '18–19 de septiembre de 1980'],
        ['Lugar', 'Complejo de lanzamiento 374-7, cerca de Damascus (Arkansas, EE. UU.)'],
        ['Misil', 'Titan II con ojiva W53 de unos 9 Mt'],
        ['Causa', 'Caída de un dado de llave de unos 4 kg dentro del silo'],
        ['Víctimas', '1 muerto (David Livingston) y 21 heridos'],
        ['Explosión nuclear', 'Ninguna; la ojiva fue hallada junto a la entrada del complejo'],
      ] },
      { t: 'h', text: 'Un descuido y ocho horas de angustia' },
      { t: 'p', text: 'En la tarde del 18 de septiembre, dos técnicos de la Fuerza Aérea trabajaban en una plataforma dentro del silo. A uno de ellos se le escurrió un dado de llave de casi cuatro kilos, que cayó unos 20 metros, rebotó y perforó la pared del depósito de combustible de la primera etapa. El combustible empezó a salir y a llenar el silo de vapores tóxicos e inflamables. Durante horas, los mandos de la base, el Mando Aéreo Estratégico y el fabricante discutieron qué hacer mientras se evacuaba el centro de control y la población cercana. Hacia las tres de la madrugada del 19, un equipo entró para evaluar la situación y los vapores estallaron.' },
      { t: 'p', text: 'La explosión arrancó la tapa del silo, de unas 740 toneladas, y lanzó la ojiva fuera del complejo. Apareció horas después en una cuneta cercana, dañada pero sin haber detonado ni liberado material radiactivo: sus sistemas de seguridad funcionaron. El aviador David Livingston murió por las heridas y otras 21 personas resultaron heridas.' },
      { t: 'h', text: 'Consecuencias' },
      { t: 'p', text: 'El accidente aceleró la retirada de los Titan II, que ya estaba decidida y se completó en 1987. Mostró también hasta qué punto un error trivial podía poner en marcha una cadena de acontecimientos difícil de controlar en sistemas tan complejos. Eric Schlosser lo convirtió en el hilo conductor de su libro *Command and Control* (2013), que también trata el caso de [[goldsboro|Goldsboro]], y en 2016 se estrenó un documental del mismo título.' },
      { t: 'sim', preset: 'B53 / W53 (EE. UU.)', label: 'Simular la potencia de una W53' },
    ],
    related: ['goldsboro', 'misil-balistico', 'triada-nuclear', 'palomares', 'falsas-alarmas'],
  },

  // ───────────────────────────── FALSAS ALARMAS ─────────────────────────────
  {
    id: 'falsas-alarmas',
    title: 'Falsas alarmas y casi guerras nucleares',
    cat: 'acc',
    order: 5,
    summary: 'Varias veces durante la Guerra Fría y después, un error técnico o un malentendido estuvo a punto de desencadenar una guerra nuclear. En muchos casos lo evitó la decisión de una sola persona.',
    tags: ['falsas alarmas', 'Petrov', 'Stanislav Petrov', 'Arjípov', 'Vasili Arjípov', 'B-59', 'Able Archer', 'NORAD', 'cohete noruego', 'Yeltsin', 'maletín nuclear', 'Oko', 'RYaN', 'casi guerra nuclear'],
    blocks: [
      { t: 'p', text: 'La lógica de la [[destruccion-mutua-asegurada|disuasión nuclear]] exige que cada bando pueda responder a un ataque antes de que los misiles enemigos destruyan los suyos. Un misil intercontinental tarda unos 30 minutos en cruzar el planeta, y uno lanzado desde un submarino, mucho menos. Eso deja a los dirigentes unos pocos minutos para decidir si una alerta es real. En esas condiciones, un fallo de los sensores o un malentendido político pueden ser tan peligrosos como una decisión deliberada.' },
      { t: 'h', text: 'Vasili Arjípov y el submarino B-59 (1962)' },
      { t: 'p', text: 'El 27 de octubre de 1962, el día más tenso de la [[crisis-de-los-misiles|crisis de los misiles de Cuba]], destructores estadounidenses acosaban al submarino soviético B-59 cerca de Cuba y lanzaban cargas de profundidad de práctica para obligarlo a emerger. El submarino llevaba días sin contacto con Moscú, con el aire viciado y temperaturas altísimas, y su tripulación no sabía si la guerra había empezado. Llevaba también un torpedo con carga nuclear. El capitán, Valentín Savitski, quiso usarlo. Según los testimonios posteriores, el lanzamiento requería el acuerdo de los tres oficiales principales: el capitán, el oficial político y **Vasili Arjípov**, jefe de la flotilla de submarinos. Arjípov se negó y convenció a los demás de emerger. Su papel no se conoció hasta décadas después.' },
      { t: 'h', text: 'Las alarmas del NORAD (1979–1980)' },
      { t: 'p', text: 'El 9 de noviembre de 1979, las pantallas del Mando Norteamericano de Defensa Aeroespacial (NORAD) mostraron un ataque soviético masivo. Se dio la alerta a los bombarderos y despegaron cazas interceptores. El consejero de Seguridad Nacional, Zbigniew Brzezinski, fue despertado de madrugada y estaba a punto de llamar al presidente Carter cuando le informaron de que era una falsa alarma: se había cargado en el sistema real una cinta de entrenamiento que simulaba un ataque. En junio de 1980 volvió a ocurrir, esta vez por un chip defectuoso de un ordenador de comunicaciones que escribía cifras al azar en los mensajes de alerta.' },
      { t: 'h', text: 'Stanislav Petrov (1983)' },
      { t: 'p', text: 'Poco después de la medianoche del **26 de septiembre de 1983**, el teniente coronel **Stanislav Petrov** estaba de guardia en el búnker de Serpujov-15, cerca de Moscú, que recibía los datos del nuevo sistema de satélites de alerta temprana Oko. El sistema anunció el lanzamiento de un misil Minuteman desde Estados Unidos y después de otros cuatro. El protocolo exigía informar a sus superiores, lo que podía desencadenar una respuesta. Petrov razonó que un ataque real empezaría con cientos de misiles, no con cinco; que el sistema era nuevo y poco fiable; y que los radares terrestres no confirmaban nada. Informó de una avería. Tenía razón: los satélites habían confundido con lanzamientos los reflejos del Sol en nubes altas. La tensión era máxima, porque tres semanas antes la Unión Soviética había derribado el vuelo 007 de Korean Air Lines con 269 personas a bordo. La historia se conoció en 1998. Petrov murió en 2017.' },
      { t: 'h', text: 'Able Archer 83' },
      { t: 'p', text: 'Entre el 7 y el 11 de noviembre de 1983, la OTAN celebró **Able Archer 83**, un ejercicio que simulaba la escalada hasta una guerra nuclear con procedimientos y comunicaciones nuevos y más realistas. La dirección soviética llevaba desde 1981 convencida de que Estados Unidos preparaba un ataque por sorpresa: el KGB había puesto en marcha la operación RYaN para detectar sus señales, y el discurso del «imperio del mal», la Iniciativa de Defensa Estratégica y el despliegue de los misiles Pershing II en Europa reforzaban esa sospecha. Algunos mandos soviéticos interpretaron el ejercicio como una posible tapadera y pusieron en alerta parte de sus fuerzas, incluidos aviones con armas nucleares. El agente doble Oleg Gordievski informó a los británicos de la alarma en Moscú. Un informe de inteligencia estadounidense de 1990, desclasificado en 2015, concluyó que el ejercicio pudo poner las relaciones entre ambas potencias al borde de la guerra sin que Occidente lo supiera.' },
      { t: 'h', text: 'El cohete noruego (1995)' },
      { t: 'p', text: 'El 25 de enero de 1995, científicos noruegos y estadounidenses lanzaron desde la isla de Andøya un cohete de investigación Black Brant XII para estudiar las auroras boreales. Noruega había avisado a Rusia semanas antes, pero el aviso no llegó a los operadores de radar. Su trayectoria se parecía a la de un misil lanzado desde un submarino para provocar un pulso electromagnético antes de un ataque. Por primera vez se activó el **maletín nuclear** ruso (el Chéguet) ante el presidente Borís Yeltsin, que consultó con sus mandos durante unos minutos hasta que el cohete cayó en el mar cerca de Svalbard. La Guerra Fría había terminado hacía años.' },
      { t: 'timeline', items: [
        { date: '5 oct 1960', text: 'El radar de alerta de Thule interpreta el eco de la Luna saliendo por el horizonte como un ataque masivo con misiles.' },
        { date: '27 oct 1962', text: 'Vasili Arjípov se niega a autorizar el uso del torpedo nuclear del submarino B-59.' },
        { date: '9 nov 1979', text: 'Una cinta de entrenamiento cargada por error en el NORAD simula un ataque soviético.' },
        { date: 'Jun 1980', text: 'Un chip defectuoso provoca nuevas falsas alarmas en el NORAD.' },
        { date: '26 sep 1983', text: 'Stanislav Petrov considera falsa una alerta de cinco misiles estadounidenses.' },
        { date: '7–11 nov 1983', text: 'El ejercicio Able Archer 83 alarma a la dirección soviética.' },
        { date: '25 ene 1995', text: 'Un cohete científico noruego hace que se active el maletín nuclear de Yeltsin.' },
        { date: '13 ene 2018', text: 'Una falsa alerta de misil balístico en Hawái tarda 38 minutos en ser desmentida.' },
      ] },
      { t: 'note', text: 'Estos episodios alimentan el debate sobre la **alerta máxima** (*launch on warning*): la política de mantener misiles listos para lanzarse en minutos ante un aviso. Muchos expertos proponen alargar los tiempos de decisión precisamente para que un error técnico no pueda convertirse en una guerra; véanse [[arsenales-actuales|arsenales actuales]] y [[triada-nuclear|tríada nuclear]].' },
    ],
    related: ['crisis-de-los-misiles', 'destruccion-mutua-asegurada', 'carrera-armamentistica', 'misil-balistico', 'arsenales-actuales', 'triada-nuclear'],
  },

  // ───────────────────────────── CRITICIDAD ─────────────────────────────
  {
    id: 'accidentes-de-criticidad',
    title: 'Accidentes de criticidad',
    cat: 'acc',
    order: 6,
    summary: 'Cuando material fisible alcanza por accidente las condiciones para una reacción en cadena, emite un destello de radiación mortal. Harry Daghlian y Louis Slotin murieron así en Los Álamos con el mismo núcleo de plutonio, el llamado «núcleo del demonio».',
    tags: ['accidente de criticidad', 'Daghlian', 'Slotin', 'núcleo del demonio', 'demon core', 'Los Álamos', 'Tokaimura', 'destello azul', 'reacción en cadena', 'radiación'],
    blocks: [
      { t: 'p', text: 'Un **accidente de criticidad** se produce cuando una cantidad de material fisible (uranio enriquecido o plutonio) alcanza por error las condiciones para mantener una [[reaccion-en-cadena|reacción en cadena]], fuera de un reactor diseñado para controlarla. No hay una explosión nuclear: en cuanto el material se calienta y se dilata, o alguien lo separa, la reacción se detiene. Pero durante esa fracción de segundo emite un pulso intensísimo de neutrones y rayos gamma que puede ser letal para quien esté a pocos metros. Los testigos describen a menudo un **destello azul**, causado por la ionización del aire, y una sensación de calor. El concepto de [[masa-critica|masa crítica]] explica por qué depende de la cantidad, la forma y lo que rodea al material.' },
      { t: 'h', text: 'Harry Daghlian (agosto de 1945)' },
      { t: 'p', text: 'Tras la guerra, los científicos de [[los-alamos|Los Álamos]] siguieron midiendo las propiedades de los núcleos de plutonio fabricados para las bombas. Uno de ellos, preparado para un posible tercer bombardeo sobre Japón que no llegó a producirse, quedó en el laboratorio. El 21 de agosto de 1945, el físico **Harry Daghlian**, de 24 años, trabajaba solo por la noche, con un vigilante como única compañía, rodeando ese núcleo de bloques que devolvían neutrones hacia él para estudiar cómo se acercaba a la criticidad. Uno de los bloques se le escapó de la mano y cayó sobre el conjunto. Daghlian lo retiró enseguida, pero ya había recibido una dosis mortal. Murió el 15 de septiembre, 25 días después: fue la primera persona fallecida en un accidente de criticidad.' },
      { t: 'h', text: 'Louis Slotin (mayo de 1946)' },
      { t: 'p', text: 'El físico canadiense **Louis Slotin**, de 35 años, era un experto en ese tipo de experimentos, que Richard Feynman había bautizado como «hacerle cosquillas a la cola del dragón». Consistían en acercar a mano dos piezas que envolvían el núcleo para medir la subida de la actividad, manteniéndolas separadas por una pequeña rendija. El 21 de mayo de 1946, mientras hacía una demostración ante siete colegas, sujetaba esa separación con la punta de un destornillador. El destornillador resbaló, las piezas se juntaron y hubo un destello azul. Slotin las separó de un manotazo y con ello detuvo la reacción y probablemente salvó a los demás, que estaban más lejos. Murió nueve días después, el 30 de mayo. Los otros siete sobrevivieron, aunque algunos con dosis importantes.' },
      { t: 'p', text: 'A partir de entonces se prohibieron estos experimentos a mano y se pasaron a realizar por control remoto, a distancia de seguridad. El núcleo, al que más tarde se apodó «núcleo del demonio» (*demon core*), se usó en la prueba Able de la [[operacion-crossroads|operación Crossroads]], en julio de 1946.' },
      { t: 'h', text: 'Otros accidentes' },
      { t: 'p', text: 'Una revisión del laboratorio de Los Álamos del año 2000 contabilizó unos 60 accidentes de criticidad en el mundo desde 1945, con 21 muertos, la mayoría en instalaciones militares o de procesamiento de combustible durante las primeras décadas. El más grave de las últimas décadas ocurrió en **Tokaimura** (Japón) el 30 de septiembre de 1999: en una planta de preparación de combustible, unos operarios siguieron un procedimiento no autorizado y vertieron demasiado material disuelto en un recipiente no previsto para ello. La reacción se mantuvo durante unas 20 horas hasta que se logró detener. Dos de los trabajadores, Hisashi Ouchi y Masato Shinohara, murieron tras meses de agonía; el accidente se clasificó en el nivel 4 de la escala INES.' },
      { t: 'note', text: 'Los accidentes de criticidad son muy distintos de una [[arma-de-fision|explosión nuclear]]: la energía liberada es diminuta y no hay onda expansiva, pero la radiación a corta distancia es comparable a la de la zona más cercana de una bomba. Sus efectos en el cuerpo se describen en [[efectos-en-la-salud|efectos en la salud]].' },
    ],
    related: ['masa-critica', 'reaccion-en-cadena', 'plutonio', 'los-alamos', 'efectos-en-la-salud', 'operacion-crossroads'],
  },

  // ───────────────────────────── KYSHTYM ─────────────────────────────
  {
    id: 'kyshtym',
    title: 'El desastre de Kyshtym (1957)',
    cat: 'acc',
    order: 7,
    summary: 'La explosión de un depósito de residuos radiactivos en el complejo soviético de Mayak contaminó una franja de 300 km de los Urales. Fue el tercer peor accidente nuclear de la historia y permaneció en secreto durante tres décadas.',
    tags: ['Kyshtym', 'Mayak', 'Cheliábinsk-40', 'Oziorsk', 'Urales', 'residuos radiactivos', 'INES 6', 'rastro radiactivo de los Urales orientales', 'Medvédev', 'Techa', 'Karachái', '1957'],
    blocks: [
      { t: 'p', text: 'Para fabricar la primera bomba atómica soviética, el [[programa-sovietico|programa nuclear de la URSS]] construyó entre 1945 y 1948 el complejo **Mayak**, en el sur de los Urales: reactores para producir [[plutonio|plutonio]] y una planta química para separarlo del combustible irradiado. La ciudad de sus trabajadores, Cheliábinsk-40 (hoy Oziorsk), no aparecía en los mapas. Por eso el accidente recibió el nombre de la localidad conocida más cercana, Kyshtym.' },
      { t: 'facts', rows: [
        ['Fecha', '29 de septiembre de 1957'],
        ['Lugar', 'Complejo de Mayak, óblast de Cheliábinsk (URSS)'],
        ['Causa', 'Fallo de la refrigeración de un depósito de residuos de alta actividad'],
        ['Explosión', 'Química, equivalente a unas 70–100 toneladas de TNT'],
        ['Zona contaminada', 'Franja de unos 300 km de largo y más de 20 000 km²'],
        ['Evacuados', 'Unas 10 000 personas'],
        ['Escala INES', 'Nivel 6 (accidente grave)'],
      ] },
      { t: 'h', text: 'El accidente' },
      { t: 'p', text: 'Los residuos líquidos de la separación del plutonio, muy radiactivos, se guardaban en depósitos de acero enterrados. Su propia radiactividad los calienta, por lo que necesitan refrigeración continua. En uno de ellos, el sistema de refrigeración falló y nadie lo reparó. El líquido se evaporó y dejó un residuo seco de sales que, al calentarse, explotó. No fue una explosión nuclear, sino química, pero levantó la tapa de hormigón del depósito y lanzó a la atmósfera una gran cantidad de material radiactivo. La mayor parte cayó cerca; el resto lo llevó el viento hacia el nordeste y formó el **Rastro Radiactivo de los Urales Orientales**, contaminado sobre todo con estroncio-90.' },
      { t: 'p', text: 'Unas 10 000 personas fueron evacuadas de más de una veintena de aldeas, algunas sólo después de días o semanas y sin explicaciones; las casas se derribaron y el ganado se sacrificó. Las estimaciones de las consecuencias sanitarias son muy inciertas por el secreto que rodeó todo el episodio. En 1968, la zona más afectada se convirtió en una reserva natural cerrada.' },
      { t: 'h', text: 'El secreto' },
      { t: 'p', text: 'La URSS no reconoció el accidente hasta 1989. En Occidente lo dio a conocer en 1976 el biólogo soviético exiliado **Zhores Medvédev** en la revista *New Scientist*; documentos desclasificados después mostraron que la CIA sabía desde hacía años que algo grave había ocurrido, pero no lo había hecho público. Por su gravedad, sólo [[chernobil|Chernóbil]] y [[fukushima|Fukushima]] lo superan en la escala INES.' },
      { t: 'h', text: 'Mayak, una herencia contaminada' },
      { t: 'p', text: 'Kyshtym no fue el único problema de Mayak. Entre 1949 y 1956, la planta vertió residuos radiactivos directamente al río Techa, del que bebían decenas de miles de personas río abajo. Después los vertió en el lago Karachái, que llegó a ser uno de los lugares más radiactivos del planeta; en una sequía de 1967 el viento levantó polvo de sus orillas y lo esparció por la región. Mayak sigue funcionando hoy como planta de reprocesamiento. En 2017 se detectó rutenio-106 en el aire de buena parte de Europa, y muchos expertos señalaron a Mayak como origen probable, algo que Rusia negó.' },
    ],
    related: ['programa-sovietico', 'plutonio', 'windscale', 'chernobil', 'radiactividad'],
  },

  // ───────────────────────────── WINDSCALE ─────────────────────────────
  {
    id: 'windscale',
    title: 'El incendio de Windscale (1957)',
    cat: 'acc',
    order: 8,
    summary: 'El núcleo de grafito de un reactor británico para producir plutonio ardió durante tres días en octubre de 1957 y liberó yodo radiactivo sobre Inglaterra. Es el peor accidente nuclear del Reino Unido.',
    tags: ['Windscale', 'Sellafield', 'Cumbria', 'Reino Unido', 'grafito', 'energía de Wigner', 'yodo-131', 'leche', 'Tom Tuohy', 'Cockcroft', 'INES 5', '1957'],
    blocks: [
      { t: 'p', text: 'Tras la guerra, el Reino Unido decidió fabricar su propia bomba atómica y construyó en Windscale, en la costa de Cumbria, dos reactores (llamados *piles*, «pilas») para producir [[plutonio|plutonio]]. Eran reactores sencillos y construidos con prisas: un gran bloque de grafito atravesado por canales con cartuchos de uranio, refrigerado simplemente por aire que unos ventiladores empujaban a través del núcleo y expulsaban por dos altas chimeneas. A última hora, por insistencia del físico John Cockcroft, se añadieron filtros en lo alto de las chimeneas, que muchos consideraron un gasto inútil y que se apodaron «la locura de Cockcroft».' },
      { t: 'facts', rows: [
        ['Fecha', '10–12 de octubre de 1957'],
        ['Lugar', 'Windscale (hoy Sellafield), Cumbria (Inglaterra)'],
        ['Reactor', 'Pila n.º 1, de grafito refrigerada por aire, para producir plutonio'],
        ['Causa', 'Sobrecalentamiento durante una liberación de energía de Wigner'],
        ['Emisión principal', 'Yodo-131'],
        ['Medida principal', 'Prohibición de la leche en unos 500 km² durante cerca de un mes'],
        ['Escala INES', 'Nivel 5'],
      ] },
      { t: 'h', text: 'El incendio' },
      { t: 'p', text: 'El bombardeo de neutrones deforma la estructura del grafito y le hace acumular energía, la llamada **energía de Wigner**. Para liberarla de forma controlada, los operadores calentaban periódicamente el reactor. El 8 de octubre de 1957 iniciaron una de esas operaciones, pero las lecturas de temperatura eran engañosas y aplicaron un segundo calentamiento. Algunos cartuchos de uranio se rompieron y empezaron a arder. El 10 de octubre se comprobó que el núcleo estaba en llamas. Aumentar el aire para enfriarlo sólo avivaba el fuego, y el dióxido de carbono no sirvió de nada.' },
      { t: 'p', text: 'En la mañana del 11 de octubre, el subdirector de la planta, **Tom Tuohy**, decidió inundar el reactor con agua, a pesar del riesgo de que el contacto del agua con el metal incandescente produjera una explosión de hidrógeno. Tuohy subió varias veces al techo del reactor para observar las llamas. Al cerrar después los ventiladores, el fuego se apagó. Los filtros de Cockcroft retuvieron buena parte de las partículas, pero salió a la atmósfera una cantidad importante de **yodo-131** y otros isótopos.' },
      { t: 'h', text: 'Consecuencias' },
      { t: 'p', text: 'El yodo-131 se concentra en la leche de las vacas que pastan en prados contaminados, y de ahí pasa a la tiroides de quien la bebe. Las autoridades prohibieron la venta de leche producida en unos 500 km² alrededor de la planta durante casi un mes y la arrojaron a los ríos y al mar. Las estimaciones actuales atribuyen al accidente del orden de cien a doscientos cuarenta casos de cáncer a lo largo de las décadas siguientes. El Gobierno de Harold Macmillan, que negociaba entonces con Estados Unidos la cooperación nuclear, publicó una versión resumida del informe de la investigación oficial dirigida por William Penney y retuvo el resto; el informe completo no se publicó hasta 1988.' },
      { t: 'p', text: 'Las dos pilas se cerraron y la n.º 1, con restos de combustible dañado dentro, sigue en proceso de desmantelamiento. El emplazamiento pasó a llamarse Sellafield en 1981 y hoy es uno de los mayores complejos de gestión de residuos nucleares de Europa. Ese mismo otoño de 1957 se produjo, al otro lado del telón de acero, el [[kyshtym|desastre de Kyshtym]].' },
    ],
    related: ['kyshtym', 'chernobil', 'plutonio', 'potencias-nucleares', 'efectos-en-la-salud'],
  },

  // ───────────────────────────── CHERNÓBIL ─────────────────────────────
  {
    id: 'chernobil',
    title: 'El accidente de Chernóbil (1986)',
    cat: 'acc',
    order: 9,
    summary: 'El 26 de abril de 1986, una prueba mal planificada en el reactor 4 de la central de Chernóbil (Ucrania) provocó una explosión y un incendio que liberaron una nube radiactiva sobre Europa. Es, con Fukushima, el único accidente de nivel 7.',
    tags: ['Chernóbil', 'Chernobyl', 'Prípiat', 'Ucrania', 'URSS', 'RBMK', 'INES 7', 'liquidadores', 'sarcófago', 'Nuevo Confinamiento Seguro', 'yodo-131', 'cesio-137', 'cáncer de tiroides', 'zona de exclusión', '1986'],
    blocks: [
      { t: 'p', text: 'La central nuclear Vladímir Ilich Lenin, cerca de la ciudad de Prípiat, en la república soviética de Ucrania, tenía cuatro reactores en funcionamiento del tipo **RBMK-1000**, un diseño exclusivamente soviético: grandes reactores moderados con grafito y refrigerados por agua que hierve dentro de miles de canales de presión. Era un diseño barato, potente y que podía recargarse sin detenerse, pero tenía defectos graves que sus operadores no conocían bien.' },
      { t: 'facts', rows: [
        ['Fecha', '26 de abril de 1986, a la 1:23 hora local'],
        ['Lugar', 'Reactor 4 de la central de Chernóbil, junto a Prípiat (Ucrania, entonces URSS)'],
        ['Tipo de reactor', 'RBMK-1000 (grafito y agua en ebullición)'],
        ['Causa inmediata', 'Subida descontrolada de potencia durante una prueba de seguridad'],
        ['Escala INES', 'Nivel 7 (accidente grave)'],
        ['Muertes inmediatas', '2 en la explosión; 28 por síndrome agudo de radiación en 1986'],
        ['Evacuados', 'Unos 116 000 en 1986; unos 350 000 realojados en total'],
        ['Zona de exclusión', 'Unos 2600 km² en Ucrania y una zona similar en Bielorrusia'],
      ] },
      { t: 'h', text: 'La prueba' },
      { t: 'p', text: 'Esa noche se iba a realizar una prueba para comprobar si, tras un corte de electricidad, la turbina que se detenía por inercia podía alimentar las bombas de refrigeración durante el minuto que tardaban en arrancar los generadores diésel. La prueba exigía bajar la potencia del reactor. Empezó a hacerse el 25 de abril, pero la red eléctrica de Kiev necesitaba energía y se aplazó casi diez horas, hasta el turno de noche, menos preparado.' },
      { t: 'p', text: 'Al reducir la potencia, el reactor se «envenenó» con xenón, un producto de fisión que absorbe neutrones, y la potencia cayó casi a cero. Para recuperarla, los operadores retiraron casi todas las barras de control, muy por debajo de los márgenes permitidos, y dejaron el reactor en un estado muy inestable. Además, varios sistemas de seguridad estaban desconectados para la prueba. Cuando ésta empezó, a la 1:23 del 26 de abril, el caudal de agua disminuyó, se formó más vapor y, por un defecto del diseño, más vapor significaba más potencia (el llamado **coeficiente de vacío positivo**). La potencia empezó a subir. El jefe de turno ordenó la parada de emergencia, pero las barras de control tenían en su extremo un segmento de grafito que, al empezar a entrar, aumentó aún más la reacción en la parte baja del núcleo. En pocos segundos la potencia se multiplicó por cientos.' },
      { t: 'p', text: 'Una explosión de vapor levantó la losa superior del reactor, de unas mil toneladas, y destrozó el edificio; segundos después hubo una segunda explosión. Fragmentos del núcleo cayeron sobre los tejados y el grafito expuesto al aire empezó a arder. No fue una [[arma-de-fision|explosión nuclear]], sino una explosión de vapor seguida de un incendio que duró unos diez días y que fue la principal fuente de emisión de radiactividad.' },
      { t: 'h', text: 'Cronología' },
      { t: 'timeline', items: [
        { date: '26 abr, 1:23', text: 'Explosiones en el reactor 4. Los bomberos de la central y de Prípiat acuden sin saber a qué se enfrentan.' },
        { date: '26 abr, madrugada', text: 'Los incendios de los tejados se apagan hacia las 5 de la mañana. El grafito del núcleo sigue ardiendo.' },
        { date: '27 abr', text: 'Evacuación de Prípiat, unas 49 000 personas, en un convoy de más de mil autobuses. Se les dice que será por tres días.' },
        { date: '27 abr – 10 may', text: 'Helicópteros arrojan miles de toneladas de arena, arcilla, plomo y boro sobre el reactor. El incendio se extingue hacia el 10 de mayo.' },
        { date: '28 abr', text: 'La central sueca de Forsmark detecta radiactividad en la ropa de sus trabajadores. Esa noche, la agencia TASS publica un breve comunicado.' },
        { date: '2–6 may', text: 'Se amplía la evacuación a una zona de 30 km de radio.' },
        { date: '14 may', text: 'Mijaíl Gorbachov habla del accidente por televisión.' },
        { date: 'Nov 1986', text: 'Se termina el «sarcófago», una estructura de hormigón y acero construida a toda prisa sobre las ruinas.' },
        { date: '2000', text: 'Se cierra el último reactor en funcionamiento de la central, el 3.' },
        { date: 'Nov 2016', text: 'El Nuevo Confinamiento Seguro, un enorme arco de acero, se desliza sobre el viejo sarcófago.' },
        { date: 'Feb–mar 2022', text: 'Tropas rusas ocupan la central y la zona de exclusión durante la invasión de Ucrania.' },
        { date: 'Feb 2025', text: 'Un dron impacta contra el Nuevo Confinamiento Seguro y daña su cubierta exterior.' },
      ] },
      { t: 'h', text: 'La nube radiactiva' },
      { t: 'p', text: 'El incendio expulsó a la atmósfera en torno al 5 % del material radiactivo del núcleo, incluida la mayor parte de los gases nobles y una fracción importante del yodo y el cesio. Las corrientes llevaron la nube primero hacia Escandinavia y después por casi toda Europa; las zonas más contaminadas estuvieron en Bielorrusia, Ucrania y Rusia, con manchas aisladas allí donde llovió al paso de la nube, desde Escandinavia hasta Austria o Grecia. En España, la contaminación detectada fue muy baja. A diferencia de la [[lluvia-radiactiva|lluvia radiactiva]] de un arma, que contiene sobre todo isótopos de vida muy corta, la de un reactor es rica en isótopos de vida media y larga, como el **cesio-137**, que hace que la zona de exclusión siga hoy contaminada.' },
      { t: 'h', text: 'Los liquidadores' },
      { t: 'p', text: 'Entre 1986 y 1990 participaron en las tareas de control y limpieza unas 600 000 personas, los llamados **liquidadores**: bomberos, soldados, mineros que excavaron bajo el reactor, pilotos de helicóptero y reservistas que limpiaron a pala el tejado del reactor 3, en turnos de pocos segundos, cuando los robots fallaron por la radiación. De los 134 operarios y bomberos diagnosticados con síndrome agudo de radiación, 28 murieron en los meses siguientes. El físico Valeri Legásov, que dirigió la respuesta científica, se suicidó en 1988.' },
      { t: 'h', text: 'Consecuencias sanitarias: unas cifras discutidas' },
      { t: 'p', text: 'El efecto mejor demostrado es el aumento del **cáncer de tiroides** en personas que eran niños o adolescentes en 1986, causado por el yodo-131 de la leche contaminada. El Comité Científico de la ONU sobre los Efectos de las Radiaciones Atómicas (UNSCEAR) contabilizó unos 20 000 casos entre 1991 y 2015 en Bielorrusia, Ucrania y las regiones rusas más afectadas, de los que estima que en torno a una cuarta parte se deben a la radiación (el resto se explica en parte por el aumento de los controles médicos). Por fortuna, es un cáncer que se trata con éxito en la gran mayoría de los casos. Para el resto de los cánceres, las estimaciones de muertes futuras varían enormemente según la población considerada y el modelo de riesgo empleado:' },
      { t: 'compare', head: ['Fuente', 'Muertes por cáncer estimadas', 'Población considerada'], rows: [
        ['Foro de Chernóbil (OMS, OIEA y otros, 2005)', 'Hasta unas 4000', 'Las 600 000 personas más expuestas'],
        ['OMS (2006)', 'Unas 9000', 'Incluyendo a unos 5 millones de residentes en zonas contaminadas'],
        ['Agencia Internacional para la Investigación del Cáncer (2006)', 'Unas 16 000 hasta 2065', 'Toda Europa'],
        ['Informe TORCH (2006)', '30 000–60 000', 'Todo el mundo'],
        ['Greenpeace (2006)', 'Unas 93 000', 'Todo el mundo'],
        ['Yáblokov y otros (2007)', 'Cerca de un millón', 'Todo el mundo; muy criticado por su metodología'],
      ] },
      { t: 'p', text: 'Las cifras más altas se obtienen aplicando el modelo lineal sin umbral a dosis muy pequeñas repartidas entre cientos de millones de personas; las más bajas sólo cuentan a los más expuestos. Ninguna es directamente verificable, porque esos cánceres se mezclan con los cientos de millones de casos que se producen por otras causas. El Foro de Chernóbil señaló además que el mayor problema de salud pública había sido psicológico y social: el desarraigo de los evacuados, la ansiedad y el fatalismo. La explicación de las dosis y sus efectos está en [[efectos-en-la-salud|efectos en la salud]].' },
      { t: 'h', text: 'Consecuencias políticas' },
      { t: 'p', text: 'El silencio inicial de las autoridades, que mantuvieron el desfile del Primero de Mayo en Kiev mientras se conocían los datos de radiación, socavó la confianza en el sistema soviético. Gorbachov escribió años después que Chernóbil fue quizá la verdadera causa del hundimiento de la Unión Soviética, más que su política de reformas. El director de la central, Víktor Briujánov, el ingeniero jefe Nikolái Fomín y el subjefe Anatoli Diátlov fueron condenados a diez años de cárcel. Los RBMK que siguen funcionando en Rusia se modificaron para corregir sus defectos. La zona de exclusión, abandonada por las personas, se ha convertido en un refugio inesperado de fauna salvaje.' },
    ],
    related: ['fukushima', 'efectos-en-la-salud', 'lluvia-radiactiva', 'reaccion-en-cadena', 'radiactividad', 'proteccion-civil'],
  },

  // ───────────────────────────── FUKUSHIMA ─────────────────────────────
  {
    id: 'fukushima',
    title: 'El accidente de Fukushima (2011)',
    cat: 'acc',
    order: 10,
    summary: 'El terremoto y el tsunami del 11 de marzo de 2011 dejaron sin refrigeración la central de Fukushima Daiichi (Japón). Tres reactores se fundieron y varias explosiones de hidrógeno liberaron radiactividad. Es el segundo accidente de nivel 7 de la historia.',
    tags: ['Fukushima', 'Fukushima Daiichi', 'Japón', 'tsunami', 'terremoto de Tōhoku', 'TEPCO', 'fusión del núcleo', 'hidrógeno', 'INES 7', 'evacuación', 'agua tratada', 'ALPS', 'Masao Yoshida', '2011'],
    blocks: [
      { t: 'p', text: 'A las 14:46 del **11 de marzo de 2011**, un terremoto de magnitud 9,0 frente a la costa noreste de Japón, el mayor registrado en el país, sacudió la central nuclear de Fukushima Daiichi, gestionada por la compañía eléctrica TEPCO. Sus tres reactores en funcionamiento (los 1, 2 y 3) se detuvieron automáticamente, como estaba previsto. El terremoto cortó el suministro eléctrico exterior y arrancaron los generadores diésel de emergencia, que mantenían la refrigeración. Hasta ahí, todo funcionaba.' },
      { t: 'facts', rows: [
        ['Fecha', '11 de marzo de 2011'],
        ['Lugar', 'Central de Fukushima Daiichi, prefectura de Fukushima (Japón)'],
        ['Reactores', '6 de agua en ebullición; 3 en funcionamiento, que se fundieron'],
        ['Causa', 'Tsunami de unos 14–15 m que inundó los sistemas eléctricos de emergencia'],
        ['Escala INES', 'Nivel 7 (asignado el 12 de abril de 2011)'],
        ['Emisión', 'En torno a una décima parte de la de Chernóbil'],
        ['Evacuados', 'Más de 150 000 personas en el momento máximo'],
        ['Muertes por radiación', 'Una muerte de un trabajador por cáncer reconocida oficialmente en 2018'],
      ] },
      { t: 'h', text: 'El tsunami y la pérdida de refrigeración' },
      { t: 'p', text: 'Unos cuarenta minutos después del terremoto llegaron las olas del tsunami. El dique de la central estaba diseñado para unos 5,7 metros; el agua alcanzó unos 14 o 15 metros, inundó los edificios de turbinas, ahogó los generadores diésel y los cuadros eléctricos y dejó a los reactores 1 a 4 sin corriente alterna y, en parte, sin baterías. Aunque un reactor detenido ya no produce fisión, el combustible sigue generando mucho calor por la desintegración de los productos de fisión (véase [[radiactividad|radiactividad]]) y necesita refrigeración durante días. Sin ella, el agua se evaporó, el combustible quedó al descubierto y se fundió en los reactores 1, 2 y 3. El revestimiento metálico del combustible, al reaccionar con el vapor a alta temperatura, produjo grandes cantidades de hidrógeno.' },
      { t: 'h', text: 'Cronología' },
      { t: 'timeline', items: [
        { date: '11 mar, 14:46', text: 'Terremoto de magnitud 9,0. Los reactores en funcionamiento se detienen automáticamente.' },
        { date: '11 mar, 15:27–15:41', text: 'Llegan las olas del tsunami. Pérdida total de electricidad en los reactores 1 a 4.' },
        { date: '11–12 mar', text: 'La evacuación se amplía de 3 a 10 y después a 20 km.' },
        { date: '12 mar', text: 'Explosión de hidrógeno en el edificio del reactor 1. El director, Masao Yoshida, mantiene la inyección de agua de mar.' },
        { date: '14 mar', text: 'Explosión de hidrógeno en el edificio del reactor 3.' },
        { date: '15 mar', text: 'Explosión en el edificio del reactor 4 (por hidrógeno procedente del 3) y daños en la contención del 2. Es el día de mayor emisión; el viento la lleva hacia el noroeste.' },
        { date: '12 abr', text: 'El accidente se clasifica en el nivel 7 de la escala INES.' },
        { date: 'Dic 2011', text: 'El Gobierno declara los reactores en «parada fría».' },
        { date: 'Ago 2023', text: 'Comienza el vertido al mar, muy diluido, del agua tratada acumulada en la central.' },
        { date: 'Nov 2024', text: 'Se extrae la primera muestra de combustible fundido del reactor 2, de apenas unos gramos.' },
      ] },
      { t: 'p', text: 'El trabajo de los operarios que se quedaron en la central, a los que la prensa llamó «los 50 de Fukushima», fue decisivo para evitar que la situación empeorara. El director de la central, Masao Yoshida, desobedeció la orden de interrumpir la inyección de agua de mar en el reactor 1, que habría agravado la fusión. Murió de un cáncer de esófago en 2013, que los expertos no relacionaron con la radiación por el poco tiempo transcurrido.' },
      { t: 'h', text: '¿Un desastre natural?' },
      { t: 'p', text: 'La comisión de investigación del Parlamento japonés, presidida por Kiyoshi Kurokawa, concluyó en 2012 que el accidente había sido un desastre «profundamente provocado por el ser humano». TEPCO había recibido en 2008 estudios internos que advertían de que un tsunami podía superar los 15 metros, pero no reforzó la central. El organismo regulador dependía del mismo ministerio que promovía la energía nuclear, y la comisión criticó una cultura de obediencia y de falta de cuestionamiento. La central vecina de Fukushima Daini, sometida al mismo terremoto, conservó una línea eléctrica y logró enfriar sus reactores.' },
      { t: 'h', text: 'Comparación con Chernóbil' },
      { t: 'compare', head: ['', 'Chernóbil (1986)', 'Fukushima (2011)'], rows: [
        ['Causa', 'Prueba mal ejecutada en un reactor con defectos de diseño', 'Tsunami que superó las defensas; pérdida de refrigeración'],
        ['Mecanismo', 'Explosión de vapor e incendio del grafito', 'Fusión del combustible y explosiones de hidrógeno'],
        ['Cesio-137 emitido', '≈ 85 PBq', '≈ 10–15 PBq'],
        ['Destino de la emisión', 'Sobre todo tierra firme en Europa', 'Gran parte hacia el océano Pacífico'],
        ['Muertes por síndrome agudo de radiación', '28', '0'],
        ['Evacuados y realojados', '≈ 350 000', '≈ 160 000 en el máximo'],
        ['Escala INES', '7', '7'],
      ] },
      { t: 'h', text: 'Consecuencias sanitarias y sociales' },
      { t: 'p', text: 'El terremoto y el tsunami dejaron unos 18 500 muertos y desaparecidos en la costa noreste de Japón; la radiación, a ninguna en los primeros días. El UNSCEAR concluyó en sus informes de 2013 y 2021 que no se espera un aumento detectable de cánceres en la población por la radiación recibida. Un programa de exploración de la tiroides de unos 300 000 niños encontró varios cientos de casos de cáncer, pero el UNSCEAR los atribuye sobre todo a la sensibilidad de las ecografías masivas, que detectan tumores que nunca habrían dado síntomas. En 2018, el Gobierno japonés reconoció la muerte por cáncer de pulmón de un trabajador de la central como relacionada con su exposición.' },
      { t: 'p', text: 'El mayor coste humano vino de la evacuación. En la prefectura de Fukushima se han reconocido más de 2000 «muertes relacionadas con el desastre», sobre todo de ancianos y enfermos trasladados de forma precipitada o que vivieron años en alojamientos provisionales. Este dato ha alimentado un debate difícil sobre cuándo evacuar y cuándo es mejor que la gente se refugie en casa; véase [[proteccion-civil|protección civil]].' },
      { t: 'p', text: 'El accidente cambió la política energética de varios países. Japón detuvo todos sus reactores y sólo una parte ha vuelto a funcionar tras nuevas revisiones de seguridad. Alemania decidió en 2011 acelerar el cierre de sus centrales nucleares, que culminó en abril de 2023. El desmantelamiento de Fukushima Daiichi, con la retirada de cientos de toneladas de combustible fundido, se prevé que dure varias décadas.' },
    ],
    related: ['chernobil', 'efectos-en-la-salud', 'radiactividad', 'proteccion-civil', 'unidades-de-radiacion'],
  },
];
