import type { Article } from '../types';

/**
 * Categoría «Impactos cósmicos»: física de la entrada atmosférica y de los impactos
 * (Collins, Melosh y Marcus, 2005), grandes impactos históricos y defensa planetaria.
 */
export const ARTICLES: Article[] = [
  // ───────────────────────────── ASTEROIDES Y COMETAS ─────────────────────────────
  {
    id: 'asteroides-y-cometas',
    title: 'Asteroides, cometas e impactos',
    cat: 'cosmos',
    order: 1,
    summary: 'Cada día caen sobre la Tierra decenas de toneladas de material del espacio. Casi todo se quema en la atmósfera, pero los objetos de decenas de metros o más pueden liberar energías comparables o muy superiores a las de las armas nucleares.',
    tags: ['asteroide', 'cometa', 'meteoroide', 'meteoro', 'meteorito', 'bólido', 'NEO', 'objeto cercano a la Tierra', 'entrada atmosférica', 'ablación', 'fragmentación', 'pancake', 'explosión aérea', 'cráter', 'tsunami', 'Collins', 'Melosh', 'frecuencia de impactos'],
    blocks: [
      { t: 'p', text: 'El sistema solar está lleno de restos de su formación. Los **asteroides** son cuerpos rocosos o metálicos, la mayoría concentrados en el cinturón principal entre Marte y Júpiter. Los **cometas** son bolas de hielo, polvo y roca procedentes de las regiones exteriores que, al acercarse al Sol, desprenden gas y forman su característica cola. Cuando un fragmento pequeño (un **meteoroide**) entra en la atmósfera produce una estela luminosa, el **meteoro** o estrella fugaz; si es muy brillante se llama **bólido**, y si una parte llega al suelo, ese resto es un **meteorito**.' },
      { t: 'p', text: 'Se llaman **objetos cercanos a la Tierra** (NEO, por sus siglas en inglés) los asteroides y cometas cuya órbita los acerca a menos de 1,3 veces la distancia media entre la Tierra y el Sol. Hoy se conocen más de 37 000 asteroides cercanos. Los que miden más de unos 140 metros y pueden pasar a menos de 7,5 millones de kilómetros de la órbita terrestre se consideran **potencialmente peligrosos**. Se cree que ya se han descubierto más del 90 % de los mayores de 1 km, pero menos de la mitad de los de 140 m.' },
      { t: 'h', text: 'De dónde sale la energía' },
      { t: 'p', text: 'Un asteroide no lleva explosivo alguno: su poder destructivo es pura **energía cinética**, que crece con la masa y con el cuadrado de la velocidad. Y las velocidades son enormes: entre 11 km/s, el mínimo para un objeto que cae desde el espacio, y 72 km/s, el máximo para un cometa que llega de frente. Una roca de 50 metros a 20 km/s lleva la energía de unos 10 megatones de TNT, casi 700 bombas de [[hiroshima|Hiroshima]]. La comparación con las [[energia-y-tnt|toneladas de TNT]] es habitual, aunque un impacto reparte esa energía de forma distinta a un arma nuclear: no hay radiación ionizante ni [[lluvia-radiactiva|lluvia radiactiva]].' },
      { t: 'facts', rows: [
        ['Velocidad de entrada', '11–72 km/s (típica, unos 17–20 km/s)'],
        ['Densidad de un cometa', '≈ 600 kg/m³ (hielo poroso)'],
        ['Densidad de un asteroide de escombros', '≈ 1200–2000 kg/m³'],
        ['Densidad de una roca (condrita)', '≈ 3000 kg/m³'],
        ['Densidad de un asteroide metálico', '≈ 7800 kg/m³ (hierro y níquel)'],
        ['Material que cae cada día', 'Decenas de toneladas, casi todo polvo'],
      ] },
      { t: 'diagram', id: 'impact', caption: 'Entrada de un asteroide: compresión del aire, fragmentación, aplastamiento de la nube de fragmentos y explosión aérea o impacto con cráter.' },
      { t: 'h', text: 'La física de la entrada' },
      { t: 'p', text: 'El simulador sigue el modelo de **Collins, Melosh y Marcus (2005)**, el del programa *Earth Impact Effects Program* de la Universidad de Purdue y el Imperial College de Londres, que resume décadas de estudios de bólidos, pruebas nucleares y experimentos de laboratorio. Sus etapas principales son éstas:' },
      { t: 'list', ordered: true, items: [
        '**Frenado y ablación.** Al entrar a decenas de kilómetros por segundo, el objeto comprime el aire que tiene delante hasta convertirlo en plasma incandescente. La resistencia del aire lo frena y el calor funde y vaporiza su superficie (**ablación**). En los objetos pequeños esto basta para consumirlos; en los grandes, la ablación es relativamente poco importante.',
        '**Fragmentación.** La presión del aire sobre el frente del objeto crece con la densidad del aire y con el cuadrado de la velocidad. Cuando supera la resistencia del material, el objeto se rompe. Los asteroides reales están llenos de grietas y son mucho más frágiles que una roca de laboratorio: en el modelo, su resistencia se estima a partir de su densidad. Los cometas y los asteroides de escombros se rompen muy alto; los metálicos, mucho más abajo o nunca.',
        '**Modelo «pancake».** Tras romperse, los fragmentos no se separan como balas: forman una nube que el aire aplasta y ensancha, como una torta (de ahí el nombre inglés *pancake*). Al crecer su sección, el frenado se dispara y la nube pierde casi toda su energía en una distancia corta. Collins y sus colegas consideran que esto ocurre cuando la nube alcanza unas siete veces el diámetro original.',
        '**Explosión aérea o impacto.** Si ese depósito brusco de energía ocurre por encima del suelo, el resultado es una **explosión aérea**: una onda de choque y un pulso de calor parecidos a los de un arma nuclear a gran altura, sin cráter. Así fueron [[tunguska|Tunguska]] y [[cheliabinsk|Cheliábinsk]]. Si el objeto es grande, denso o resistente, llega al suelo casi a plena velocidad y excava un cráter.',
      ] },
      { t: 'h', text: 'Cráteres simples y complejos' },
      { t: 'p', text: 'Al chocar, el objeto se comprime y se vaporiza en una fracción de segundo y una onda de choque se propaga por el terreno. Primero se abre un **cráter transitorio** con forma de cuenco, cuyo tamaño crece con la energía según leyes de escala obtenidas en experimentos (en el modelo, aproximadamente con el diámetro del objeto elevado a 0,78 y la velocidad elevada a 0,44). Después, la gravedad toma el relevo:' },
      { t: 'list', items: [
        '**Cráter simple.** Si es pequeño, las paredes se derrumban un poco hacia dentro y el fondo se rellena de roca triturada (brecha). Queda un cuenco limpio, como el [[meteor-crater|cráter Barringer]] de Arizona. Su diámetro final es aproximadamente 1,25 veces el del cráter transitorio.',
        '**Cráter complejo.** Por encima de unos 3 km de diámetro en la Tierra, el suelo del cuenco rebota hacia arriba y forma un pico central, y las paredes se desploman en terrazas. Los mayores, como [[chicxulub|Chicxulub]], tienen un anillo de picos en lugar de un pico central.',
      ] },
      { t: 'p', text: 'El impacto lanza además **eyecta**, roca pulverizada y fundida cuyo espesor disminuye con el cubo de la distancia; produce un **terremoto** cuya magnitud el modelo estima a partir de una pequeña fracción de la energía; y, si la velocidad es suficiente, una **bola de fuego** de vapor que quema a gran distancia, de forma parecida a la [[bola-de-fuego|bola de fuego]] de un arma nuclear.' },
      { t: 'h', text: 'Impactos en el océano' },
      { t: 'p', text: 'Dos tercios de los impactos caen en el mar. Un objeto grande abre en el agua una cavidad transitoria que se derrumba y genera un **tsunami de impacto**. A diferencia de los tsunamis sísmicos, cuya ola tiene una longitud de cientos de kilómetros, las olas de impacto son más cortas y su amplitud disminuye más deprisa con la distancia, aproximadamente en proporción inversa a ella. Los estudios numéricos de Wünnemann y sus colegas (2010) indicaron que eran menores de lo que se había estimado antes; el simulador usa esa versión más prudente. Al llegar a la costa, la altura de la ola y la zona inundada pueden multiplicarse.' },
      { t: 'h', text: '¿Con qué frecuencia ocurre?' },
      { t: 'p', text: 'Los objetos pequeños son muchísimo más numerosos que los grandes. Combinando las observaciones de bólidos detectados por satélites y sensores de infrasonidos con los recuentos de asteroides de los telescopios se obtiene esta tabla aproximada:' },
      { t: 'compare', head: ['Tamaño', 'Energía típica', 'Frecuencia aproximada', 'Consecuencias', 'Ejemplo'], rows: [
        ['≈ 1 m', '≈ 0,05 kt', 'Decenas de veces al año', 'Bólido brillante; a veces meteoritos', '—'],
        ['≈ 4 m', '≈ 1–5 kt', 'Una vez al año', 'Explosión a 30–40 km de altura, inofensiva', '2008 TC3'],
        ['≈ 20 m', '≈ 500 kt', 'Una vez cada pocas décadas a un siglo', 'Explosión aérea; cristales rotos y heridos', '[[cheliabinsk|Cheliábinsk]]'],
        ['≈ 50 m', '≈ 5–15 Mt', 'Cada varios siglos a un milenio', 'Destrucción de cientos o miles de km²; cráter si es metálico', '[[tunguska|Tunguska]], [[meteor-crater|Barringer]]'],
        ['≈ 140 m', '≈ 100–300 Mt', 'Cada 10 000–20 000 años', 'Destrucción de una región entera', '—'],
        ['≈ 1 km', '≈ 50 000–100 000 Mt', 'Cada medio millón de años, aproximadamente', 'Catástrofe regional y efectos climáticos globales', '—'],
        ['≈ 10 km', '≈ 100 millones de Mt', 'Cada 100 millones de años, aproximadamente', 'Extinción masiva', '[[chicxulub|Chicxulub]]'],
      ] },
      { t: 'note', text: '**Cómo lo calcula Bum.** Para un asteroide o cometa, el simulador calcula la energía cinética a partir del diámetro, la densidad y la velocidad; resuelve la entrada con las ecuaciones de Collins, Melosh y Marcus (2005): altura de fragmentación, aplastamiento de la nube con un factor de 7 y altura de la explosión aérea o velocidad de llegada al suelo; y, si hay impacto, el cráter transitorio y final, la eyecta, el terremoto y la bola de fuego. La onda expansiva se calcula con las mismas curvas que para las armas nucleares, y el tsunami, con el modelo de Wünnemann y colaboradores. El intervalo medio entre impactos de esa energía se estima con el ajuste de Collins y sus colegas, proporcional a la energía en megatones elevada a 0,78.' },
      { t: 'sim', preset: '2008 TC3 (Sudán, 2008)', label: 'Simular 2008 TC3, el primer impacto predicho' },
      { t: 'sim', preset: 'Asteroide de 1 km', label: 'Simular un asteroide de 1 km' },
    ],
    related: ['tunguska', 'cheliabinsk', 'chicxulub', 'meteor-crater', 'defensa-planetaria', 'energia-y-tnt'],
  },

  // ───────────────────────────── TUNGUSKA ─────────────────────────────
  {
    id: 'tunguska',
    title: 'El evento de Tunguska (1908)',
    cat: 'cosmos',
    order: 2,
    summary: 'El 30 de junio de 1908, un objeto de unos 50–60 metros estalló sobre Siberia y derribó unos 80 millones de árboles en más de 2000 km². Es la mayor explosión de origen cósmico de la historia registrada.',
    tags: ['Tunguska', 'Siberia', '1908', 'explosión aérea', 'Kulik', 'Vanavara', 'evenkis', 'bosque derribado', 'Día del Asteroide', 'lago Cheko'],
    blocks: [
      { t: 'p', text: 'Hacia las siete de la mañana del **30 de junio de 1908**, los habitantes de la cuenca del río Podkámennaya Tunguska, en el centro de Siberia, vieron cruzar el cielo una bola de fuego casi tan brillante como el Sol. Después hubo un destello, una sacudida y un estruendo que se oyó a cientos de kilómetros. En la factoría comercial de Vanavara, a unos 65 km, un testigo contó que el calor era tan intenso que sentía arder la camisa, y que la onda expansiva lo tiró del porche de su casa. Los sismógrafos de Irkutsk registraron el temblor y los barómetros de Gran Bretaña, el paso de la onda de presión.' },
      { t: 'facts', rows: [
        ['Fecha', '30 de junio de 1908, hacia las 7:15 hora local'],
        ['Lugar', 'Cuenca del río Podkámennaya Tunguska, Siberia central (Rusia)'],
        ['Tipo', 'Explosión aérea, sin cráter'],
        ['Altura de la explosión', 'Entre unos 5 y 10 km'],
        ['Energía', 'Entre 3 y 15 Mt, según los estudios'],
        ['Objeto', 'Probablemente un asteroide rocoso de unos 50–60 m'],
        ['Bosque derribado', 'Unos 2150 km², unos 80 millones de árboles'],
      ] },
      { t: 'h', text: 'La expedición de Kulik' },
      { t: 'p', text: 'La región era tan remota y el momento político tan convulso (la Revolución y la guerra civil) que nadie investigó sobre el terreno hasta casi veinte años después. En 1927, el mineralogista **Leonid Kulik** llegó por fin a la zona buscando un gran meteorito de hierro. Encontró un paisaje asombroso: árboles derribados en un patrón radial que apuntaba hacia un centro común, extendido por una superficie mayor que la de la provincia de Barcelona. Pero no había cráter. En el centro, los árboles seguían en pie, sin ramas ni hojas, como postes de telégrafo: la onda les había llegado desde arriba. Kulik organizó varias expediciones más; murió en 1942 como prisionero de guerra, sin haber encontrado nunca el meteorito.' },
      { t: 'h', text: 'Qué fue' },
      { t: 'p', text: 'Hoy se sabe que la ausencia de cráter es justo lo que cabe esperar. Un asteroide rocoso de unas decenas de metros que entra a unos 15 km/s se [[asteroides-y-cometas|fragmenta y se aplasta]] en la atmósfera y libera casi toda su energía de golpe a varios kilómetros de altura. El patrón de árboles caídos, con forma de mariposa, permitió reconstruir la trayectoria y la altura de la explosión, de forma parecida a como se analizaban los efectos de las pruebas nucleares atmosféricas. Durante décadas se discutió si el objeto era un fragmento de cometa, lo que explicaría que no se hayan hallado grandes meteoritos; los estudios más recientes se inclinan por un asteroide rocoso. En el suelo y en la resina de los árboles se encontraron esférulas microscópicas de material fundido. Las hipótesis exóticas que se propusieron (antimateria, un pequeño agujero negro, una nave extraterrestre) no tienen ningún apoyo científico.' },
      { t: 'p', text: 'Las estimaciones de la energía han ido bajando: de los 10–15 megatones calculados en los años sesenta a unos 3–5 megatones en algunos modelos modernos, que tienen en cuenta que la bola de fuego de una explosión aérea en movimiento proyecta su energía hacia abajo con más eficacia. En cualquier caso, fue cientos de veces más potente que la bomba de [[hiroshima|Hiroshima]].' },
      { t: 'h', text: 'Un golpe de suerte' },
      { t: 'p', text: 'La zona estaba casi deshabitada; los relatos de los evenkis, pastores de renos de la región, hablan de cabañas derribadas, renos muertos y posiblemente de una o dos víctimas humanas. Durante varias noches, el cielo de Europa y Asia estuvo tan iluminado por el polvo en la alta atmósfera que en Londres se podía leer el periódico a medianoche. Si el objeto hubiera llegado unas horas más tarde, la rotación de la Tierra lo habría situado sobre zonas pobladas de Europa. En recuerdo de este evento, la ONU proclamó en 2016 el 30 de junio **Día Internacional del Asteroide**.' },
      { t: 'sim', preset: 'Tunguska (Siberia, 1908)', label: 'Simular Tunguska sobre cualquier ciudad' },
    ],
    related: ['asteroides-y-cometas', 'cheliabinsk', 'meteor-crater', 'defensa-planetaria', 'onda-expansiva'],
  },

  // ───────────────────────────── CHELIÁBINSK ─────────────────────────────
  {
    id: 'cheliabinsk',
    title: 'El bólido de Cheliábinsk (2013)',
    cat: 'cosmos',
    order: 3,
    summary: 'El 15 de febrero de 2013, un asteroide de unos 19 metros estalló a unos 30 km de altura sobre la ciudad rusa de Cheliábinsk. La onda expansiva rompió miles de ventanas e hirió a unas 1500 personas.',
    tags: ['Cheliábinsk', 'Chelyabinsk', 'Rusia', '2013', 'bólido', 'superbólido', 'explosión aérea', 'cristales', 'Chebarkul', 'cámaras de salpicadero', 'condrita'],
    blocks: [
      { t: 'p', text: 'A las 9:20 de la mañana del **15 de febrero de 2013**, millones de personas en los Urales vieron una bola de fuego cruzar el cielo, durante unos segundos más brillante que el Sol. Era un asteroide de unos 19 metros y unas 12 000 toneladas que entró en la atmósfera a unos 19 km/s, con una trayectoria muy rasante. Se fragmentó y liberó la mayor parte de su energía a unos 30 km de altura, al sur de la ciudad de Cheliábinsk, de más de un millón de habitantes.' },
      { t: 'facts', rows: [
        ['Fecha', '15 de febrero de 2013, 9:20 hora local'],
        ['Lugar', 'Óblast de Cheliábinsk (Rusia)'],
        ['Tamaño', '≈ 19 m, ≈ 12 000 toneladas'],
        ['Velocidad', '≈ 19 km/s, con una inclinación de unos 18° sobre el horizonte'],
        ['Altura de la explosión', '≈ 27–30 km'],
        ['Energía', '≈ 400–500 kt, unas 30 veces Hiroshima'],
        ['Heridos', '≈ 1500, casi todos por cristales'],
        ['Edificios dañados', '≈ 7000'],
      ] },
      { t: 'h', text: 'El minuto y medio de espera' },
      { t: 'p', text: 'El destello y el calor llegaron a la velocidad de la luz y muchas personas se acercaron a las ventanas para ver qué ocurría. La [[onda-expansiva|onda expansiva]] tardó más de un minuto y medio en recorrer los kilómetros que separaban el punto de la explosión del suelo. Cuando llegó, reventó ventanas en un área de cientos de kilómetros cuadrados. De las alrededor de 1500 personas que necesitaron atención médica, la inmensa mayoría tenía cortes por cristales; algunas sufrieron quemaduras leves por el ultravioleta o problemas en los ojos por el destello. Una maestra, Yulia Karbýsheva, al ver el resplandor ordenó a sus alumnos agacharse bajo los pupitres, y resultó herida en los brazos mientras ellos salían ilesos. Es exactamente el consejo que da [[proteccion-civil|protección civil]] ante una explosión.' },
      { t: 'p', text: 'La sobrepresión en la ciudad fue de apenas unas décimas de psi, suficiente para romper cristales pero no para dañar las estructuras, salvo el tejado de una fábrica de zinc que se derrumbó. El simulador muestra bien esa diferencia: a esa distancia, el anillo de cristales rotos es enorme y el de daños estructurales casi inexistente.' },
      { t: 'h', text: 'El primer bólido en directo' },
      { t: 'p', text: 'Cheliábinsk fue el impacto mejor documentado de la historia. Las cámaras de salpicadero, muy extendidas en Rusia, y las de seguridad grabaron la trayectoria desde decenas de ángulos, lo que permitió a los científicos reconstruir su órbita con precisión: procedía del cinturón de asteroides. Los sensores de infrasonidos de la red de vigilancia del Tratado de Prohibición Completa de los Ensayos Nucleares, diseñados para detectar explosiones nucleares, la registraron en todo el planeta; véase [[tratados|tratados]]. Se recogieron miles de meteoritos, una condrita ordinaria; el mayor fragmento, de más de media tonelada, fue extraído en octubre de 2013 del fondo del lago Chebarkul, donde había abierto un agujero de ocho metros en el hielo.' },
      { t: 'p', text: 'Nadie lo vio venir: llegó desde la dirección del Sol, donde los telescopios no pueden observar. Por casualidad, ese mismo día pasó cerca de la Tierra otro asteroide, 2012 DA14, de unos 30 metros, que sí se conocía y que no tenía relación con el de Cheliábinsk. La coincidencia dio un fuerte impulso a la [[defensa-planetaria|defensa planetaria]] y mostró que los objetos de unas decenas de metros son más frecuentes de lo que se creía.' },
      { t: 'sim', preset: 'Cheliábinsk (Rusia, 2013)', label: 'Simular el bólido de Cheliábinsk' },
    ],
    related: ['tunguska', 'asteroides-y-cometas', 'defensa-planetaria', 'onda-expansiva', 'proteccion-civil'],
  },

  // ───────────────────────────── METEOR CRATER ─────────────────────────────
  {
    id: 'meteor-crater',
    title: 'El cráter Barringer (Meteor Crater)',
    cat: 'cosmos',
    order: 4,
    summary: 'En el desierto de Arizona hay un cráter de 1,2 km de diámetro excavado hace unos 50 000 años por un meteorito de hierro. Fue el primero del que se demostró un origen por impacto y es el ejemplo clásico de cráter simple.',
    tags: ['Meteor Crater', 'cráter Barringer', 'Arizona', 'Canyon Diablo', 'meteorito de hierro', 'cráter simple', 'Shoemaker', 'coesita', 'Barringer', 'Gilbert'],
    blocks: [
      { t: 'p', text: 'En la meseta del Colorado, cerca de Flagstaff (Arizona), se abre un cuenco casi perfecto de unos **1,2 km de diámetro** y **170 m de profundidad**, rodeado por un borde que se eleva unos 45 metros sobre la llanura. Es el **cráter Barringer**, más conocido como Meteor Crater. Lo excavó hace unos 50 000 años un asteroide de hierro y níquel de unos 50 metros, cuyos fragmentos, llamados meteoritos Canyon Diablo, todavía se encuentran esparcidos por los alrededores.' },
      { t: 'facts', rows: [
        ['Edad', '≈ 50 000 años'],
        ['Diámetro', '≈ 1,2 km'],
        ['Profundidad actual', '≈ 170 m'],
        ['Objeto', 'Asteroide metálico de unos 50 m'],
        ['Velocidad estimada de impacto', '≈ 12–13 km/s'],
        ['Energía', '≈ 10 Mt'],
        ['Tipo', 'Cráter simple'],
      ] },
      { t: 'h', text: 'Un debate de medio siglo' },
      { t: 'p', text: 'En 1891, el geólogo Grove Karl Gilbert, del Servicio Geológico de Estados Unidos, estudió el cráter y concluyó que se debía a una explosión de vapor volcánico, porque no encontró bajo él la gran masa de hierro que esperaba de un impacto. En 1903, el ingeniero de minas **Daniel Barringer** se convenció de lo contrario, compró los terrenos y pasó veintiséis años perforando en busca de un enorme cuerpo de hierro que pensaba explotar comercialmente. Nunca lo encontró. Hoy sabemos por qué: a esa velocidad, el meteorito se vaporizó y se fundió casi por completo en el impacto, y sólo sobrevivieron fragmentos dispersos. Barringer murió en 1929 sin ver reconocida su idea; su familia todavía es la propietaria del cráter.' },
      { t: 'p', text: 'La prueba definitiva llegó en 1960. El geólogo **Eugene Shoemaker** comparó el cráter con los que habían dejado las [[pruebas-nucleares|pruebas nucleares]] subterráneas poco profundas de Nevada y observó la misma estructura: capas de roca dobladas hacia arriba y volcadas en el borde. Ese mismo año, Shoemaker, Edward Chao y Beth Madsen identificaron en la arena del cráter **coesita**, una forma de sílice que sólo se forma a presiones enormes, imposibles en una erupción. Era la huella inequívoca de una onda de choque de impacto. Shoemaker fundó después la astrogeología y entrenó a los astronautas del programa Apolo en este mismo cráter.' },
      { t: 'h', text: 'Lo que enseñan los modelos' },
      { t: 'p', text: 'Durante años desconcertó la escasez de roca fundida en el cráter. En 2005, Jay Melosh y Gareth Collins, dos de los autores del modelo que usa el simulador, demostraron que el asteroide se había fragmentado parcialmente en la atmósfera y había llegado al suelo a unos 12 km/s, más despacio de lo que se creía, lo que explica que fundiera menos roca. Es un ejemplo perfecto de [[asteroides-y-cometas|cráter simple]]: un cuenco con paredes empinadas y el fondo relleno de roca triturada, sin pico central. Un asteroide rocoso del mismo tamaño no habría llegado al suelo; habría estallado en el aire como en [[tunguska|Tunguska]].' },
      { t: 'sim', preset: 'Cráter Barringer (50 000 a. C.)', label: 'Simular el impacto que excavó el cráter Barringer' },
      { t: 'sim', preset: 'Sikhote-Alin (Rusia, 1947)', label: 'Simular la lluvia de meteoritos metálicos de Sijoté-Alín' },
    ],
    related: ['asteroides-y-cometas', 'tunguska', 'chicxulub', 'pruebas-nucleares', 'shoemaker-levy-9'],
  },

  // ───────────────────────────── CHICXULUB ─────────────────────────────
  {
    id: 'chicxulub',
    title: 'Chicxulub y la extinción de los dinosaurios',
    cat: 'cosmos',
    order: 5,
    summary: 'Hace 66 millones de años, un asteroide de unos 10 km chocó contra la península de Yucatán. El impacto excavó un cráter de unos 180 km y desencadenó la extinción en masa que acabó con los dinosaurios no avianos.',
    tags: ['Chicxulub', 'Yucatán', 'México', 'dinosaurios', 'extinción', 'K-Pg', 'K-T', 'iridio', 'Alvarez', 'Caravaca', 'Zumaia', 'invierno de impacto', 'tsunami', 'cráter complejo', 'Deccan'],
    blocks: [
      { t: 'p', text: 'Hace unos **66 millones de años**, al final del periodo Cretácico, desaparecieron en poco tiempo alrededor de tres cuartas partes de las especies de la Tierra: los dinosaurios no avianos, los pterosaurios, los grandes reptiles marinos, los amonites y buena parte del plancton. La frontera entre el Cretácico y el Paleógeno (el **límite K-Pg**, antes llamado K-T) está marcada en las rocas de todo el planeta por una fina capa de arcilla. Durante más de un siglo nadie supo qué la había producido.' },
      { t: 'facts', rows: [
        ['Edad', '≈ 66 millones de años'],
        ['Lugar', 'Península de Yucatán (México), enterrado bajo sedimentos'],
        ['Diámetro del cráter', '≈ 180 km (cráter complejo con anillo de picos)'],
        ['Objeto', 'Asteroide de unos 10 km, probablemente una condrita carbonácea'],
        ['Energía', 'Del orden de 100 millones de megatones (10²³–10²⁴ J)'],
        ['Consecuencia', 'Extinción de ≈ 75 % de las especies'],
      ] },
      { t: 'h', text: 'La pista del iridio' },
      { t: 'p', text: 'En 1980, el físico **Luis Alvarez**, premio Nobel, su hijo el geólogo **Walter Alvarez** y los químicos Frank Asaro y Helen Michel publicaron que la arcilla del límite en Gubbio (Italia) contenía muchísimo más **iridio** de lo normal. El iridio es raro en la corteza terrestre pero abundante en los meteoritos, así que propusieron que un asteroide de unos 10 km había chocado contra la Tierra y que el polvo había oscurecido el planeta. Ese mismo año, el geólogo neerlandés **Jan Smit** llegó a una conclusión parecida estudiando el límite K-Pg en **Caravaca de la Cruz (Murcia)**. España tiene algunos de los mejores afloramientos del mundo de este límite, como los de Caravaca, Agost (Alicante) o el flysch de **Zumaia** (Guipúzcoa), donde la capa oscura puede verse a simple vista en los acantilados.' },
      { t: 'p', text: 'Faltaba el cráter. Se encontró en un lugar inesperado: en 1978, los geofísicos Glen Penfield y Antonio Camargo, que buscaban petróleo para la compañía mexicana Pemex, habían detectado una enorme estructura circular enterrada bajo Yucatán, pero su hallazgo pasó casi inadvertido. En 1991, Alan Hildebrand y sus colegas lo relacionaron con la extinción tras encontrar cuarzo de choque y esférulas de vidrio de impacto en Haití y en los sondeos de Pemex. En 2016, una expedición científica internacional perforó el anillo de picos del cráter y confirmó cómo se formó.' },
      { t: 'h', text: 'Las horas, días y años después' },
      { t: 'list', items: [
        '**El impacto.** El asteroide atravesó la atmósfera en menos de un segundo y abrió en el fondo del mar poco profundo un cráter transitorio de decenas de kilómetros de hondo que, al derrumbarse, formó el [[asteroides-y-cometas|cráter complejo]] actual. Los modelos indican que llegó con una trayectoria bastante inclinada, de unos 45–60°.',
        '**Terremoto y tsunami.** El temblor equivalió a un terremoto de magnitud superior a 10. El tsunami barrió el golfo de México con olas de más de cien metros cerca del impacto y dejó depósitos en la costa de lo que hoy es Estados Unidos.',
        '**Lluvia de fuego.** Una parte de la roca vaporizada salió de la atmósfera y volvió a caer por todo el planeta en forma de esférulas incandescentes. Su reentrada calentó el aire y pudo provocar incendios en muchos continentes, aunque su extensión sigue debatiéndose.',
        '**Invierno de impacto.** El objetivo era rico en rocas con azufre. El polvo, el hollín de los incendios y, sobre todo, los aerosoles de azufre bloquearon la luz solar durante años: la fotosíntesis se detuvo en gran parte, la temperatura cayó muchos grados y las cadenas alimentarias se desplomaron. Es un fenómeno parecido al [[invierno-nuclear|invierno nuclear]], pero a una escala muchísimo mayor.',
      ] },
      { t: 'p', text: 'Algunos investigadores sostienen que las enormes erupciones volcánicas del Decán, en la India, que ocurrían por la misma época, contribuyeron a la crisis. Hoy la mayoría de los especialistas considera que el impacto fue la causa principal y que, sin él, no habría habido extinción en masa. En el yacimiento de Tanis (Dakota del Norte) se han hallado peces fosilizados con esférulas del impacto en las branquias, que murieron quizá menos de una hora después del choque. Entre los supervivientes estaban los antepasados de las aves y de los mamíferos, incluidos los nuestros.' },
      { t: 'note', text: '**Cómo lo calcula Bum.** El preset de Chicxulub usa un objeto de 10 km a 20 km/s que cae en un mar de 200 m de profundidad. A esta escala, el simulador avisa de que los modelos se extrapolan fuera de su rango: la atmósfera es demasiado fina para que la onda expansiva siga las leyes de escala habituales y los efectos globales (incendios, invierno de impacto) dependen de procesos que no calcula. Las cifras de cráter, terremoto y tsunami siguen siendo una buena aproximación.' },
      { t: 'sim', preset: 'Chicxulub (extinción K-Pg)', label: 'Simular el impacto de Chicxulub' },
      { t: 'sim', preset: 'Popigai (Siberia, 35 Ma)', label: 'Simular Popigai, un gran cráter de hace 35 millones de años' },
    ],
    related: ['asteroides-y-cometas', 'invierno-nuclear', 'meteor-crater', 'defensa-planetaria', 'escalas-de-riesgo'],
  },

  // ───────────────────────────── SHOEMAKER-LEVY 9 ─────────────────────────────
  {
    id: 'shoemaker-levy-9',
    title: 'El cometa Shoemaker-Levy 9 contra Júpiter (1994)',
    cat: 'cosmos',
    order: 6,
    summary: 'En julio de 1994, los fragmentos de un cometa partido por la gravedad de Júpiter chocaron uno tras otro contra el planeta. Fue la primera colisión entre dos cuerpos del sistema solar observada en directo.',
    tags: ['Shoemaker-Levy 9', 'cometa', 'Júpiter', '1994', 'fragmentos', 'límite de Roche', 'Hubble', 'Galileo', 'Eugene Shoemaker', 'Carolyn Shoemaker', 'David Levy'],
    blocks: [
      { t: 'p', text: 'En marzo de 1993, **Carolyn y Eugene Shoemaker** y **David Levy**, que buscaban cometas y asteroides con un pequeño telescopio del observatorio de Monte Palomar (California), descubrieron un objeto extraño: un cometa «aplastado», alargado como un collar de perlas. Era el noveno cometa periódico que descubrían juntos, y por eso recibió el nombre de Shoemaker-Levy 9. Pronto se comprobó que no giraba alrededor del Sol, sino de Júpiter, que lo había capturado probablemente décadas antes.' },
      { t: 'facts', rows: [
        ['Descubrimiento', 'Marzo de 1993, observatorio de Monte Palomar'],
        ['Ruptura', 'Julio de 1992, al pasar a unos 40 000 km de las nubes de Júpiter'],
        ['Fragmentos', '21 visibles, designados con letras de la A a la W'],
        ['Impactos', 'Del 16 al 22 de julio de 1994'],
        ['Velocidad de impacto', '≈ 60 km/s'],
        ['Mayor impacto', 'Fragmento G: unos 6 millones de megatones'],
        ['Manchas', 'Algunas mayores que la Tierra'],
      ] },
      { t: 'h', text: 'Partido por la gravedad' },
      { t: 'p', text: 'En julio de 1992, el cometa había pasado tan cerca de Júpiter que entró dentro del llamado **límite de Roche**: la distancia a la que la diferencia de atracción gravitatoria entre el lado cercano y el lejano de un cuerpo supera la fuerza que lo mantiene unido. Un núcleo de cometa, un agregado frágil de hielo y polvo, no resistió y se partió en una veintena de fragmentos de hasta un kilómetro o dos. Al calcular su órbita, los astrónomos vieron que en su siguiente paso, dos años después, chocarían contra el planeta.' },
      { t: 'h', text: 'Una semana de impactos' },
      { t: 'p', text: 'Entre el 16 y el 22 de julio de 1994, los fragmentos fueron cayendo uno tras otro a unos 60 km/s sobre el hemisferio sur de Júpiter, justo por detrás del borde visible desde la Tierra. La rotación del planeta, que gira en menos de diez horas, mostraba las consecuencias pocos minutos después. La sonda **Galileo**, que viajaba hacia Júpiter, los observó directamente; el telescopio espacial **Hubble** y observatorios de todo el mundo siguieron cada impacto. Las columnas de material ascendieron miles de kilómetros y dejaron manchas oscuras en la atmósfera, visibles incluso con telescopios de aficionado. El impacto del fragmento G, el 18 de julio, liberó una energía del orden de seis millones de megatones y dejó una mancha de unos 12 000 km, casi el diámetro de la Tierra.' },
      { t: 'h', text: 'Una lección para la Tierra' },
      { t: 'p', text: 'El espectáculo convenció a muchos de que los grandes impactos no eran sólo cosa del pasado remoto. Poco después, el Congreso de Estados Unidos encargó a la NASA localizar el 90 % de los asteroides cercanos mayores de 1 km, el origen de los programas modernos de [[defensa-planetaria|defensa planetaria]]. Desde entonces se han observado otros impactos menores en Júpiter, como el que descubrió en 2009 un astrónomo aficionado australiano, Anthony Wesley. Eugene Shoemaker, pionero del estudio de los [[meteor-crater|cráteres de impacto]], murió en un accidente de tráfico en 1997; parte de sus cenizas viajó a bordo de la sonda Lunar Prospector, que se estrelló a propósito en la Luna en 1999. Es la única persona cuyos restos reposan allí.' },
      { t: 'note', text: 'El preset del simulador traslada a la Tierra un fragmento de 2 km con la baja densidad de un cometa y la velocidad de los impactos en Júpiter. Como la energía crece con el cuadrado de la velocidad, un objeto de hielo poroso de ese tamaño a 60 km/s libera más energía que un asteroide rocoso de ese mismo tamaño a 20 km/s.' },
      { t: 'sim', preset: 'Fragmento de Shoemaker-Levy 9', label: 'Simular un fragmento de Shoemaker-Levy 9 sobre la Tierra' },
      { t: 'sim', preset: 'Cometa de 5 km', label: 'Simular un cometa de 5 km' },
    ],
    related: ['asteroides-y-cometas', 'meteor-crater', 'defensa-planetaria', 'chicxulub'],
  },

  // ───────────────────────────── DEFENSA PLANETARIA ─────────────────────────────
  {
    id: 'defensa-planetaria',
    title: 'Defensa planetaria',
    cat: 'cosmos',
    order: 7,
    summary: 'La humanidad es la primera especie capaz de evitar un gran impacto. Para ello hay que encontrar los asteroides peligrosos con años de antelación y, si hace falta, desviarlos, como demostró la misión DART en 2022.',
    tags: ['defensa planetaria', 'DART', 'Dimorphos', 'Didymos', 'Hera', 'NEO Surveyor', 'Vera Rubin', 'LSST', 'impactador cinético', 'tractor gravitatorio', 'explosión nuclear', 'Apophis', '2024 YR4', 'IAWN', 'SMPAG', 'ESA', 'NASA'],
    blocks: [
      { t: 'p', text: 'Un gran impacto es el único desastre natural que, en principio, puede evitarse por completo. La estrategia tiene dos partes: **detectar** los objetos peligrosos y calcular sus órbitas con años o décadas de antelación, y **actuar**, desviando el objeto o, si es pequeño, evacuando la zona de impacto. La clave es el tiempo: un empujón minúsculo aplicado muchos años antes basta para que un asteroide pase de largo, mientras que unas semanas antes no hay casi nada que hacer.' },
      { t: 'h', text: 'Encontrarlos' },
      { t: 'p', text: 'Desde los años noventa, programas de búsqueda automatizados como Catalina Sky Survey, Pan-STARRS o ATLAS escanean el cielo cada noche. Los datos se reúnen en el Centro de Planetas Menores de la Unión Astronómica Internacional, y los sistemas Sentry de la NASA y Aegis de la Agencia Espacial Europea (ESA) calculan las probabilidades de impacto de cada objeto. La red internacional IAWN coordina las alertas, y el grupo SMPAG, respaldado por la ONU desde 2013, estudia cómo responder. Las próximas grandes herramientas son:' },
      { t: 'list', items: [
        '**Observatorio Vera C. Rubin** (Chile). Un telescopio de 8,4 metros con la mayor cámara digital jamás construida, que fotografiará todo el cielo austral visible cada pocas noches durante diez años. Presentó sus primeras imágenes en 2025 y se espera que multiplique el número de asteroides conocidos.',
        '**NEO Surveyor** (NASA). Un telescopio espacial infrarrojo, cuyo lanzamiento está previsto para 2027, que observará desde un punto cercano a la Tierra en dirección al Sol. En infrarrojo, los asteroides oscuros brillan por su calor, y podrá ver objetos que llegan desde la dirección del Sol, como el de [[cheliabinsk|Cheliábinsk]]. Sucede al satélite NEOWISE, que dejó de funcionar en 2024.',
        '**Telescopios de la ESA**, como los telescopios de pruebas de Cebreros (Ávila) y La Silla (Chile) y el futuro Flyeye, con un campo de visión muy amplio. Los observatorios de Canarias participan también en el seguimiento de objetos cercanos.',
      ] },
      { t: 'p', text: 'El sistema ya funciona para objetos pequeños. En octubre de 2008, el asteroide **2008 TC3**, de unos 4 metros, fue descubierto 19 horas antes de entrar en la atmósfera sobre Sudán; se predijo el lugar y la hora y después se recuperaron cientos de sus meteoritos en el desierto. Desde entonces se ha predicho una decena de impactos de objetos pequeños. A finales de 2024, el asteroide **2024 YR4**, de unos 60 metros, llegó a tener una probabilidad de impactar en 2032 de en torno al 3 %, la más alta registrada para un objeto de su tamaño, hasta que nuevas observaciones la descartaron en febrero de 2025. El episodio puso a prueba toda la cadena de alerta; véase [[escalas-de-riesgo|escalas de riesgo]].' },
      { t: 'h', text: 'Desviarlos' },
      { t: 'compare', head: ['Método', 'Cómo funciona', 'Ventajas e inconvenientes'], rows: [
        ['Impactador cinético', 'Una nave choca a gran velocidad contra el asteroide y le transfiere su impulso', 'Probado con DART; requiere años de antelación y funciona mejor con objetos de hasta unos cientos de metros'],
        ['Tractor gravitatorio', 'Una nave se mantiene cerca del asteroide durante años y lo atrae suavemente con su propia gravedad', 'Muy preciso y controlable, pero extremadamente lento'],
        ['Haz de iones', 'Una nave dirige el chorro de sus motores iónicos contra el asteroide para empujarlo', 'Controlable; también lento'],
        ['Explosión nuclear a distancia', 'Una explosión cerca de la superficie vaporiza una capa del asteroide y el material expulsado lo empuja', 'La opción más potente para objetos grandes o con poco tiempo; plantea problemas legales y políticos, porque el Tratado del Espacio Exterior prohíbe colocar armas nucleares en órbita'],
        ['Evacuación', 'Si el objeto es pequeño, se evacua la zona de impacto prevista', 'Útil para objetos de decenas de metros y con aviso suficiente'],
      ] },
      { t: 'p', text: 'La opción nuclear, objeto de muchas películas, se estudia en serio como último recurso: en 2024, un experimento del laboratorio Sandia con pulsos intensos de rayos X sobre pequeñas muestras de roca simuló en miniatura el empujón que produciría. Romper el asteroide en pedazos, en cambio, se considera peligroso salvo que haya poco tiempo, porque los fragmentos podrían seguir en la misma trayectoria. Sobre los tratados que limitan las armas en el espacio, véase [[tratados|tratados]].' },
      { t: 'h', text: 'DART y Hera' },
      { t: 'p', text: 'La misión **DART** (*Double Asteroid Redirection Test*) de la NASA fue la primera prueba real de desvío. Su objetivo era **Dimorphos**, una pequeña luna de unos 160 metros que orbita alrededor del asteroide **Didymos**, de unos 780 metros; ninguno de los dos supone peligro alguno. El 26 de septiembre de 2022, la nave, de algo menos de 600 kg, chocó contra Dimorphos a unos 6 km/s, mientras la sonda italiana LICIACube fotografiaba la colisión. El periodo de la órbita de Dimorphos, de 11 horas y 55 minutos, se acortó en unos 33 minutos, mucho más de lo previsto. La razón es que la colisión lanzó al espacio una enorme cantidad de escombros, y ese chorro empujó al asteroide como un cohete, multiplicando el efecto del choque varias veces.' },
      { t: 'p', text: 'La misión **Hera** de la ESA, lanzada en octubre de 2024, viaja hacia el sistema Didymos para estudiar con detalle el cráter, la masa y la estructura interna de Dimorphos, y llegará previsiblemente en noviembre de 2026. Con esos datos se podrá calibrar con precisión cuánto empuja un impactador cinético. La empresa española GMV es responsable de su sistema de guiado, navegación y control.' },
      { t: 'h', text: 'Apophis, la gran cita de 2029' },
      { t: 'p', text: 'El asteroide **Apophis**, de unos 340–370 metros, causó alarma tras su descubrimiento en 2004: durante unos días se calculó una probabilidad de cerca del 3 % de impacto en 2029. Las observaciones posteriores lo descartaron, también para 2036 y, en 2021, para 2068. El **13 de abril de 2029** pasará a unos 32 000 km de la superficie, más cerca que los satélites geoestacionarios, y será visible a simple vista desde Europa y África. La sonda OSIRIS-APEX de la NASA lo acompañará tras el encuentro para estudiar cómo lo afecta la gravedad terrestre.' },
      { t: 'sim', preset: 'Dimorphos (hipotético)', label: 'Simular qué haría Dimorphos si chocara contra la Tierra' },
      { t: 'sim', preset: 'Apophis (hipotético)', label: 'Simular el impacto de Apophis (que no ocurrirá)' },
      { t: 'sim', preset: '2024 YR4 (hipotético)', label: 'Simular 2024 YR4' },
    ],
    related: ['escalas-de-riesgo', 'asteroides-y-cometas', 'cheliabinsk', 'shoemaker-levy-9', 'tratados'],
  },

  // ───────────────────────────── ESCALAS DE RIESGO ─────────────────────────────
  {
    id: 'escalas-de-riesgo',
    title: 'Las escalas de Turín y de Palermo',
    cat: 'cosmos',
    order: 8,
    summary: 'Dos escalas resumen el peligro de un posible impacto: la de Turín, del 0 al 10, pensada para comunicarlo al público, y la de Palermo, logarítmica, que usan los especialistas para comparar riesgos.',
    tags: ['escala de Turín', 'escala de Palermo', 'Torino', 'riesgo de impacto', 'probabilidad', 'Binzel', 'Apophis', '2024 YR4', 'Bennu', 'Sentry', 'NEOCC'],
    blocks: [
      { t: 'p', text: 'Cuando se descubre un asteroide, su órbita sólo se conoce de forma aproximada. Los programas de cálculo de órbitas proyectan hacia el futuro una «nube» de trayectorias posibles, y si alguna de ellas cruza la Tierra, se le asigna una probabilidad de impacto. Con más observaciones la nube se estrecha y, en casi todos los casos, acaba dejando fuera a la Tierra: por eso es normal que la probabilidad primero **suba** y luego caiga a cero de golpe. Para comunicar este riesgo cambiante sin crear alarma ni restarle importancia se usan dos escalas.' },
      { t: 'h', text: 'La escala de Turín' },
      { t: 'p', text: 'La propuso el astrónomo Richard Binzel, del Instituto Tecnológico de Massachusetts, y fue adoptada en un congreso celebrado en Turín en 1999. Combina la probabilidad de impacto con la energía del objeto y asigna un número entero del 0 al 10, con un código de colores, pensado para el público y los medios.' },
      { t: 'compare', head: ['Nivel', 'Color', 'Significado'], rows: [
        ['0', 'Blanco', 'Sin riesgo: probabilidad nula o prácticamente nula, u objeto tan pequeño que se desintegraría en la atmósfera'],
        ['1', 'Verde', 'Normal: paso cercano rutinario; lo más probable es que nuevas observaciones lo bajen a 0'],
        ['2–4', 'Amarillo', 'Merece la atención de los astrónomos; en el nivel 4, probabilidad superior al 1 % de un impacto con daños regionales'],
        ['5–7', 'Naranja', 'Amenazante: encuentro cercano con posibilidad seria pero incierta de un impacto capaz de causar devastación regional o global'],
        ['8–10', 'Rojo', 'Colisión segura: destrucción local (8), regional (9) o catástrofe climática global (10)'],
      ] },
      { t: 'p', text: 'Hasta ahora ningún objeto ha superado el nivel 4. Lo alcanzó **Apophis** en diciembre de 2004, cuando su probabilidad de impactar en 2029 llegó al 2,7 %. El asteroide **2024 YR4** llegó al nivel 3 en enero de 2025, con una probabilidad máxima de alrededor del 3 % para el año 2032, antes de bajar a 0 en febrero. Los niveles 1 son relativamente frecuentes y casi siempre duran poco.' },
      { t: 'h', text: 'La escala de Palermo' },
      { t: 'p', text: 'La escala de Turín es fácil de entender pero poco precisa. En 2002, un equipo del Laboratorio de Propulsión a Chorro de la NASA, encabezado por Steven Chesley, presentó la **escala de Palermo**, llamada así por un congreso celebrado en esa ciudad italiana. Es una escala técnica y continua que compara el riesgo de un objeto concreto con el **riesgo de fondo**: la probabilidad de que la Tierra reciba, por azar, un impacto de esa misma energía o mayor entre hoy y la fecha del posible impacto.' },
      { t: 'p', text: 'Su valor es el logaritmo decimal de ese cociente. Un valor de 0 significa que el objeto es tan peligroso como el fondo natural; de +1, diez veces más; de −2, cien veces menos. Los valores por debajo de −2 no tienen consecuencias prácticas; entre −2 y 0 merecen seguimiento; por encima de 0 indican un motivo real de preocupación. Al tener en cuenta el tiempo que falta, un posible impacto dentro de diez años puntúa más alto que otro de la misma probabilidad dentro de un siglo. El valor más alto registrado fue el de Apophis en 2004, de alrededor de +1,1.' },
      { t: 'facts', rows: [
        ['Escala de Turín', 'Números enteros del 0 al 10; para el público'],
        ['Escala de Palermo', 'Logarítmica y continua; para los especialistas'],
        ['Máximo histórico en Turín', 'Nivel 4: Apophis (diciembre de 2004)'],
        ['Máximo histórico en Palermo', 'Alrededor de +1,1: Apophis (diciembre de 2004)'],
        ['Listas de riesgo', 'Sentry (NASA) y la lista de riesgo de la ESA'],
      ] },
      { t: 'h', text: 'Riesgos a muy largo plazo' },
      { t: 'p', text: 'Algunos objetos conocidos tienen probabilidades pequeñas pero no nulas de impacto dentro de siglos. El caso más estudiado es **Bennu**, de unos 490 metros, visitado por la sonda OSIRIS-REx, que trajo muestras a la Tierra en 2023: su probabilidad acumulada de impacto hasta el año 2300 es de alrededor de 1 entre 1750 (un 0,06 %, según la NASA en 2021), y la fecha individual más probable es 2182, con alrededor de 1 entre 2700. Otro es el asteroide **(29075) 1950 DA**, de más de un kilómetro, con una pequeña probabilidad para el año 2880. Ninguno de los dos es motivo de alarma, pero ambos se siguen de cerca, porque con siglos de antelación desviar un asteroide sería relativamente sencillo; véase [[defensa-planetaria|defensa planetaria]].' },
      { t: 'sim', preset: 'Bennu (hipotético)', label: 'Simular un impacto de Bennu' },
      { t: 'sim', preset: 'Apophis (hipotético)', label: 'Simular un impacto de Apophis' },
    ],
    related: ['defensa-planetaria', 'asteroides-y-cometas', 'chicxulub', 'tunguska'],
  },
];
