import type { Article } from '../types';

/**
 * Categoría «Efectos»: física de los efectos de una explosión nuclear, contada a partir de
 * «The Effects of Nuclear Weapons» (Glasstone y Dolan, 1977) y de los estudios posteriores,
 * con una explicación de cómo los calcula el simulador.
 */
export const ARTICLES: Article[] = [
  // ───────────────────────────── BOLA DE FUEGO ─────────────────────────────
  {
    id: 'bola-de-fuego',
    title: 'La bola de fuego',
    cat: 'efec',
    order: 1,
    summary: 'En una millonésima de segundo, la energía de un arma nuclear convierte el aire en una esfera de plasma más caliente que el centro del Sol. Su evolución explica casi todos los demás efectos.',
    tags: ['bola de fuego', 'fireball', 'doble destello', 'mínimo térmico', 'plasma', 'rayos X', 'reparto de energía', 'Glasstone', 'bhangmetro', 'Vela'],
    blocks: [
      { t: 'p', text: 'Una explosión química libera su energía en forma de gases calientes que empujan el aire. Una explosión nuclear es distinta desde el primer instante: al terminar la [[fision|fisión]] o la [[fusion|fusión]], la energía queda concentrada en una masa diminuta de material vaporizado a decenas de millones de grados. A esa temperatura la materia no emite sobre todo luz visible, sino **rayos X blandos**, y el aire que rodea el arma los absorbe en pocos metros. Ese aire, calentado de golpe, se convierte en una esfera de gas ionizado y luminoso: la **bola de fuego**.' },
      { t: 'p', text: 'De lo que ocurre dentro de esa esfera durante el primer segundo dependen la [[onda-expansiva|onda expansiva]], el [[radiacion-termica|pulso de calor]], la altura de la [[nube-de-hongo|nube de hongo]] y la cantidad de [[lluvia-radiactiva|lluvia radiactiva]]. Por eso Glasstone y Dolan dedican un capítulo entero a describirla antes de hablar de cualquier daño.' },
      { t: 'h', text: 'Adónde va la energía' },
      { t: 'p', text: 'En una explosión en la atmósfera baja (por debajo de unos 30 km), el reparto típico de la energía de un arma de fisión es aproximadamente el siguiente. Las proporciones cambian con la altura, el diseño y la potencia, pero sirven como regla general:' },
      { t: 'compare', head: ['Forma de energía', 'Fracción aproximada', 'Qué produce'], rows: [
        ['Onda expansiva (choque y viento)', '≈ 50 %', 'Derrumbe de edificios, vuelos de escombros, heridas por cristales'],
        ['Radiación térmica (luz y calor)', '≈ 35 %', 'Quemaduras, ceguera, incendios'],
        ['Radiación nuclear inicial', '≈ 5 %', 'Dosis de rayos gamma y neutrones en el primer minuto'],
        ['Radiación residual', '≈ 10 %', 'Desintegración de los productos de fisión: lluvia radiactiva'],
      ] },
      { t: 'p', text: 'A gran altitud, donde el aire es tenue, este reparto se rompe: casi no hay onda expansiva, los rayos X viajan cientos de kilómetros y aparecen efectos propios como el [[pulso-electromagnetico|pulso electromagnético]]. Y en un arma termonuclear con poca fisión, como la [[tsar-bomba|Tsar Bomba]], la fracción de radiación residual es mucho menor. Para comparar potencias, recuerda que se miden en toneladas de TNT equivalente: véase [[energia-y-tnt|energía y TNT]].' },
      { t: 'diagram', id: 'fireball', caption: 'Fases de la bola de fuego: destello inicial, expansión con el frente de choque, ascenso y formación del hongo.' },
      { t: 'h', text: 'Las fases de la bola de fuego' },
      { t: 'list', ordered: true, items: [
        '**Fase radiativa** (primeras millonésimas de segundo). La esfera crece porque la radiación calienta capas de aire cada vez más alejadas. Es pequeña, casi perfectamente esférica y su superficie alcanza temperaturas de cientos de miles de grados.',
        '**Formación del frente de choque**. Al enfriarse un poco, la radiación deja de avanzar más deprisa que la materia y el gas empieza a empujar el aire como un pistón. Se forma una onda de choque que avanza por delante de la zona más caliente.',
        '**Ocultamiento y mínimo térmico**. El aire comprimido del frente de choque, a unos miles de grados, es opaco: actúa como una cortina que tapa el interior más caliente. Visto desde lejos, el brillo cae bruscamente. Es el **mínimo térmico**, que en un arma de 20 kilotones se produce a las pocas milésimas de segundo.',
        '**Ruptura (breakaway) y segundo máximo**. Cuando el frente de choque se expande y se enfría por debajo de unos 3000 °C, vuelve a ser transparente y deja ver de nuevo el núcleo caliente. El brillo sube hasta un segundo máximo, mucho más largo que el primero. De este segundo pulso procede la inmensa mayoría de la energía térmica: unas cuatro quintas partes.',
        '**Ascenso**. La bola de fuego, mucho más ligera que el aire que la rodea, sube como un globo a más de 100 metros por segundo, arrastra polvo y humo y da lugar a la [[nube-de-hongo|nube de hongo]].',
      ] },
      { t: 'p', text: 'Esta secuencia produce el famoso **doble destello**: un primer fogonazo muy breve, una caída del brillo y un segundo pulso más largo. Ningún fenómeno natural lo produce, así que se convirtió en la firma de las explosiones nucleares. Los satélites estadounidenses Vela llevaban sensores ópticos llamados **bhangmetros** precisamente para detectarlo; el 22 de septiembre de 1979 registraron un doble destello sobre el océano Índico, el llamado incidente Vela, cuyo origen sigue siendo objeto de debate.' },
      { t: 'h', text: 'Tamaño y duración' },
      { t: 'p', text: 'El tamaño máximo de la bola de fuego crece con la potencia, pero despacio: aproximadamente con la potencia elevada a 0,4. La de un arma de 1 kilotón alcanza unos 70 metros de radio; la de 1 megatón, algo más de un kilómetro; la de la Tsar Bomba, de 50 megatones, rondaba los 4 o 5 kilómetros. El tiempo que tarda en llegar el segundo máximo también crece con la potencia: unas centésimas de segundo para unos pocos kilotones y en torno a un segundo para un megatón. En las armas de varios megatones el pulso térmico dura más de diez segundos, lo suficiente para que una persona alcance a cubrirse, aunque casi nunca lo hace porque no sabe lo que está ocurriendo.' },
      { t: 'facts', rows: [
        ['Temperatura inicial', 'Decenas de millones de grados en el material del arma'],
        ['Radio máximo (1 kt)', '≈ 70 m'],
        ['Radio máximo (1 Mt)', '≈ 1,1 km'],
        ['Segundo máximo térmico (1 Mt)', '≈ 1 s después de la detonación'],
        ['Velocidad de ascenso', 'Más de 100 m/s al principio'],
        ['Brillo aparente', 'Varias veces el del Sol a decenas de kilómetros'],
      ] },
      { t: 'h', text: 'Cuando la bola de fuego toca el suelo' },
      { t: 'p', text: 'Si la explosión se produce lo bastante baja como para que la bola de fuego toque la superficie, vaporiza toneladas de tierra y las mezcla con los productos de fisión. Al enfriarse, ese material se condensa en partículas radiactivas que caen en las horas siguientes: es el origen de la [[lluvia-radiactiva|lluvia radiactiva local]]. Si la bola de fuego no toca el suelo, como ocurrió en [[hiroshima|Hiroshima]] y [[nagasaki|Nagasaki]], los productos de fisión suben a gran altura en forma de partículas muy finas y se dispersan por todo el planeta, muy diluidos. La diferencia se explica en [[explosiones-aereas-y-de-superficie|explosiones aéreas y de superficie]].' },
      { t: 'note', text: '**Cómo lo calcula Bum.** El simulador usa la relación de Glasstone y Dolan para el radio máximo de la bola de fuego (unos 70 m multiplicados por la potencia en kilotones elevada a 0,4) y considera que la explosión «toca el suelo» cuando la altura de detonación es menor que ese radio. Cuanto más profundo es el contacto, mayor es la fracción de energía que se pierde en el terreno y mayor la lluvia radiactiva local. Para las explosiones químicas usa una bola de fuego mucho más pequeña y fría, porque un explosivo convencional no alcanza temperaturas comparables.' },
      { t: 'sim', preset: 'Trinity (EE. UU., 1945)', label: 'Simular Trinity, la primera bola de fuego nuclear' },
      { t: 'sim', preset: 'Tsar Bomba (URSS, 1961)', label: 'Simular la Tsar Bomba: una bola de fuego de varios kilómetros' },
    ],
    related: ['nube-de-hongo', 'onda-expansiva', 'radiacion-termica', 'energia-y-tnt', 'prueba-trinity', 'explosiones-aereas-y-de-superficie'],
  },

  // ───────────────────────────── NUBE DE HONGO ─────────────────────────────
  {
    id: 'nube-de-hongo',
    title: 'La nube de hongo',
    cat: 'efec',
    order: 2,
    summary: 'La bola de fuego asciende como un globo de aire caliente, arrastra polvo y humo y forma la nube con forma de seta que se ha convertido en el símbolo de la era nuclear.',
    tags: ['nube de hongo', 'hongo atómico', 'seta', 'tallo', 'sombrero', 'tropopausa', 'estratosfera', 'anillo de condensación', 'nube de Wilson'],
    blocks: [
      { t: 'p', text: 'Pocos segundos después de la detonación, la [[bola-de-fuego|bola de fuego]] ha dejado de brillar pero sigue siendo una burbuja de gas muy caliente y mucho menos densa que el aire que la rodea. Como un globo aerostático gigantesco, empieza a subir. En su ascenso se deforma: el aire más frío de los bordes frena la parte exterior, mientras el centro sigue subiendo, y la burbuja se enrolla sobre sí misma en un **anillo de vórtice** (un toroide) que gira hacia dentro por abajo y hacia fuera por arriba. Ese movimiento es el que da a la nube su forma característica.' },
      { t: 'p', text: 'La corriente ascendente aspira aire, polvo, humo y restos desde el suelo, que suben por el centro y forman el **tallo**. Arriba, el gas se enfría al expandirse, el vapor de agua que contiene (procedente del aire y, si la explosión es de superficie, del suelo) se condensa y la nube se vuelve blanca. El conjunto se aplana al chocar con capas de aire estables y forma el **sombrero**.' },
      { t: 'h', text: 'Hasta dónde sube' },
      { t: 'p', text: 'La altura final depende sobre todo de la potencia y del estado de la atmósfera. Las nubes de unos pocos kilotones se detienen por debajo de la **tropopausa**, la frontera entre la troposfera y la estratosfera, situada a unos 10–16 km según la latitud y la estación. Las de cientos de kilotones la atraviesan, y las de varios megatones se extienden ampliamente por la estratosfera, donde las partículas finas pueden permanecer meses o años. La nube de la [[tsar-bomba|Tsar Bomba]] superó los 60 km de altura y su sombrero llegó a tener unos 100 km de diámetro.' },
      { t: 'compare', head: ['Potencia', 'Altura aproximada de la cima', 'Ejemplo'], rows: [
        ['1 kt', '≈ 7–8 km', 'Arma táctica pequeña'],
        ['15–20 kt', '≈ 12–16 km', '[[hiroshima|Hiroshima]], [[nagasaki|Nagasaki]]'],
        ['1 Mt', '≈ 20–22 km', 'Ojiva estratégica grande'],
        ['15 Mt', '≈ 35–40 km', '[[castle-bravo|Castle Bravo]]'],
        ['50 Mt', '> 60 km', '[[tsar-bomba|Tsar Bomba]]'],
      ] },
      { t: 'p', text: 'La nube alcanza su altura máxima al cabo de unos diez minutos y después el viento la deforma y la arrastra. Esa deriva es la que determina hacia dónde cae la [[lluvia-radiactiva|lluvia radiactiva]]: el viento a la altura del sombrero, que puede ser muy distinto del que sopla en el suelo, es el que más importa.' },
      { t: 'h', text: 'Fenómenos asociados' },
      { t: 'list', items: [
        '**Anillo de condensación o nube de Wilson.** En atmósferas húmedas, la fase de succión que sigue al frente de choque enfría el aire de golpe y aparece durante un instante una cúpula o anillo de niebla alrededor de la explosión. Fue muy visible en las pruebas en el mar, como las de la [[operacion-crossroads|operación Crossroads]].',
        '**Casquetes de hielo (pileus).** Cuando la nube empuja hacia arriba capas de aire húmedo, se forman sobre ella velos de nube lisos y efímeros.',
        '**Nubes no nucleares.** Cualquier explosión o incendio que caliente mucha masa de aire puede formar un hongo: volcanes, grandes incendios o explosiones industriales como la del puerto de Beirut en 2020. La forma de seta no es exclusiva de las armas nucleares, aunque sí lo es su tamaño.',
      ] },
      { t: 'note', text: '**Cómo lo calcula Bum.** El simulador estima la altura de la cima con ajustes empíricos a las nubes observadas en las pruebas atmosféricas: crece con la potencia elevada a algo más de 0,15 por debajo del megatón y a 0,22 por encima, con un tope de unos 80 km. El sombrero se representa con un radio que también crece con la potencia y la base del sombrero se sitúa a la mitad de la altura total. En las explosiones químicas, mucho más frías, la nube sube bastante menos.' },
      { t: 'sim', preset: 'Castle Bravo (EE. UU., 1954)', label: 'Simular la nube de Castle Bravo' },
    ],
    related: ['bola-de-fuego', 'lluvia-radiactiva', 'tsar-bomba', 'operacion-crossroads', 'invierno-nuclear'],
  },

  // ───────────────────────────── ONDA EXPANSIVA ─────────────────────────────
  {
    id: 'onda-expansiva',
    title: 'La onda expansiva',
    cat: 'efec',
    order: 3,
    summary: 'La mitad de la energía de una explosión nuclear se convierte en una onda de choque que aplasta los edificios y en un viento de cientos de kilómetros por hora. Es la principal causa de destrucción en las ciudades.',
    tags: ['onda expansiva', 'onda de choque', 'sobrepresión', 'presión dinámica', 'psi', 'kPa', 'onda de Mach', 'altura óptima', 'raíz cúbica', 'leyes de escala', 'viento', 'OTA'],
    blocks: [
      { t: 'p', text: 'Cuando la [[bola-de-fuego|bola de fuego]] se expande, empuja el aire con tal violencia que se forma una **onda de choque**: una capa delgada en la que la presión, la densidad y la temperatura del aire saltan de golpe. Esa capa se separa de la bola de fuego y avanza sola, al principio a varias veces la velocidad del sonido y después, a medida que se debilita, cada vez más cerca de ella. En una explosión de 1 megatón, el frente tarda unos 10 segundos en recorrer los primeros 5 km y casi un minuto en llegar a 20 km.' },
      { t: 'p', text: 'Detrás del frente, el aire comprimido se mueve en la misma dirección que la onda: es el **viento de la explosión**. Cuando el frente ha pasado, la presión cae por debajo de la normal (la **fase negativa** o de succión) y el viento se invierte durante unos segundos. Muchos testigos de Hiroshima recordaban precisamente ese doble golpe.' },
      { t: 'diagram', id: 'blast', caption: 'La onda de choque: sobrepresión, viento y formación de la onda de Mach en una explosión aérea.' },
      { t: 'h', text: 'Sobrepresión y presión dinámica' },
      { t: 'p', text: 'Glasstone y Dolan describen la onda con dos magnitudes distintas. La **sobrepresión** es el exceso de presión sobre la atmosférica normal: aprieta los objetos desde todos los lados a la vez y es lo que hace estallar paredes, ventanas y tejados, sobre todo en estructuras cerradas. La **presión dinámica** es la fuerza del viento: empuja en una sola dirección y arranca, vuelca y arrastra lo que encuentra, desde coches y árboles hasta personas. Las estructuras abiertas, como puentes o torres de celosía, resisten bien la sobrepresión pero son sensibles al viento; los edificios con muros de carga, al revés.' },
      { t: 'p', text: 'La sobrepresión suele expresarse en **psi** (libras por pulgada cuadrada), la unidad del libro de Glasstone. Un psi equivale a unos 6,9 kilopascales, aproximadamente el 7 % de la presión atmosférica. Parece poco, pero sobre la fachada de una casa supone varias toneladas por metro cuadrado aplicadas en una fracción de segundo.' },
      { t: 'compare', head: ['Sobrepresión', 'Viento máximo', 'Efecto en los edificios', 'Efecto en las personas'], rows: [
        ['0,2–0,5 psi (1,5–3,5 kPa)', '< 30 km/h', 'Rotura de una parte de los cristales', 'Heridas leves por cristales'],
        ['1 psi (7 kPa)', '≈ 60 km/h', 'Rotura general de ventanas; daños en tejados y puertas', 'Muchos heridos por cristales y objetos proyectados'],
        ['2–3 psi (14–21 kPa)', '≈ 110–160 km/h', 'Casas de madera o ligeras gravemente dañadas', 'Heridos graves; algunos muertos'],
        ['5 psi (35 kPa)', '≈ 260 km/h', 'Se derrumba la mayoría de las viviendas', 'Muertes generalizadas por derrumbes y escombros'],
        ['10 psi (70 kPa)', '≈ 470 km/h', 'Edificios de hormigón armado gravemente dañados o derrumbados', 'Casi todos muertos o heridos graves'],
        ['20 psi (140 kPa)', '≈ 800 km/h', 'Destrucción de estructuras de hormigón muy reforzadas', 'Mortalidad cercana al 100 %'],
        ['> 100 psi', 'Supersónico', 'Sólo resisten instalaciones enterradas y endurecidas, como silos', 'Ninguna supervivencia en superficie'],
      ] },
      { t: 'p', text: 'El cuerpo humano es sorprendentemente resistente a la sobrepresión en sí: el umbral de rotura del tímpano está en torno a 5 psi y las lesiones pulmonares graves exigen bastante más. Lo que mata en una ciudad son los **efectos indirectos**: el derrumbe de los edificios, los cristales convertidos en metralla, los objetos que vuelan y el propio cuerpo lanzado contra una pared. Por eso la Oficina de Evaluación Tecnológica del Congreso de EE. UU. (OTA), en su estudio de 1979 *The Effects of Nuclear War*, propuso una regla sencilla para una población urbana: con más de 12 psi muere casi el 98 %; entre 5 y 12 psi, alrededor de la mitad; entre 2 y 5 psi, en torno al 5 %, con muchos heridos; y entre 1 y 2 psi, casi nadie muere pero una cuarta parte resulta herida.' },
      { t: 'h', text: 'Reflexión, onda de Mach y altura óptima' },
      { t: 'p', text: 'Si el arma estalla en el aire, la onda de choque llega primero al suelo justo debajo (la **zona cero**) y se refleja. La onda reflejada viaja por aire ya comprimido y calentado por la primera, así que avanza más deprisa y acaba alcanzándola. Al fusionarse ambas se forma un frente vertical reforzado, el **tallo de Mach** o **onda de Mach**, que barre el terreno con una presión mayor que la que tendría la onda sola. El fenómeno lo describió el físico Ernst Mach en el siglo XIX y John von Neumann lo estudió en detalle durante la Segunda Guerra Mundial.' },
      { t: 'p', text: 'De ahí surge el concepto de **altura óptima**: para cada nivel de sobrepresión existe una altura de detonación que maximiza la superficie que lo recibe. Para destruir viviendas (unos 5 psi) con un arma de 1 kilotón, esa altura ronda los 240 metros; para 1 megatón, unos 2,4 km. Las bombas de [[hiroshima|Hiroshima]] (unos 580 m) y [[nagasaki|Nagasaki]] (unos 500 m) se programaron para estallar cerca de ese óptimo. Contra objetivos muy resistentes, como silos, la altura óptima baja hasta casi el suelo; véase [[explosiones-aereas-y-de-superficie|explosiones aéreas y de superficie]].' },
      { t: 'h', text: 'La ley de la raíz cúbica' },
      { t: 'p', text: 'La regla más útil del libro de Glasstone es la ley de escala: **la distancia a la que se alcanza una sobrepresión determinada crece con la raíz cúbica de la potencia**. La razón es geométrica: la energía de la onda se reparte en un volumen de aire, y el volumen crece con el cubo de la distancia. Si una bomba es mil veces más potente que otra, sus anillos de daño no son mil veces más grandes, sino diez veces (porque 10 × 10 × 10 = 1000), y la superficie arrasada es cien veces mayor.' },
      { t: 'compare', head: ['Potencia (altura óptima)', '20 psi', '5 psi', '1 psi'], rows: [
        ['1 kt', '0,24 km', '0,6 km', '1,7 km'],
        ['15 kt (Hiroshima)', '0,6 km', '1,5 km', '4,2 km'],
        ['1 Mt', '2,4 km', '6 km', '17 km'],
        ['50 Mt', '≈ 9 km', '≈ 22 km', '≈ 60 km'],
      ] },
      { t: 'p', text: 'Esa ley tiene consecuencias estratégicas. Como la superficie destruida sólo crece con la potencia elevada a 2/3, varias ojivas pequeñas repartidas destruyen más superficie que una sola grande de la misma potencia total. Es una de las razones por las que, a partir de los años setenta, los arsenales pasaron de bombas de muchos megatones a misiles con [[mirv|varias ojivas independientes]] de cientos de kilotones.' },
      { t: 'note', text: '**Cómo lo calcula Bum.** Para una explosión en superficie, el simulador usa el ajuste analítico de la curva de 1 kilotón de Glasstone y Dolan que también emplean Collins, Melosh y Marcus (2005), y escala las distancias con la raíz cúbica de la potencia. Para las explosiones aéreas aplica un factor de refuerzo por la onda de Mach calibrado con las tablas de *The Effects of Nuclear Weapons* (con 1 kt a la altura óptima: 20 psi a 0,24 km, 5 psi a 0,6 km y 1 psi a 1,7 km). El viento máximo se obtiene de la sobrepresión con las relaciones de Rankine-Hugoniot, y el tiempo de llegada del frente se integra a partir de la velocidad del choque. Para las víctimas usa probabilidades continuas ajustadas a la regla de la OTA descrita arriba. En explosiones de energía enorme, como los grandes impactos de asteroides, reduce el alcance porque la atmósfera finita impide que la ley de la raíz cúbica siga valiendo.' },
      { t: 'sim', preset: 'Little Boy — Hiroshima (1945)', label: 'Simular Hiroshima: una explosión aérea a la altura óptima' },
      { t: 'sim', preset: 'B83-1 (EE. UU.)', label: 'Simular un arma de 1,2 megatones' },
    ],
    related: ['bola-de-fuego', 'radiacion-termica', 'explosiones-aereas-y-de-superficie', 'hiroshima', 'mirv', 'energia-y-tnt'],
  },

  // ───────────────────────────── RADIACIÓN TÉRMICA ─────────────────────────────
  {
    id: 'radiacion-termica',
    title: 'La radiación térmica',
    cat: 'efec',
    order: 4,
    summary: 'Un tercio de la energía de la explosión sale en forma de luz y calor. Viaja a la velocidad de la luz, provoca quemaduras a kilómetros de distancia, ciega e incendia ciudades enteras.',
    tags: ['radiación térmica', 'pulso térmico', 'quemaduras', 'cal/cm²', 'fluencia', 'ceguera por destello', 'tormenta de fuego', 'incendios', 'quemaduras de tercer grado', 'sombras de Hiroshima'],
    blocks: [
      { t: 'p', text: 'Alrededor del 35 % de la energía de una explosión aérea sale de la [[bola-de-fuego|bola de fuego]] como radiación térmica: luz visible, ultravioleta e infrarrojo. A diferencia de la [[onda-expansiva|onda expansiva]], que tarda segundos en llegar, el calor viaja a la velocidad de la luz y alcanza a las víctimas antes de que hayan podido reaccionar. Llega en línea recta, así que cualquier objeto opaco que se interponga (una pared, un árbol, una prenda gruesa) da sombra y protege.' },
      { t: 'diagram', id: 'thermal', caption: 'El pulso térmico: alcance de las quemaduras de primer, segundo y tercer grado.' },
      { t: 'h', text: 'La fluencia: calorías por centímetro cuadrado' },
      { t: 'p', text: 'Lo que determina el daño es la **fluencia térmica** o exposición radiante: la energía recibida por unidad de superficie. Glasstone la mide en **calorías por centímetro cuadrado** (cal/cm²); una caloría es la energía necesaria para calentar un gramo de agua un grado. Para hacerse una idea, el Sol de mediodía en verano aporta unas 0,03 cal/cm² por segundo; un arma de un megatón puede depositar 10 cal/cm² a más de 10 km en un par de segundos, el equivalente a varios minutos de sol abrasador concentrados en un instante.' },
      { t: 'p', text: 'La fluencia disminuye con el cuadrado de la distancia, como cualquier luz que se reparte sobre una esfera cada vez mayor, y además el aire la absorbe y la dispersa. La **visibilidad** importa mucho: con niebla, nubes bajas o contaminación, el alcance de las quemaduras puede reducirse a la mitad o menos; con nieve en el suelo o nubes por encima de la explosión, que reflejan la luz, puede aumentar.' },
      { t: 'h', text: 'Quemaduras de primer, segundo y tercer grado' },
      { t: 'compare', head: ['Efecto', 'Qué ocurre', 'Fluencia aprox. (20 kt)', 'Fluencia aprox. (1 Mt)'], rows: [
        ['Quemadura de 1.er grado', 'Enrojecimiento y dolor, como una quemadura solar fuerte; cura sin cicatriz', '≈ 2–2,5 cal/cm²', '≈ 3 cal/cm²'],
        ['Quemadura de 2.º grado', 'Ampollas; destruye parte de la piel; deja cicatriz y se infecta con facilidad', '≈ 4–4,5 cal/cm²', '≈ 5–6 cal/cm²'],
        ['Quemadura de 3.er grado', 'Destruye todo el espesor de la piel; necesita injertos; mortal si es extensa', '≈ 6–8 cal/cm²', '≈ 8–10 cal/cm²'],
        ['Ignición de materiales', 'Prenden papel, hojas secas, telas oscuras; incendios generalizados', '≈ 10–12 cal/cm²', '≈ 15 cal/cm²'],
      ] },
      { t: 'p', text: 'Una curiosidad física: las armas más potentes necesitan **más** fluencia para causar la misma quemadura. Su pulso térmico dura más, y la piel tiene tiempo de disipar una parte del calor; con una bomba pequeña, la misma energía llega de golpe. Por eso los umbrales de la tabla crecen ligeramente con la potencia.' },
      { t: 'p', text: 'La ley de escala también es distinta de la de la onda expansiva. Si el aire fuera perfectamente transparente, la distancia a la que se recibe una fluencia dada crecería con la raíz cuadrada de la potencia; la absorción atmosférica la reduce a algo más cerca de la potencia elevada a 0,4. Como eso es más que la raíz cúbica de la onda, **cuanto mayor es el arma, más dominan las quemaduras sobre la destrucción por la onda**. Con una bomba de 1 megatón y aire claro, las quemaduras de tercer grado llegan a unos 12 km, mucho más allá de la zona de 5 psi (unos 6 km).' },
      { t: 'h', text: 'Lo que se vio en Hiroshima y Nagasaki' },
      { t: 'p', text: 'En [[hiroshima|Hiroshima]] hubo quemaduras por destello en la piel expuesta hasta unos 3,5 km de la zona cero. Los médicos japoneses describieron **quemaduras de perfil**: sólo en el lado del cuerpo que miraba hacia la explosión. Las telas oscuras absorbían más calor que las claras, y en algunas víctimas el dibujo estampado de los kimonos quedó grabado en la piel. El calor dejó también las célebres **sombras**: superficies de piedra o madera que se decoloraron excepto donde una persona u objeto las tapaba, como en las escaleras de una sucursal del banco Sumitomo. Los [[hibakusha|supervivientes]] con quemaduras extensas sufrieron después queloides, cicatrices gruesas que fueron uno de los estigmas más visibles.' },
      { t: 'h', text: 'Ceguera por destello' },
      { t: 'p', text: 'El ojo es el órgano más vulnerable. Mirar hacia la explosión, aunque sea por reflejo, produce **ceguera por destello**: un deslumbramiento temporal que puede durar desde segundos hasta media hora y que, de día, se extiende a decenas de kilómetros; de noche, con la pupila dilatada, mucho más lejos. Si la imagen de la bola de fuego se enfoca directamente sobre la retina, puede quemarla y dejar un punto ciego permanente. Ese riesgo afecta a distancias aún mayores, sobre todo de noche y en explosiones a gran altitud, y era una preocupación seria para los pilotos.' },
      { t: 'h', text: 'Incendios y tormentas de fuego' },
      { t: 'p', text: 'El pulso térmico prende miles de fuegos a la vez: cortinas, papeles, tejados de madera, hierba seca. La onda expansiva, que llega después, apaga algunos pero también rompe conductos de gas, vuelca estufas y llena las calles de escombros que impiden apagarlos. Si los incendios son densos y se unen, pueden formar una **tormenta de fuego**: un único incendio gigantesco que crea su propio sistema de vientos, aspira aire desde todas direcciones con fuerza de huracán y consume todo lo que hay dentro. Hiroshima sufrió una tormenta de fuego que comenzó unos veinte minutos después de la explosión y arrasó unos 11 km². Nagasaki, con una orografía de valles, no llegó a tenerla. Los incendios masivos son también la clave del [[invierno-nuclear|invierno nuclear]].' },
      { t: 'note', text: '**Cómo lo calcula Bum.** El simulador calcula la fluencia como la energía térmica (en torno al 35 % de la potencia en una explosión aérea, menos si la bola de fuego toca el suelo) repartida sobre una esfera y multiplicada por un factor de transmisión atmosférica que depende de la visibilidad que hayas elegido. Los umbrales de quemaduras e ignición se escalan ligeramente con la potencia, tal como describe Glasstone. Para estimar víctimas, sólo cuenta como expuesta a las quemaduras la fracción de la población que está al aire libre, que depende de la hora del día.' },
      { t: 'sim', preset: 'W88 (EE. UU.)', label: 'Simular una ojiva de 475 kilotones' },
    ],
    related: ['bola-de-fuego', 'onda-expansiva', 'hiroshima', 'hibakusha', 'invierno-nuclear', 'efectos-en-la-salud'],
  },

  // ───────────────────────────── RADIACIÓN INICIAL ─────────────────────────────
  {
    id: 'radiacion-inicial',
    title: 'La radiación nuclear inicial',
    cat: 'efec',
    order: 5,
    summary: 'En el primer minuto, la explosión emite rayos gamma y neutrones capaces de causar una dosis mortal a más de un kilómetro. Es decisiva en las armas pequeñas y casi irrelevante en las grandes.',
    tags: ['radiación inicial', 'radiación inmediata', 'rayos gamma', 'neutrones', 'dosis', 'rem', 'gray', 'activación neutrónica', 'radiación ionizante'],
    blocks: [
      { t: 'p', text: 'Glasstone y Dolan llaman **radiación nuclear inicial** a la que se emite durante el primer minuto tras la explosión. El límite es algo arbitrario pero tiene sentido físico: al cabo de un minuto la [[nube-de-hongo|nube]] ha subido tanto que la radiación de los productos de fisión que contiene ya casi no llega al suelo cercano. Lo que se recibe después se considera radiación residual, sobre todo la de la [[lluvia-radiactiva|lluvia radiactiva]].' },
      { t: 'p', text: 'Aunque sólo se lleva alrededor del 5 % de la energía, esta radiación es muy penetrante: atraviesa paredes que detienen el calor y el viento. Sus efectos en el cuerpo se miden como dosis absorbida, en gray o en rad, o como dosis equivalente, en sievert o en rem; las unidades se explican en [[unidades-de-radiacion|unidades de radiación]].' },
      { t: 'h', text: 'De dónde viene' },
      { t: 'list', items: [
        '**Rayos gamma inmediatos**, emitidos en el propio acto de la [[fision|fisión]]. La mayoría quedan atrapados en el material del arma, así que contribuyen relativamente poco.',
        '**Rayos gamma de los productos de fisión**, emitidos por los núcleos radiactivos recién formados dentro de la bola de fuego mientras ésta todavía está cerca del suelo. Son la fuente principal.',
        '**Rayos gamma de captura**: los neutrones que escapan del arma chocan con los núcleos de nitrógeno del aire y les arrancan rayos gamma de alta energía.',
        '**Neutrones**, que escapan de las reacciones de fisión y, sobre todo, de las de [[fusion|fusión]]. Viajan más despacio que la luz y llegan en una fracción de segundo; son muy dañinos para los tejidos.',
      ] },
      { t: 'h', text: 'Por qué importa tanto en las armas pequeñas' },
      { t: 'p', text: 'La radiación se debilita con la distancia de dos maneras: por la dispersión geométrica (el cuadrado de la distancia) y, sobre todo, por la **absorción en el aire**, que la reduce de forma exponencial. Cada pocos cientos de metros de aire la dosis cae a la mitad, de modo que el alcance de una dosis dada apenas crece con la potencia. Según las tablas de Glasstone, la dosis de unos 500 rem, letal para la mitad de las personas sin tratamiento, se alcanza a estas distancias:' },
      { t: 'compare', head: ['Potencia', 'Alcance aproximado de 500 rem', 'Alcance de 5 psi (onda)', 'Qué domina'], rows: [
        ['1 kt', '≈ 0,8 km', '≈ 0,6 km', 'La radiación llega más lejos que la destrucción'],
        ['20 kt', '≈ 1,4 km', '≈ 1,6 km', 'Ambas similares (Hiroshima, Nagasaki)'],
        ['1 Mt', '≈ 2,3 km', '≈ 6 km', 'La onda y el calor matan mucho más lejos'],
        ['20 Mt', '≈ 4,7 km', '≈ 16 km', 'La radiación inicial es irrelevante'],
      ] },
      { t: 'p', text: 'En un arma de pocos kilotones, mucha gente podría sobrevivir a la onda y al calor dentro de un edificio sólido y aun así recibir una dosis mortal. Esa idea llevada al extremo es la [[bomba-de-neutrones|bomba de neutrones]]: un arma pequeña diseñada para que la radiación, y no la onda, sea el efecto principal. En [[hiroshima|Hiroshima]] y [[nagasaki|Nagasaki]], muchas de las personas que murieron en las semanas siguientes con caída del pelo, hemorragias e infecciones habían recibido radiación inicial, no lluvia radiactiva; sus síntomas se describen en [[efectos-en-la-salud|efectos en la salud]].' },
      { t: 'h', text: 'Protección y radiactividad inducida' },
      { t: 'p', text: 'Los materiales densos y gruesos protegen: unos centímetros de hormigón o de tierra reducen la dosis de rayos gamma a la mitad, y los materiales ricos en hidrógeno, como el agua o el propio hormigón húmedo, frenan bien los neutrones. Los neutrones tienen además otro efecto: al ser capturados por algunos núcleos del suelo (sodio, manganeso, aluminio) los vuelven radiactivos. Esa **radiactividad inducida** en la zona cero de una explosión aérea es intensa durante horas o días, pero queda muy localizada.' },
      { t: 'note', text: '**Cómo lo calcula Bum.** El simulador ancla la dosis a la tabla de Glasstone de alcance oblicuo (distancia en línea recta desde el punto de la explosión) para varias potencias e interpola entre ellas. Alrededor de ese punto, la dosis cae con el cuadrado de la distancia multiplicado por una exponencial que representa la absorción del aire. Después convierte la distancia oblicua en distancia sobre el suelo teniendo en cuenta la altura de detonación y, al estimar víctimas, supone que los edificios reducen la dosis media a la mitad. Muestra anillos de 100, 500, 1000 y 5000 rem.' },
      { t: 'sim', preset: 'W54 / Davy Crockett (EE. UU.)', label: 'Simular un arma minúscula en la que domina la radiación' },
    ],
    related: ['unidades-de-radiacion', 'efectos-en-la-salud', 'bomba-de-neutrones', 'radiactividad', 'lluvia-radiactiva'],
  },

  // ─────────────────────── EXPLOSIONES AÉREAS Y DE SUPERFICIE ───────────────────────
  {
    id: 'explosiones-aereas-y-de-superficie',
    title: 'Explosiones aéreas, de superficie y subterráneas',
    cat: 'efec',
    order: 6,
    summary: 'La misma bomba produce efectos muy distintos según explote en el aire, en el suelo, bajo tierra, bajo el agua o en el espacio. La altura decide entre la destrucción máxima de una ciudad y la lluvia radiactiva masiva.',
    tags: ['explosión aérea', 'explosión en superficie', 'explosión subterránea', 'explosión submarina', 'gran altitud', 'altura de detonación', 'cráter', 'Sedan', 'Baker', 'oleada de base', 'silos'],
    blocks: [
      { t: 'p', text: 'La altura de detonación es, después de la potencia, el factor que más cambia lo que ocurre. Glasstone y Dolan distinguen varios tipos de explosión y cada uno tiene usos militares, consecuencias y huellas diferentes.' },
      { t: 'h', text: 'Explosión aérea' },
      { t: 'p', text: 'Es aquella en la que la [[bola-de-fuego|bola de fuego]] no llega a tocar el suelo. Aprovecha la reflexión de la [[onda-expansiva|onda expansiva]] y la onda de Mach para extender el área de daño, y como no hay obstáculos entre la bola de fuego y el terreno, el [[radiacion-termica|pulso térmico]] alcanza su máximo. Es la opción para destruir objetivos «blandos» y extensos, como ciudades, puertos o bases aéreas. Su gran diferencia es que **apenas produce lluvia radiactiva local**: los productos de fisión suben a la estratosfera en partículas muy finas y caen meses o años después, diluidos sobre medio planeta. Ése fue el caso de [[hiroshima|Hiroshima]] y [[nagasaki|Nagasaki]].' },
      { t: 'h', text: 'Explosión en superficie' },
      { t: 'p', text: 'La bola de fuego toca el suelo. Una parte de la energía se gasta en excavar un **cráter** y en sacudir el terreno, y el área de daño por la onda es algo menor que en una explosión aérea. A cambio, se alcanzan presiones enormes cerca de la zona cero, lo que la hace útil contra objetivos endurecidos: silos de misiles, búnkeres de mando o presas. El precio es la **lluvia radiactiva local**: la explosión arranca miles de toneladas de tierra, las mezcla con los productos de fisión y las deja caer a sotavento durante las horas siguientes. Una guerra contra silos, como la que se planificaba en la [[destruccion-mutua-asegurada|Guerra Fría]], sería por tanto una guerra con lluvia radiactiva masiva.' },
      { t: 'p', text: 'El cráter de una explosión en superficie es más modesto de lo que suele imaginarse: con 1 megatón en suelo seco, las fórmulas de Glasstone dan del orden de 300 metros de diámetro; en terrenos saturados de agua o de coral es mucho mayor, y Castle Bravo dejó en el arrecife de Bikini un cráter de unos 2 km. La prueba Sedan, de 104 kilotones y realizada en 1962 en Nevada a unos 200 m de profundidad dentro del programa de usos pacíficos Plowshare, dejó un cráter de unos 390 m de ancho y casi 100 m de hondo; la tierra levantada llevó contaminación hasta varios estados.' },
      { t: 'h', text: 'Explosión subterránea' },
      { t: 'p', text: 'Si la carga está enterrada a poca profundidad, la explosión rompe la superficie, forma un cráter y lanza una nube de polvo muy contaminada. A gran profundidad, en cambio, la energía queda contenida: vaporiza y funde la roca alrededor, forma una cavidad y produce una sacudida que los sismógrafos registran en todo el mundo. Así se hicieron casi todas las [[pruebas-nucleares|pruebas nucleares]] tras el [[tratados|Tratado de Prohibición Parcial]] de 1963. Las armas penetrantes, como la B61-11, buscan acoplar mejor la energía al terreno para destruir búnkeres, pero ninguna penetra lo suficiente como para contener la explosión.' },
      { t: 'h', text: 'Explosión submarina' },
      { t: 'p', text: 'Bajo el agua, la onda de choque se transmite con mucha más eficacia que en el aire y es devastadora para los barcos. La prueba Baker de la [[operacion-crossroads|operación Crossroads]] (1946), a 27 metros de profundidad en el atolón Bikini, levantó una columna de agua de unos dos kilómetros cuyo colapso produjo una **oleada de base**: una nube de gotas radiactivas que barrió la flota fondeada y la contaminó tanto que muchos barcos tuvieron que ser hundidos. También genera olas, aunque mucho menores que las de un tsunami sísmico; véase [[torpedo-nuclear|torpedo nuclear]].' },
      { t: 'h', text: 'Explosión a gran altitud y en el espacio' },
      { t: 'p', text: 'Por encima de unos 30 km, el aire es tan tenue que no hay apenas onda expansiva ni bola de fuego convencional. Los rayos X recorren cientos de kilómetros y los efectos dominantes pasan a ser el [[pulso-electromagnetico|pulso electromagnético]], las auroras artificiales y los cinturones de radiación que dañan satélites. La prueba Starfish Prime de 1962 es el caso más estudiado.' },
      { t: 'compare', head: ['Tipo', 'Área de daño por onda', 'Pulso térmico', 'Lluvia radiactiva local', 'Uso típico'], rows: [
        ['Aérea (altura óptima)', 'Máxima', 'Máximo', 'Casi nula', 'Ciudades, bases, objetivos extensos'],
        ['Superficie', 'Algo menor, presión máxima en el centro', 'Algo menor', 'Muy intensa', 'Silos, búnkeres, objetivos endurecidos'],
        ['Subterránea profunda', 'Ninguna en superficie', 'Ninguno', 'Ninguna si queda contenida', 'Pruebas nucleares'],
        ['Submarina', 'Enorme bajo el agua', 'Reducido', 'Agua y espuma radiactivas', 'Antibuque, antisubmarino'],
        ['Gran altitud', 'Casi nula', 'Destello visible a gran distancia', 'Ninguna', 'EMP, antisatélite'],
      ] },
      { t: 'note', text: '**Cómo lo calcula Bum.** En el simulador puedes elegir explosión en superficie, a la altura óptima (la que maximiza el anillo de 5 psi, que escala con la raíz cúbica de la potencia) o a una altura personalizada. La regla clave es geométrica: si la altura es menor que el radio de la bola de fuego, se considera que hay contacto con el suelo, y el grado de contacto decide la fracción de energía térmica perdida, el tamaño del cráter y la cantidad de lluvia radiactiva. Por encima de 30 km se muestra el alcance del pulso electromagnético hasta el horizonte.' },
      { t: 'sim', preset: 'Sedan (EE. UU., 1962)', label: 'Simular Sedan, una explosión de excavación' },
      { t: 'sim', preset: 'Fat Man — Nagasaki (1945)', label: 'Simular Nagasaki, una explosión aérea' },
    ],
    related: ['onda-expansiva', 'lluvia-radiactiva', 'pulso-electromagnetico', 'operacion-crossroads', 'pruebas-nucleares', 'bola-de-fuego'],
  },

  // ───────────────────────────── LLUVIA RADIACTIVA ─────────────────────────────
  {
    id: 'lluvia-radiactiva',
    title: 'La lluvia radiactiva',
    cat: 'efec',
    order: 7,
    summary: 'Las partículas radiactivas que caen de la nube tras una explosión en superficie pueden contaminar miles de kilómetros cuadrados a sotavento. Su radiactividad cae deprisa, y un refugio adecuado reduce la dosis de forma drástica.',
    tags: ['lluvia radiactiva', 'fallout', 'productos de fisión', 'regla del 7-10', 'tasa de dosis', 'refugio', 'factor de protección', 'Castle Bravo', 'Rongelap', 'Daigo Fukuryū Maru', 'WSEG-10', 'polvo radiactivo'],
    blocks: [
      { t: 'p', text: 'Cada [[fision|fisión]] parte un núcleo pesado en dos fragmentos. Esos **productos de fisión** son una mezcla de más de 300 isótopos de unos 36 elementos distintos, casi todos radiactivos: algunos se desintegran en segundos y otros tardan décadas. Una explosión de un megatón de fisión produce del orden de una tonelada de ellos. Si la explosión es aérea, suben a la estratosfera y se dispersan por el planeta; si la [[bola-de-fuego|bola de fuego]] toca el suelo, se pegan a la tierra vaporizada y vuelven a caer cerca. Esa caída es la **lluvia radiactiva**.' },
      { t: 'diagram', id: 'fallout', caption: 'La nube arrastra tierra contaminada que cae a sotavento; la radiactividad se reduce a la décima parte cada vez que el tiempo transcurrido se multiplica por siete.' },
      { t: 'h', text: 'Cómo se forma' },
      { t: 'p', text: 'En una explosión en superficie, la bola de fuego vaporiza o funde una enorme cantidad de suelo y la corriente ascendente aspira mucha más. Al enfriarse, los productos de fisión se condensan sobre esas partículas o dentro de ellas. Las más grandes, del tamaño de granos de arena o de sal, caen en la primera hora cerca de la zona cero, en parte desde el propio tallo. Las de tamaño medio caen desde el sombrero durante las horas siguientes, arrastradas por el viento: forman el **penacho** de lluvia radiactiva **local** o temprana, que puede extenderse cientos de kilómetros. Las partículas finísimas, de pocas micras, se quedan en la atmósfera días, meses o años y forman la lluvia radiactiva **global** o retardada, mucho menos intensa.' },
      { t: 'p', text: 'La forma del penacho depende del viento a distintas alturas, no sólo del que sopla en el suelo. Las lluvias de verdad (las de agua) pueden arrastrar las partículas al suelo de golpe y crear «puntos calientes» lejos de la explosión. La lluvia radiactiva visible parece polvo, ceniza o arenilla; en el atolón de Rongelap, tras Castle Bravo, los niños jugaron con ella creyendo que era nieve.' },
      { t: 'h', text: 'La regla del 7-10' },
      { t: 'p', text: 'Como la mezcla contiene muchos isótopos de vida corta, su radiactividad total disminuye muy deprisa al principio y luego cada vez más despacio. Empíricamente, la tasa de dosis cae aproximadamente con el tiempo elevado a −1,2 (la llamada ley de Way-Wigner). Glasstone la tradujo en una regla fácil de recordar: **cada vez que el tiempo transcurrido se multiplica por siete, la tasa de dosis se divide por diez**.' },
      { t: 'compare', head: ['Tiempo tras la explosión', 'Tasa de dosis relativa', 'Ejemplo'], rows: [
        ['1 hora', '1000', '1000 R/h (letal en menos de una hora)'],
        ['7 horas', '100', '100 R/h'],
        ['2 días (49 h)', '10', '10 R/h'],
        ['2 semanas (343 h)', '1', '1 R/h'],
        ['3 meses y medio', '0,1', '0,1 R/h'],
      ] },
      { t: 'p', text: 'La consecuencia práctica es enorme: **las primeras horas son las peligrosas**. Una persona que se refugia bien durante los dos primeros días evita la mayor parte de la dosis que habría recibido. A largo plazo, en cambio, persisten isótopos como el cesio-137 y el estroncio-90, con semividas de unos 30 años, que contaminan el suelo, los cultivos y la leche. Las nociones de semivida y desintegración se explican en [[radiactividad|radiactividad]].' },
      { t: 'h', text: 'Refugio y factor de protección' },
      { t: 'p', text: 'La radiación de la lluvia radiactiva es sobre todo gamma, emitida por las partículas depositadas en el suelo y en los tejados. Protegerse consiste en poner **masa y distancia** entre uno y esas superficies. Se mide con el **factor de protección** (FP): un FP de 10 significa que dentro se recibe la décima parte de la dosis que fuera.' },
      { t: 'compare', head: ['Lugar', 'Factor de protección aproximado'], rows: [
        ['Al aire libre', '1'],
        ['Dentro de un coche', '≈ 1,5–2'],
        ['Planta baja de una casa ligera', '≈ 2–3'],
        ['Sótano de una vivienda', '≈ 10–20'],
        ['Centro de un edificio grande de ladrillo u hormigón (plantas intermedias)', '≈ 10–100'],
        ['Sótano de un edificio grande o aparcamiento subterráneo', '≈ 100–1000'],
        ['Refugio subterráneo diseñado para ello', '> 1000'],
      ] },
      { t: 'p', text: 'Las recomendaciones prácticas se resumen en [[proteccion-civil|protección civil]]. Las consecuencias para el cuerpo de las distintas dosis se explican en [[efectos-en-la-salud|efectos en la salud]].' },
      { t: 'h', text: 'El caso de Castle Bravo' },
      { t: 'p', text: 'El 1 de marzo de 1954, la prueba [[castle-bravo|Castle Bravo]] en el atolón Bikini rindió unos 15 megatones, más del doble de lo previsto, por una reacción del litio que los diseñadores no habían tenido en cuenta. Era una explosión en superficie sobre un arrecife de coral, y el viento había rolado. La lluvia radiactiva cayó sobre los atolones habitados de Rongelap, Ailinginae y Utirik, a más de 150 km. Los habitantes de Rongelap recibieron dosis de hasta casi 2 gray antes de ser evacuados dos días después; sufrieron quemaduras en la piel, caída del pelo y, años más tarde, numerosos problemas de tiroides. El pesquero japonés **Daigo Fukuryū Maru** («Dragón Afortunado n.º 5»), que faenaba fuera de la zona de exclusión, quedó cubierto de ceniza; su radiotelegrafista, Aikichi Kuboyama, murió meses después. El caso desató en Japón el movimiento contra las pruebas y dio a conocer al mundo el peligro de la lluvia radiactiva.' },
      { t: 'note', text: '**Cómo lo calcula Bum.** El simulador usa un modelo analítico simplificado del tipo **WSEG-10**, el que desarrolló el Grupo de Evaluación de Sistemas de Armas del Pentágono en los años sesenta. La actividad total se fija con el dato de Glasstone de unos 3000 R/h por milla cuadrada a la hora 1 por cada kilotón de fisión (unos 7770 R/h·km²), de la que se deposita localmente en torno al 60 % si la bola de fuego toca el suelo plenamente. Sólo cuenta la energía procedente de la fisión, por eso un arma muy «limpia», como la Tsar Bomba, deja menos lluvia radiactiva que otra menos potente. La actividad se reparte en un núcleo alrededor de la zona cero y un penacho a sotavento con tiempos de caída distribuidos de forma logarítmico-normal y una anchura lateral que crece con la distancia. El viento efectivo es la media vectorial entre el suelo y la cima de la nube, con más peso en la capa del sombrero, y si activas el tiempo real usa el perfil de vientos del lugar. Las tasas de dosis se refieren a la hora 1 y decaen según la regla del 7-10.' },
      { t: 'sim', preset: 'Castle Bravo (EE. UU., 1954)', label: 'Simular la lluvia radiactiva de Castle Bravo' },
      { t: 'sim', preset: 'Ivy Mike (EE. UU., 1952)', label: 'Simular Ivy Mike, explosión en superficie de 10 Mt' },
    ],
    related: ['castle-bravo', 'radiactividad', 'proteccion-civil', 'efectos-en-la-salud', 'explosiones-aereas-y-de-superficie', 'pruebas-nucleares'],
  },

  // ───────────────────────────── EMP ─────────────────────────────
  {
    id: 'pulso-electromagnetico',
    title: 'El pulso electromagnético (EMP)',
    cat: 'efec',
    order: 8,
    summary: 'Una explosión nuclear a cientos de kilómetros de altura no destruye nada en el suelo, pero puede inducir corrientes capaces de dañar la electrónica y la red eléctrica de un continente entero.',
    tags: ['pulso electromagnético', 'EMP', 'HEMP', 'E1', 'E2', 'E3', 'Starfish Prime', 'efecto Compton', 'red eléctrica', 'satélites', 'Proyecto K', 'Telstar'],
    blocks: [
      { t: 'p', text: 'Toda explosión nuclear produce un pulso electromagnético: una onda de radio brevísima e intensísima. En una explosión en la superficie, el pulso es fuerte sólo a pocos kilómetros, dentro de la zona que ya ha destruido la [[onda-expansiva|onda expansiva]]. Pero si el arma estalla por encima de la atmósfera, a 30 km o más, el pulso puede alcanzar todo el territorio visible desde el punto de la explosión: con 400 km de altura, un círculo de más de 2000 km de radio, del tamaño de Europa occidental. Es el **pulso electromagnético de gran altitud** (HEMP en inglés).' },
      { t: 'diagram', id: 'emp', caption: 'Los rayos gamma arrancan electrones en la alta atmósfera; el campo magnético terrestre los desvía y la corriente resultante radia el pulso hacia el suelo.' },
      { t: 'h', text: 'Cómo se produce' },
      { t: 'p', text: 'Los rayos gamma emitidos por el arma viajan hacia abajo hasta que, a unos 20–40 km de altura, el aire se vuelve lo bastante denso como para absorberlos. Al chocar con las moléculas arrancan electrones a gran velocidad (el **efecto Compton**). El campo magnético de la Tierra obliga a esos electrones a girar, y una enorme cantidad de cargas girando a la vez forma una corriente que radia una onda electromagnética hacia el suelo. El físico estadounidense Conrad Longmire explicó el mecanismo en 1963. Como depende del campo magnético, la intensidad varía según la latitud y la orientación.' },
      { t: 'h', text: 'Las tres componentes' },
      { t: 'compare', head: ['Componente', 'Duración', 'Causa', 'Qué daña', 'Comparación natural'], rows: [
        ['E1', 'Nanosegundos', 'Electrones Compton desviados por el campo magnético', 'Microelectrónica, ordenadores, sistemas de control, comunicaciones; campos de decenas de kV/m', 'Ninguna: no hay nada natural tan rápido e intenso'],
        ['E2', 'Microsegundos a milisegundos', 'Rayos gamma dispersados y neutrones', 'Equipos ya debilitados por E1; las protecciones contra rayos suelen bastar', 'Similar a un rayo cercano'],
        ['E3', 'Segundos a minutos', 'La bola de fuego deforma el campo magnético terrestre', 'Corrientes en líneas eléctricas, cables submarinos y transformadores de alta tensión', 'Similar a una gran tormenta solar'],
      ] },
      { t: 'p', text: 'E1 es tan rápido que los pararrayos y fusibles normales no llegan a actuar: el daño se produce en el componente antes de que la protección reaccione. E3, en cambio, es lento pero actúa sobre líneas muy largas, en las que induce corrientes que pueden sobrecalentar y destruir grandes transformadores, equipos que se fabrican por encargo y tardan meses en reponerse. Por eso los estudios sobre el EMP se parecen mucho a los de las tormentas geomagnéticas como la de Quebec de 1989, que dejó sin luz a seis millones de personas.' },
      { t: 'h', text: 'Starfish Prime y las pruebas soviéticas' },
      { t: 'p', text: 'El 9 de julio de 1962, Estados Unidos detonó una carga de 1,4 megatones a unos 400 km sobre el atolón Johnston, en el Pacífico, dentro de la serie Fishbowl. La prueba, **Starfish Prime**, produjo una aurora artificial visible desde Hawái hasta Nueva Zelanda. En Honolulú, a unos 1400 km, se apagaron unas 300 farolas, saltaron alarmas antirrobo y falló un enlace de microondas. Los efectos fueron mayores de lo esperado y llevaron a estudiar el fenómeno a fondo.' },
      { t: 'p', text: 'La explosión inyectó además electrones de alta energía en el campo magnético terrestre y creó un **cinturón de radiación artificial** que duró años. En pocos meses dañó o inutilizó alrededor de un tercio de los satélites que había entonces en órbita baja, entre ellos el Telstar 1, el primer satélite de comunicaciones comercial, lanzado precisamente al día siguiente de la prueba. La Unión Soviética hizo ensayos parecidos sobre Kazajistán ese mismo año, dentro del llamado **Proyecto K**: en el de octubre de 1962 se dañó una línea telefónica de cientos de kilómetros y se produjo un incendio en una central eléctrica. Las pruebas en la alta atmósfera y en el espacio terminaron con el [[tratados|Tratado de Prohibición Parcial de Ensayos]] de 1963.' },
      { t: 'facts', rows: [
        ['Starfish Prime', '9 de julio de 1962, 1,4 Mt a unos 400 km de altura'],
        ['Alcance de los efectos observados', 'Hawái, a unos 1400 km'],
        ['Consecuencia más duradera', 'Cinturón de radiación artificial que dañó satélites'],
        ['Mecanismo explicado por', 'Conrad Longmire (1963)'],
        ['Fin de las pruebas espaciales', 'Tratado de Prohibición Parcial (1963)'],
      ] },
      { t: 'h', text: 'Qué se sabe y qué no' },
      { t: 'p', text: 'La electrónica actual es más sensible que la de 1962, pero también hay más blindaje en los sistemas militares y críticos. Las estimaciones sobre las consecuencias de un ataque EMP sobre una sociedad moderna varían mucho: desde apagones regionales recuperables en días hasta el colapso prolongado de la red eléctrica que describió en 2008 una comisión del Congreso estadounidense. Las pruebas con simuladores de EMP sobre coches, por ejemplo, han mostrado que la mayoría siguen funcionando o vuelven a arrancar. La incertidumbre es grande y el tema se presta a exageraciones; lo que sí está claro es que el EMP es uno de los pocos efectos nucleares que no mata directamente a nadie.' },
      { t: 'note', text: '**Cómo lo calcula Bum.** Cuando eliges una altura de detonación superior a 30 km, el simulador dibuja la zona afectada por el EMP como el círculo de terreno visible desde el punto de la explosión: su radio es la distancia al horizonte, que crece con la raíz cuadrada de la altura. No modela la intensidad del campo, que depende de la latitud, de la potencia y del diseño del arma, y no calcula daños concretos a equipos.' },
      { t: 'sim', preset: 'Starfish Prime (EE. UU., 1962)', label: 'Simular Starfish Prime a 400 km de altura' },
    ],
    related: ['explosiones-aereas-y-de-superficie', 'pruebas-nucleares', 'tratados', 'bola-de-fuego', 'carrera-armamentistica'],
  },

  // ───────────────────────────── EFECTOS EN LA SALUD ─────────────────────────────
  {
    id: 'efectos-en-la-salud',
    title: 'Efectos de la radiación en la salud',
    cat: 'efec',
    order: 9,
    summary: 'Una dosis alta de radiación destruye las células que se dividen deprisa y causa el síndrome agudo de radiación; dosis menores aumentan el riesgo de cáncer durante décadas. Casi todo lo que se sabe procede de los supervivientes de Hiroshima y Nagasaki.',
    tags: ['síndrome agudo de radiación', 'SAR', 'enfermedad por radiación', 'dosis letal', 'DL50', 'cáncer', 'leucemia', 'LSS', 'RERF', 'ABCC', 'hibakusha', 'efectos a largo plazo', 'tiroides', 'yodo'],
    blocks: [
      { t: 'p', text: 'La radiación ionizante deposita energía en el interior de las células y rompe moléculas, sobre todo el ADN. Una célula puede reparar daños pequeños, pero cuando son muchos muere o pierde la capacidad de dividirse. Los tejidos que más se renuevan (la médula ósea que fabrica la sangre, el revestimiento del intestino, la piel, las células que forman el pelo) son los primeros en fallar. Ése es el origen de los efectos **agudos**, que aparecen en horas o semanas y sólo con dosis altas. Además, una célula dañada que sobrevive con mutaciones puede, años después, originar un cáncer: son los efectos **tardíos** o estocásticos, cuya probabilidad aumenta con la dosis.' },
      { t: 'p', text: 'Las dosis se miden en gray (Gy) o en sievert (Sv); para la radiación gamma, 1 Gy equivale aproximadamente a 1 Sv, que son 100 rad o 100 rem. Véase [[unidades-de-radiacion|unidades de radiación]]. Como referencia, una persona en España recibe de fuentes naturales y médicas unos 3 milisievert al año, es decir, 0,003 Sv.' },
      { t: 'h', text: 'El síndrome agudo de radiación' },
      { t: 'compare', head: ['Dosis de cuerpo entero', 'Primeros síntomas', 'Evolución', 'Mortalidad aproximada'], rows: [
        ['< 0,25 Gy (< 25 rem)', 'Ninguno', 'Sin efectos agudos detectables', '0'],
        ['0,25–1 Gy', 'Ninguno o náuseas leves', 'Descenso temporal de glóbulos blancos', '0'],
        ['1–2 Gy', 'Náuseas y vómitos en una parte de los expuestos, a las pocas horas', 'Síntomas leves; recuperación en semanas', '< 5 %'],
        ['2–6 Gy', 'Vómitos en 1–2 horas, fatiga', 'Síndrome de la médula ósea: tras una o dos semanas de aparente mejoría, caída del pelo, infecciones y hemorragias', 'La mitad muere hacia los 3,5–4,5 Gy sin tratamiento; menos con cuidados intensivos'],
        ['6–10 Gy', 'Vómitos en menos de una hora, diarrea, fiebre', 'Médula ósea destruida y daño intestinal grave', '50–100 % incluso con tratamiento'],
        ['10–20 Gy', 'Vómitos inmediatos, diarrea intensa', 'Síndrome gastrointestinal: deshidratación e infección', '≈ 100 % en una o dos semanas'],
        ['> 20 Gy', 'Confusión, desorientación, colapso en minutos u horas', 'Síndrome neurovascular', '100 % en horas o pocos días'],
      ] },
      { t: 'p', text: 'Un rasgo cruel del síndrome es la **fase latente**: tras los primeros vómitos, el enfermo puede sentirse bien durante días o semanas mientras su médula ósea se agota. Así lo vivieron muchas víctimas de [[hiroshima|Hiroshima]] y [[nagasaki|Nagasaki]], que parecían ilesas y murieron un mes después. La dosis letal media sin tratamiento (DL50/60, la que mata a la mitad de los expuestos en 60 días) se sitúa en torno a 4 Gy; con transfusiones, antibióticos y factores de crecimiento puede acercarse a 6 Gy. Entre los bomberos y operarios de [[chernobil|Chernóbil]], 134 sufrieron el síndrome y 28 murieron en los meses siguientes.' },
      { t: 'h', text: 'Efectos a largo plazo: el estudio de los supervivientes' },
      { t: 'p', text: 'La fuente principal de conocimiento sobre los efectos tardíos es el **Estudio de Duración de la Vida** (*Life Span Study*, LSS), que sigue desde 1950 a unas 120 000 personas de Hiroshima y Nagasaki: unos 94 000 supervivientes cuya dosis se reconstruyó según su posición y su refugio en el momento de la explosión, y un grupo de comparación. Lo inició la Comisión de Víctimas de la Bomba Atómica (ABCC), creada por Estados Unidos en 1947, y desde 1975 lo lleva la Fundación para la Investigación de los Efectos de la Radiación (RERF), gestionada a medias por Japón y Estados Unidos. Es probablemente el estudio epidemiológico más importante de la historia de la radiología.' },
      { t: 'list', items: [
        '**Leucemia.** Fue el primer efecto detectado: aumentó a partir de los dos años, alcanzó su máximo a los seis u ocho y después fue disminuyendo. Cerca de la mitad de las leucemias en los supervivientes con dosis apreciables se atribuyen a la radiación.',
        '**Tumores sólidos.** Aumentaron más tarde y siguen apareciendo a lo largo de toda la vida, sobre todo en quienes estuvieron expuestos de niños. En el grupo estudiado, unas 450 de las aproximadamente 9300 muertes por cáncer sólido registradas hasta el año 2000 se atribuyen a la radiación: un exceso real pero mucho menor de lo que suele creerse.',
        '**Otras enfermedades.** Cataratas, enfermedades cardiovasculares y problemas de tiroides aumentan con la dosis.',
        '**Exposición en el útero.** Los niños expuestos durante las semanas 8 a 25 del embarazo mostraron más casos de microcefalia y discapacidad intelectual.',
        '**Hijos de los supervivientes.** Hasta ahora no se ha detectado un aumento significativo de enfermedades hereditarias en la segunda generación, un resultado que tranquilizó a muchas familias.',
      ] },
      { t: 'p', text: 'De estos datos procede la estimación que usan los organismos de protección radiológica: un riesgo adicional de muerte por cáncer de alrededor del 5 % por cada sievert recibido. Para dosis bajas se aplica el modelo **lineal sin umbral**, que supone que el riesgo es proporcional a la dosis por pequeña que sea; es una hipótesis prudente que sigue debatiéndose, porque a esas dosis el efecto es demasiado pequeño para medirse directamente. Más allá de las cifras, los [[hibakusha|hibakusha]] sufrieron durante décadas discriminación laboral y matrimonial por miedo a una supuesta enfermedad contagiosa o hereditaria.' },
      { t: 'h', text: 'Contaminación interna' },
      { t: 'p', text: 'La [[lluvia-radiactiva|lluvia radiactiva]] y los accidentes de reactores añaden otro riesgo: inhalar o ingerir isótopos radiactivos que se acumulan en órganos concretos. El yodo-131 se concentra en la tiroides, sobre todo de los niños que beben leche contaminada, y fue la causa del aumento de cánceres de tiroides tras Chernóbil. El estroncio-90 se fija en los huesos como el calcio y el cesio-137 se reparte por los músculos. Las pastillas de yoduro potásico sólo protegen frente al yodo radiactivo y sólo si se toman en el momento indicado por las autoridades; véase [[proteccion-civil|protección civil]].' },
      { t: 'note', text: '**Cómo lo calcula Bum.** El simulador expresa la radiación inicial en rem y dibuja anillos de 100, 500, 1000 y 5000 rem. Para estimar las víctimas combina tres probabilidades independientes en cada punto: muerte por la onda expansiva (ajustada a la regla de la OTA de 1979), por quemaduras (sólo para la población al aire libre) y por radiación, con una dosis letal media de 450 rem tras aplicar el blindaje medio de los edificios. No estima los cánceres futuros ni las muertes por lluvia radiactiva, que dependen de cómo se comporte la gente en los días siguientes.' },
    ],
    related: ['unidades-de-radiacion', 'radiacion-inicial', 'hibakusha', 'lluvia-radiactiva', 'chernobil', 'radiactividad'],
  },

  // ───────────────────────────── INVIERNO NUCLEAR ─────────────────────────────
  {
    id: 'invierno-nuclear',
    title: 'El invierno nuclear',
    cat: 'efec',
    order: 10,
    summary: 'Los incendios de las ciudades tras una guerra nuclear podrían inyectar tanto humo en la estratosfera que la Tierra se enfriaría durante años. Los modelos actuales indican que la hambruna resultante mataría a más personas que las propias bombas.',
    tags: ['invierno nuclear', 'TTAPS', 'Sagan', 'Turco', 'Robock', 'Toon', 'hollín', 'estratosfera', 'clima', 'hambruna', 'otoño nuclear', 'capa de ozono'],
    blocks: [
      { t: 'p', text: 'Durante las primeras décadas de la era nuclear, los estudios sobre una guerra total se centraron en la onda, el calor y la [[lluvia-radiactiva|lluvia radiactiva]]. A principios de los años ochenta, varios científicos se dieron cuenta de que faltaba una pieza: el **humo**. Las ciudades contienen enormes cantidades de madera, plásticos, asfalto y combustibles. Si cientos de ellas ardieran a la vez en [[radiacion-termica|tormentas de fuego]], las columnas de humo subirían hasta la estratosfera y allí, por encima de la lluvia que las lavaría, el hollín podría quedarse años.' },
      { t: 'h', text: 'El mecanismo' },
      { t: 'list', ordered: true, items: [
        'Los incendios urbanos producen **hollín negro**, muy eficaz absorbiendo la luz solar.',
        'Las tormentas de fuego generan columnas convectivas que llevan el humo a la alta troposfera; una vez allí, el propio humo, calentado por el Sol, sigue subiendo hasta la estratosfera.',
        'En la estratosfera no llueve, así que el hollín puede permanecer varios años y extenderse por todo el hemisferio y después por el planeta.',
        'El humo absorbe la luz solar en altura: la estratosfera se calienta y la superficie se oscurece y se enfría. Las lluvias disminuyen porque se evapora menos agua de los océanos.',
        'El calentamiento de la estratosfera destruye además buena parte de la **capa de ozono**, lo que aumenta la radiación ultravioleta cuando el humo empieza a disiparse.',
      ] },
      { t: 'h', text: 'De Crutzen al estudio TTAPS' },
      { t: 'p', text: 'En 1982, Paul Crutzen (futuro premio Nobel de Química por sus trabajos sobre el ozono) y John Birks publicaron en la revista *Ambio* que el humo de los incendios de una guerra nuclear oscurecería el cielo durante semanas. Al año siguiente, en diciembre de 1983, la revista *Science* publicó el estudio que dio nombre al fenómeno: «TTAPS», por las iniciales de sus autores, Richard **Turco**, Owen **Toon**, Thomas Ackerman, James Pollack y Carl **Sagan**. Con un modelo climático sencillo, concluía que una guerra a gran escala podría hacer caer las temperaturas en el interior de los continentes del hemisferio norte entre 10 y 20 °C durante meses, incluso en verano. Científicos soviéticos como Vladímir Alexándrov y Gueorgui Stenchikov llegaron a resultados parecidos con modelos propios.' },
      { t: 'p', text: 'Sagan divulgó la idea con enorme intensidad, y eso generó también críticas. En 1986, Starley Thompson y Stephen Schneider, con modelos más completos, propusieron que el efecto sería menor, un «otoño nuclear». En 1991, Sagan predijo que los incendios de los pozos de petróleo de Kuwait tendrían un efecto climático apreciable y se equivocó: el humo no subió lo bastante. Durante unos años, la teoría quedó en entredicho para el gran público, aunque los propios críticos aceptaban que habría un enfriamiento significativo.' },
      { t: 'h', text: 'Los modelos modernos: Robock y Toon' },
      { t: 'p', text: 'A partir de 2007, Alan **Robock**, Owen **Toon** y sus colaboradores retomaron el problema con los modelos climáticos actuales, los mismos que se usan para estudiar el calentamiento global, y con lo aprendido de las grandes erupciones volcánicas. Sus conclusiones fueron que el humo duraría más de lo que se pensaba en los ochenta (años, no meses) y que incluso una guerra «pequeña» tendría efectos globales.' },
      { t: 'compare', head: ['Escenario', 'Humo en la estratosfera', 'Enfriamiento medio global', 'Consecuencias estimadas'], rows: [
        ['Guerra regional (p. ej. India–Pakistán, unas 100 armas de 15 kt)', '≈ 5 Tg', '≈ 1–1,5 °C durante varios años', 'Pérdida de cosechas; cientos de millones o más de 2000 millones de personas en riesgo de hambre según los estudios'],
        ['Guerra regional grande (India–Pakistán, 250 armas)', '16–36 Tg', '≈ 2–5 °C', 'Caída de la producción de alimentos del 15–30 %'],
        ['Guerra entre EE. UU. y Rusia', '≈ 150 Tg', '≈ 8 °C; más de 15 °C en zonas continentales', 'Hambruna mundial; más de 5000 millones de muertos en el estudio de Xia y colaboradores (2022)'],
      ] },
      { t: 'p', text: 'Un teragramo (Tg) son un millón de toneladas. Las cifras del estudio de 2022, publicado en *Nature Food*, se refieren a muertes por hambre en los dos años siguientes, sin contar las víctimas directas. Hay estudios discrepantes, como uno del Laboratorio de Los Álamos de 2018 que estimaba mucho menos humo en la estratosfera porque los incendios urbanos serían menos intensos; la cantidad de material combustible de las ciudades modernas y la altura a la que subiría el humo son las principales incertidumbres. Aun así, el consenso es que una guerra nuclear de gran escala tendría consecuencias climáticas globales graves.' },
      { t: 'h', text: 'Influencia política' },
      { t: 'p', text: 'El invierno nuclear cambió el debate de la [[carrera-armamentistica|carrera armamentística]]: si una guerra destruiría también al país que atacara primero, aunque no recibiera ni una bomba, la idea de una guerra nuclear «ganable» perdía sentido. Mijaíl Gorbachov declaró años después que los informes sobre el invierno nuclear habían influido en su decisión de reducir los arsenales. En la cumbre de Ginebra de noviembre de 1985, él y Ronald Reagan firmaron una declaración que se ha repetido muchas veces desde entonces.' },
      { t: 'quote', text: 'Una guerra nuclear no se puede ganar y nunca debe librarse.', by: 'Declaración conjunta de Reagan y Gorbachov, Ginebra, 1985' },
      { t: 'p', text: 'En enero de 2022, las cinco potencias nucleares reconocidas por el Tratado de No Proliferación reafirmaron esa frase en un comunicado conjunto. Los estudios climáticos explican el porqué mejor que cualquier eslogan; véanse también [[destruccion-mutua-asegurada|destrucción mutua asegurada]] y [[arsenales-actuales|arsenales actuales]].' },
      { t: 'note', text: '**Bum y el clima.** El simulador muestra los efectos de una sola explosión y no calcula efectos climáticos de las armas nucleares, porque dependen de cuántas ciudades ardan a la vez y de cuánto humo llegue a la estratosfera. Sí avisa de las consecuencias climáticas globales en los grandes impactos de asteroides, cuyo «invierno de impacto» es un fenómeno parecido; véase [[chicxulub|Chicxulub]].' },
    ],
    related: ['radiacion-termica', 'destruccion-mutua-asegurada', 'arsenales-actuales', 'chicxulub', 'carrera-armamentistica'],
  },

  // ───────────────────────────── PROTECCIÓN CIVIL ─────────────────────────────
  {
    id: 'proteccion-civil',
    title: 'Qué hacer ante una alerta nuclear',
    cat: 'efec',
    order: 11,
    summary: 'Las recomendaciones de protección civil se resumen en tres verbos: entrar, quedarse e informarse. Fuera de la zona de destrucción, refugiarse bien durante las primeras horas puede salvar la vida.',
    tags: ['protección civil', 'refugio', 'alerta', 'ES-Alert', '112', 'entrar quedarse informarse', 'yoduro potásico', 'descontaminación', 'Duck and Cover', 'lluvia radiactiva', 'emergencia nuclear'],
    blocks: [
      { t: 'p', text: 'Ante un arma nuclear no hay protección posible en las inmediaciones de la zona cero. Pero la mayor parte de la población afectada por una explosión no estaría ahí, sino en las zonas de daño leve y, sobre todo, bajo la [[lluvia-radiactiva|lluvia radiactiva]]. Para esas personas, lo que hagan en la primera hora y en los dos primeros días marca una diferencia enorme. Las agencias de protección civil de Europa y Norteamérica coinciden en una consigna de tres palabras: **entrar, quedarse e informarse**.' },
      { t: 'h', text: 'Si se recibe un aviso antes de la explosión' },
      { t: 'list', items: [
        'Entrar de inmediato en el edificio sólido más cercano y bajar al sótano o ir al centro del edificio, lejos de ventanas, puertas exteriores y tejados.',
        'Si no hay ningún edificio cerca, tumbarse en el suelo boca abajo, protegiendo la cabeza y la piel expuesta, detrás de cualquier cosa que dé sombra o cobijo (un muro, una zanja).',
        'No mirar hacia el destello: incluso a decenas de kilómetros puede causar [[radiacion-termica|ceguera temporal o lesiones en la retina]].',
      ] },
      { t: 'h', text: 'Si se ve el destello sin aviso' },
      { t: 'p', text: 'La luz llega antes que la [[onda-expansiva|onda expansiva]]: a varios kilómetros, el frente de choque tarda entre unos segundos y casi un minuto. Ese tiempo basta para tirarse al suelo, alejarse de las ventanas o agacharse detrás de un mueble. En las ciudades, la mayoría de los heridos fuera de la zona de derrumbes lo serían por cristales rotos. La famosa campaña estadounidense de los años cincuenta *Duck and Cover* («agáchate y cúbrete»), protagonizada por la tortuga Bert, se ha ridiculizado mucho, pero su consejo básico sigue siendo válido fuera de la zona de destrucción. Después de que pase la onda, puede llegar un segundo golpe de viento en sentido contrario.' },
      { t: 'h', text: 'Entrar' },
      { t: 'p', text: 'Si la explosión fue en superficie, la lluvia radiactiva empieza a caer cerca de la zona cero en unos 15–30 minutos y a decenas de kilómetros en una o varias horas. Hay que ponerse bajo techo cuanto antes en el lugar que ofrezca más **factor de protección**: sótanos, aparcamientos subterráneos o el centro de las plantas intermedias de un edificio grande de hormigón o ladrillo. Un coche no protege casi nada. Es preferible un refugio bueno a diez minutos que uno malo a uno, pero no salir a buscarlo si la lluvia radiactiva ya está cayendo.' },
      { t: 'p', text: 'Quien haya estado fuera debe quitarse la ropa exterior (eso elimina buena parte de la contaminación), guardarla en una bolsa cerrada lejos de las personas, y ducharse con agua y jabón o, si no es posible, lavarse con un paño húmedo. No conviene usar acondicionador en el pelo porque fija las partículas. Las mascotas que hayan estado fuera también deben lavarse.' },
      { t: 'h', text: 'Quedarse' },
      { t: 'p', text: 'Por la regla del 7-10, la radiación de la lluvia radiactiva cae a la décima parte a las 7 horas y a la centésima a los dos días. Quedarse dentro **al menos 24 horas**, y tanto como indiquen las autoridades, evita la mayor parte de la dosis. Salir antes de tiempo para buscar a familiares que están en otro lugar es una de las decisiones más peligrosas: es mejor que cada uno se quede donde está. Conviene tener en casa agua embotellada, alimentos no perecederos, una radio a pilas, una linterna, medicamentos habituales y un botiquín.' },
      { t: 'h', text: 'Informarse' },
      { t: 'p', text: 'Las autoridades indicarán cuándo es seguro salir, hacia dónde evacuar y qué hacer con el agua y los alimentos. Las redes móviles e internet pueden saturarse o fallar; una radio a pilas es la fuente más fiable. En España, el sistema **ES-Alert** del 112, en funcionamiento desde 2023, envía avisos a todos los teléfonos móviles de una zona aunque estén saturadas las redes de voz y datos, y la Dirección General de Protección Civil y Emergencias coordina la respuesta junto con las comunidades autónomas.' },
      { t: 'h', text: 'Las pastillas de yodo' },
      { t: 'p', text: 'El yoduro potásico satura la tiroides de yodo estable y evita que absorba el yodo-131 radiactivo. Es muy útil tras un accidente en un reactor, como [[chernobil|Chernóbil]], para niños, jóvenes y embarazadas; en España se distribuye en el entorno de las centrales nucleares dentro de los planes de emergencia nuclear. Pero **no protege de ninguna otra radiación**, ni de la radiación externa ni de otros isótopos, y tomarlo sin indicación tiene riesgos, sobre todo para personas con problemas de tiroides. Sólo debe tomarse cuando lo ordenen las autoridades sanitarias.' },
      { t: 'h', text: 'Refugios y planificación' },
      { t: 'p', text: 'Pocos países mantienen hoy refugios para toda la población. Suiza es la excepción más conocida: desde los años sesenta la ley exige que haya plaza en un refugio para cada habitante, y Finlandia tiene una amplia red en sus ciudades. En la Guerra Fría, Estados Unidos señalizó miles de edificios como refugios contra la lluvia radiactiva con un factor de protección mínimo de 40. La planificación española de emergencias radiológicas se basa en la Directriz Básica de Planificación de Protección Civil ante el Riesgo Radiológico (2019) y en el Plan Básico de Emergencia Nuclear, pensados sobre todo para accidentes en instalaciones nucleares.' },
      { t: 'note', text: 'Estas recomendaciones resumen las guías públicas de organismos de protección civil y no sustituyen a las instrucciones oficiales: ante una emergencia real, sigue siempre las indicaciones del 112 y de las autoridades. El simulador Bum es una herramienta divulgativa y sus resultados son aproximados.' },
    ],
    related: ['lluvia-radiactiva', 'onda-expansiva', 'radiacion-termica', 'efectos-en-la-salud', 'chernobil', 'fukushima'],
  },
];
