import type { Article } from '../types';

/**
 * Categoría «Fundamentos»: la física necesaria para entender el resto de la enciclopedia,
 * desde qué es un átomo hasta las unidades con que se mide la radiación.
 * Nivel divulgativo: sin cantidades de material, masas críticas ni parámetros de diseño.
 */
export const ARTICLES: Article[] = [
  // ───────────────────────────────────────────────────────────── átomo
  {
    id: 'atomo',
    title: 'El átomo',
    cat: 'fund',
    order: 1,
    summary: 'Toda la materia está hecha de átomos: un núcleo diminuto de protones y neutrones rodeado de electrones. La energía nuclear procede de las fuerzas que mantienen unido ese núcleo.',
    tags: ['átomo', 'núcleo', 'protón', 'neutrón', 'electrón', 'fuerza nuclear fuerte', 'energía de enlace', 'E=mc²', 'Rutherford', 'Bohr', 'Chadwick', 'defecto de masa'],
    blocks: [
      { t: 'p', text: 'Todo lo que nos rodea, desde el aire hasta el acero, está formado por **átomos**. Un átomo es la porción más pequeña de un elemento químico que conserva sus propiedades: un átomo de hierro sigue siendo hierro, pero si lo partimos dejamos de tener hierro. La palabra procede del griego *átomos*, «indivisible», porque los filósofos Leucipo y Demócrito imaginaron en el siglo V a. C. que la materia debía estar hecha de piezas que ya no podían dividirse. Hoy sabemos que el átomo sí tiene partes, y que en la forma de unirlas se esconde la energía de las armas nucleares, de los reactores y del propio Sol.' },
      { t: 'diagram', id: 'atom', caption: 'Esquema de un átomo: núcleo con protones (carga positiva) y neutrones (sin carga), y electrones alrededor. Las proporciones reales son imposibles de dibujar: el núcleo sería invisible a esta escala.' },
      { t: 'h', text: 'Las tres piezas' },
      { t: 'list', items: [
        '**Protones**: partículas con carga eléctrica positiva que viven en el núcleo. Su número, llamado *número atómico* (Z), define el elemento: todo átomo con 1 protón es hidrógeno, con 6 es carbono, con 92 es [[uranio|uranio]] y con 94 es [[plutonio|plutonio]].',
        '**Neutrones**: partículas casi de la misma masa que el protón pero sin carga eléctrica. También están en el núcleo. Al no tener carga, un neutrón libre puede acercarse a otro núcleo sin ser repelido, y por eso es la «bala» que desencadena la [[fision|fisión]].',
        '**Electrones**: partículas unas 1836 veces más ligeras que un protón, con carga negativa, que ocupan la región que rodea al núcleo. Son los responsables de toda la química: los enlaces, las reacciones y, por tanto, la energía de los [[explosivos-convencionales|explosivos convencionales]].',
      ] },
      { t: 'p', text: 'La suma de protones y neutrones es el *número másico* (A). Así, el uranio-235 tiene 92 protones y 143 neutrones, que suman 235. Átomos del mismo elemento con distinto número de neutrones son [[isotopos|isótopos]].' },
      { t: 'h', text: 'Un núcleo increíblemente pequeño' },
      { t: 'p', text: 'Un átomo mide del orden de una diezmilmillonésima de metro (0,1 nanómetros). Su núcleo es entre diez mil y cien mil veces más pequeño. Si el átomo fuera un estadio de fútbol, el núcleo sería un garbanzo en el centro del campo y los electrones, motas de polvo moviéndose por las gradas. Y sin embargo ese garbanzo concentra más del 99,9 % de la masa. La materia corriente es, en realidad, casi toda espacio vacío.' },
      { t: 'h', text: 'La fuerza nuclear fuerte' },
      { t: 'p', text: 'El núcleo plantea un enigma: los protones tienen todos carga positiva y, a distancias tan cortas, se repelen con una fuerza enorme. ¿Por qué no sale disparado? Porque existe otra interacción, la **fuerza nuclear fuerte**, que atrae entre sí a protones y neutrones con una intensidad muy superior a la repulsión eléctrica, pero sólo a distancias del tamaño de un núcleo. Más allá, se desvanece casi por completo. El físico japonés Hideki Yukawa propuso en 1935 la primera teoría de esta fuerza, lo que le valió el Nobel en 1949.' },
      { t: 'p', text: 'Esta competencia entre dos fuerzas explica casi todo lo que sigue. En los núcleos ligeros la fuerza fuerte domina con holgura. En los muy pesados, como el uranio, hay tantos protones que la repulsión eléctrica, que actúa a mayor distancia, empieza a ganar terreno: el núcleo es como una gota de agua demasiado grande, tembloroso y a punto de partirse. Por eso los elementos más pesados son [[radiactividad|radiactivos]] y algunos pueden fisionarse.' },
      { t: 'h', text: 'Energía de enlace y E = mc²' },
      { t: 'p', text: 'Si pesamos con precisión un núcleo de helio y lo comparamos con la suma de los dos protones y dos neutrones que lo forman, descubrimos algo sorprendente: el núcleo pesa *menos* que sus piezas por separado. A esa diferencia se le llama **defecto de masa**. La masa que «falta» se liberó como energía cuando las piezas se unieron, y es la misma energía que habría que aportar para separarlas: la **energía de enlace**.' },
      { t: 'p', text: 'La relación entre masa y energía la estableció Albert Einstein en 1905 con su célebre ecuación **E = mc²**: la energía equivale a la masa multiplicada por la velocidad de la luz al cuadrado. Como esa velocidad es enorme, una masa minúscula equivale a una energía colosal. Un solo gramo de materia convertido íntegramente en energía equivaldría a unos 21 [[energia-y-tnt|kilotones]], más que la bomba de Hiroshima, en la que en realidad se transformó en energía menos de un gramo de masa. Conviene matizar un error frecuente: Einstein no inventó la bomba ni participó en su diseño; su ecuación sólo explica de dónde sale la energía.' },
      { t: 'p', text: 'Si se representa la energía de enlace por partícula de cada núcleo, se obtiene una curva que sube muy deprisa en los elementos ligeros, alcanza un máximo en torno al hierro y el níquel y luego desciende lentamente hacia los pesados. Esa curva es el mapa de la energía nuclear: cualquier reacción que lleve los núcleos hacia el máximo libera energía. Hay dos caminos: **partir** un núcleo pesado en dos medianos ([[fision|fisión]]) o **unir** núcleos ligeros en uno más pesado ([[fusion|fusión]]).' },
      { t: 'compare', head: ['Núcleo', 'Energía de enlace por partícula (aprox.)', 'Qué implica'], rows: [
        ['Deuterio (hidrógeno-2)', '1,1 MeV', 'Muy poco ligado: fusionarlo libera mucha energía'],
        ['Helio-4', '7,1 MeV', 'Extraordinariamente estable; producto típico de la fusión'],
        ['Hierro-56', '8,8 MeV', 'Cerca del máximo: ni fisión ni fusión le sacan energía'],
        ['Uranio-235', '7,6 MeV', 'Al partirse en dos núcleos medianos libera energía'],
      ] },
      { t: 'note', text: 'El MeV (megaelectronvoltio) es una unidad de energía muy pequeña a escala humana, pero enorme a escala de una molécula: una reacción química típica libera unos pocos electronvoltios, un millón de veces menos que una reacción nuclear. Esa diferencia de un millón es la clave de todo: véase [[energia-y-tnt|Energía y equivalencia en TNT]].' },
      { t: 'h', text: 'Cómo se descubrió' },
      { t: 'timeline', items: [
        { date: 'h. 400 a. C.', text: 'Leucipo y Demócrito proponen que la materia está hecha de partículas indivisibles.' },
        { date: '1803–1808', text: 'John Dalton formula la teoría atómica moderna: cada elemento tiene átomos de una masa característica.' },
        { date: '1897', text: 'J. J. Thomson descubre el electrón al estudiar los rayos catódicos. Imagina el átomo como un «pudin» positivo con electrones incrustados.' },
        { date: '1909–1911', text: 'Hans Geiger y Ernest Marsden disparan partículas alfa contra una lámina de oro; algunas rebotan. Ernest Rutherford concluye que la carga positiva se concentra en un núcleo diminuto.' },
        { date: '1913', text: 'Niels Bohr propone que los electrones ocupan órbitas de energía fija, lo que explica la luz que emiten los átomos.' },
        { date: '1917–1920', text: 'Rutherford identifica el protón como componente de todos los núcleos.' },
        { date: '1932', text: 'James Chadwick descubre el neutrón en Cambridge. Ese mismo año Werner Heisenberg y Dmitri Ivanenko describen el núcleo como un conjunto de protones y neutrones.' },
        { date: '1935', text: 'Hideki Yukawa propone la primera teoría de la fuerza nuclear fuerte.' },
      ] },
      { t: 'p', text: 'El descubrimiento del neutrón en 1932 fue el punto de partida de la era nuclear. Por primera vez se disponía de un proyectil capaz de penetrar en cualquier núcleo, y Enrico Fermi empezó enseguida a bombardear con neutrones todos los elementos que encontraba. Siete años después, ese camino desembocaría en el [[descubrimiento-de-la-fision|descubrimiento de la fisión]].' },
    ],
    related: ['isotopos', 'radiactividad', 'fision', 'fusion', 'energia-y-tnt'],
  },

  // ───────────────────────────────────────────────────────────── isótopos
  {
    id: 'isotopos',
    title: 'Isótopos',
    cat: 'fund',
    order: 2,
    summary: 'Los isótopos son variantes de un mismo elemento que tienen el mismo número de protones pero distinto número de neutrones. Químicamente son casi idénticos, pero su comportamiento nuclear puede ser radicalmente distinto.',
    tags: ['isótopo', 'número másico', 'deuterio', 'tritio', 'uranio-235', 'uranio-238', 'plutonio-239', 'Soddy', 'estabilidad nuclear', 'carbono-14'],
    blocks: [
      { t: 'p', text: 'Todos los átomos de un elemento tienen el mismo número de protones, pero no necesariamente el mismo número de neutrones. Cada variante se llama **isótopo**. El nombre lo acuñó el químico británico Frederick Soddy en 1913, a sugerencia de la médica y escritora Margaret Todd: viene del griego *isos topos*, «mismo lugar», porque todos los isótopos de un elemento ocupan la misma casilla de la tabla periódica.' },
      { t: 'diagram', id: 'isotopes', caption: 'Uranio-235, uranio-238 y plutonio-239: los dos primeros tienen 92 protones; difieren sólo en tres neutrones, pero esa diferencia decide si un núcleo se fisiona con facilidad o no.' },
      { t: 'h', text: 'Cómo se nombran' },
      { t: 'p', text: 'Un isótopo se identifica con el nombre del elemento y su número másico (protones más neutrones): carbono-12, uranio-235, plutonio-239. En notación científica se escribe el número arriba a la izquierda del símbolo químico (¹²C, ²³⁵U). En esta enciclopedia usamos la forma con guion, más legible: U-235, Pu-239.' },
      { t: 'h', text: 'Química igual, física distinta' },
      { t: 'p', text: 'La química de un átomo depende de sus electrones, y el número de electrones depende del número de protones. Por eso dos isótopos del mismo elemento reaccionan prácticamente igual: el agua hecha con hidrógeno pesado se parece mucho al agua corriente y el uranio-235 forma los mismos compuestos que el uranio-238. Esta semejanza tiene una consecuencia histórica enorme: no hay ninguna reacción química que separe con facilidad dos isótopos. Para lograrlo hay que aprovechar la diminuta diferencia de masa entre ellos, lo que exige instalaciones industriales gigantescas. Ese es el problema del *enriquecimiento* que se describe en [[uranio|Uranio]].' },
      { t: 'p', text: 'El núcleo, en cambio, sí distingue entre isótopos. Unos son estables para siempre; otros son [[radiactividad|radiactivos]] y se transforman con el tiempo. Algunos absorben neutrones con avidez y otros apenas los notan. Y, sobre todo, unos pocos isótopos pesados son **fisibles**: se parten al recibir un neutrón de cualquier energía, incluso uno muy lento. Los tres fisibles de interés práctico son el uranio-233, el uranio-235 y el plutonio-239.' },
      { t: 'h', text: 'Isótopos que aparecen en esta enciclopedia' },
      { t: 'compare', head: ['Isótopo', 'Protones / neutrones', 'Por qué importa'], rows: [
        ['Hidrógeno-1 (protio)', '1 / 0', 'El hidrógeno corriente; combustible de las estrellas'],
        ['Hidrógeno-2 (deuterio)', '1 / 1', 'Estable; se encuentra en el agua. Combustible de [[fusion|fusión]]'],
        ['Hidrógeno-3 (tritio)', '1 / 2', 'Radiactivo (semivida de unos 12,3 años); combustible de fusión'],
        ['Litio-6 y litio-7', '3 / 3 y 3 / 4', 'Materia prima del tritio; el litio-7 causó la sorpresa de [[castle-bravo|Castle Bravo]]'],
        ['Carbono-14', '6 / 8', 'Radiactivo; permite datar restos orgánicos'],
        ['Cesio-137 y estroncio-90', '55 / 82 y 38 / 52', 'Productos de fisión de larga vida en la [[lluvia-radiactiva|lluvia radiactiva]]'],
        ['Yodo-131', '53 / 78', 'Producto de fisión de vida corta que se acumula en el tiroides'],
        ['Uranio-235', '92 / 143', 'Fisible; menos del 1 % del uranio natural'],
        ['Uranio-238', '92 / 146', 'El 99,3 % del uranio natural; sólo se fisiona con neutrones rápidos'],
        ['Plutonio-239', '94 / 145', 'Fisible; se fabrica en reactores a partir del uranio-238'],
        ['Plutonio-240', '94 / 146', 'Sufre fisión espontánea; condicionó el diseño de las primeras bombas'],
      ] },
      { t: 'h', text: 'El valle de la estabilidad' },
      { t: 'p', text: 'Si se dibujan todos los núcleos conocidos en un gráfico con los protones en un eje y los neutrones en otro, los estables forman una franja estrecha llamada *valle de la estabilidad*. En los elementos ligeros, la proporción ideal es de un neutrón por protón; en los pesados, hacen falta bastantes más neutrones que protones para «diluir» la repulsión eléctrica. Los núcleos que se salen de la franja son inestables y tienden a volver a ella emitiendo radiación: si les sobran neutrones, suelen sufrir desintegración beta; si son muy pesados, desintegración alfa.' },
      { t: 'p', text: 'Esta regla explica por qué los [[fision|productos de fisión]] son tan radiactivos. Cuando un núcleo de uranio se parte, los dos fragmentos heredan su elevada proporción de neutrones, que es excesiva para núcleos medianos. Quedan muy lejos del valle y se desintegran en cadenas sucesivas durante segundos, días o décadas. De ahí procede la radiactividad de la [[lluvia-radiactiva|lluvia radiactiva]] y de los residuos de los reactores.' },
      { t: 'h', text: 'Un poco de historia' },
      { t: 'timeline', items: [
        { date: '1913', text: 'J. J. Thomson observa que el neón tiene dos variantes de distinta masa. Soddy acuña la palabra «isótopo».' },
        { date: '1919', text: 'Francis Aston construye el espectrógrafo de masas y encuentra isótopos en decenas de elementos (Nobel de Química en 1922).' },
        { date: '1931', text: 'Harold Urey descubre el deuterio, el hidrógeno pesado (Nobel de Química en 1934).' },
        { date: '1934', text: 'Mark Oliphant, Paul Harteck y Ernest Rutherford obtienen tritio en el laboratorio al fusionar núcleos de deuterio.' },
        { date: '1935', text: 'Arthur Dempster identifica el uranio-235 en el uranio natural.' },
        { date: '1939', text: 'Niels Bohr y John Wheeler deducen que es el raro uranio-235, y no el abundante uranio-238, el responsable de la fisión con neutrones lentos.' },
        { date: '1941', text: 'Glenn Seaborg y su equipo demuestran que el plutonio-239 es fisible.' },
      ] },
    ],
    related: ['atomo', 'radiactividad', 'uranio', 'plutonio', 'combustibles-de-fusion'],
  },

  // ───────────────────────────────────────────────────────────── radiactividad
  {
    id: 'radiactividad',
    title: 'Radiactividad',
    cat: 'fund',
    order: 3,
    summary: 'La radiactividad es la transformación espontánea de núcleos inestables, que emiten radiación alfa, beta, gamma o neutrones. Cada isótopo lo hace a su propio ritmo, medido por su semivida.',
    tags: ['radiactividad', 'radiación alfa', 'radiación beta', 'radiación gamma', 'neutrones', 'semivida', 'Becquerel', 'Marie Curie', 'blindaje', 'cadena de desintegración'],
    blocks: [
      { t: 'p', text: 'Un núcleo inestable no permanece así para siempre. Tarde o temprano se transforma en otro más estable y, al hacerlo, expulsa partículas o energía. Ese proceso espontáneo es la **radiactividad**, y lo que sale despedido es la **radiación ionizante**: radiación con energía suficiente para arrancar electrones de los átomos que atraviesa, romper moléculas y dañar el ADN de las células. No hay que confundirla con la radiación no ionizante, como la luz visible, las ondas de radio o las microondas, que no tiene esa capacidad.' },
      { t: 'h', text: 'El descubrimiento' },
      { t: 'p', text: 'En 1896 el físico francés Henri Becquerel guardó unas sales de uranio junto a placas fotográficas envueltas en papel negro y descubrió que las placas se velaban sin necesidad de luz. El uranio emitía algo por sí mismo. Poco después, Marie Skłodowska-Curie, que bautizó el fenómeno como *radiactividad*, y su marido Pierre Curie descubrieron en 1898 dos elementos mucho más activos que el uranio: el polonio y el radio. Los tres compartieron el Nobel de Física en 1903; Marie Curie ganaría además el de Química en 1911, y moriría en 1934 de una anemia atribuida a décadas de exposición.' },
      { t: 'p', text: 'Ernest Rutherford distinguió en 1899 dos tipos de radiación según su poder de penetración, a los que llamó alfa y beta; en 1900 Paul Villard encontró un tercero, aún más penetrante, que recibió el nombre de gamma. En 1902 Rutherford y Soddy demostraron algo que parecía alquimia: al desintegrarse, un elemento se convierte en otro distinto.' },
      { t: 'diagram', id: 'decay', caption: 'Desintegración alfa (sale un núcleo de helio), beta (un neutrón se convierte en protón y sale un electrón) y gamma (el núcleo libera energía en forma de luz muy energética). Abajo, la semivida: cada intervalo igual queda la mitad.' },
      { t: 'h', text: 'Los tipos de radiación' },
      { t: 'list', items: [
        '**Alfa (α)**: el núcleo expulsa un paquete de dos protones y dos neutrones, es decir, un núcleo de helio. Es una partícula pesada y con carga que choca enseguida con todo lo que encuentra: recorre unos pocos centímetros en el aire y la detiene una hoja de papel o la capa muerta de la piel. Fuera del cuerpo es casi inofensiva; dentro, si se inhala o se ingiere, deposita toda su energía en muy poco espacio y es muy dañina. Es la radiación típica del uranio, el plutonio, el radio o el polonio.',
        '**Beta (β)**: un neutrón del núcleo se transforma en protón y emite un electrón muy rápido (y un antineutrino). Penetra más que la alfa: recorre metros en el aire y unos milímetros en el cuerpo. La frena una lámina de plástico o de aluminio de pocos milímetros. Puede causar quemaduras en la piel, como las «quemaduras beta» de los habitantes de Rongelap tras [[castle-bravo|Castle Bravo]].',
        '**Gamma (γ)**: después de una desintegración, el núcleo suele quedar excitado y se libera del sobrante de energía emitiendo un fotón, luz de energía altísima. No tiene masa ni carga, así que es muy penetrante: atraviesa el cuerpo y para atenuarla hacen falta espesores considerables de materiales densos, como plomo, hormigón, acero o tierra. Nunca se detiene del todo: cada cierto espesor se reduce a la mitad.',
        '**Neutrones (n)**: no proceden de la radiactividad corriente sino, sobre todo, de la [[fision|fisión]] y la [[fusion|fusión]]. Al no tener carga, atraviesan con facilidad el plomo y el acero. Se frenan mejor con materiales ricos en hidrógeno, como el agua, el polietileno o el hormigón húmedo, porque al chocar con núcleos ligeros pierden mucha energía en cada choque, igual que una bola de billar contra otra de su mismo tamaño. Además pueden volver radiactivos los materiales que los absorben (*activación*).',
      ] },
      { t: 'compare', head: ['Radiación', 'Qué es', 'Alcance en aire', 'Qué la frena', 'Peligro principal'], rows: [
        ['Alfa', 'Núcleo de helio', 'Unos centímetros', 'Papel, piel', 'Interno (inhalada o ingerida)'],
        ['Beta', 'Electrón rápido', 'Unos metros', 'Plástico, aluminio fino', 'Piel y ojos; también interno'],
        ['Gamma', 'Fotón de alta energía', 'Cientos de metros', 'Plomo, hormigón, tierra (atenúan)', 'Externo: atraviesa el cuerpo'],
        ['Neutrones', 'Partícula sin carga', 'Cientos de metros a kilómetros', 'Agua, hormigón, polietileno', 'Externo; activa los materiales'],
      ] },
      { t: 'h', text: 'La semivida' },
      { t: 'p', text: 'Es imposible saber cuándo se desintegrará un núcleo concreto, pero con muchísimos núcleos el comportamiento es perfectamente predecible. Cada isótopo tiene una **semivida** (o periodo de semidesintegración): el tiempo que tarda en desintegrarse la mitad de una muestra. Pasada una semivida queda la mitad; pasadas dos, la cuarta parte; pasadas diez, aproximadamente una milésima. La semivida no depende de la temperatura, la presión ni la combinación química: es una propiedad del núcleo.' },
      { t: 'p', text: 'Hay una relación inversa que conviene entender: cuanto más corta es la semivida, más intensa es la radiación de una cantidad dada de material, pero menos dura. Un isótopo de semivida muy larga, como el uranio-238, es poco activo; uno de semivida corta, como el yodo-131, es muy activo pero desaparece en semanas. Por eso la [[lluvia-radiactiva|lluvia radiactiva]] es intensísima en las primeras horas y decae deprisa, mientras que la contaminación de larga duración la dejan isótopos como el cesio-137.' },
      { t: 'compare', head: ['Isótopo', 'Semivida', 'Dónde aparece'], rows: [
        ['Uranio-239', '23 minutos', 'Paso intermedio en la producción de [[plutonio|plutonio]]'],
        ['Radón-222', '3,8 días', 'Gas natural del subsuelo; principal fuente de dosis natural'],
        ['Yodo-131', '8 días', 'Producto de fisión; afecta al tiroides'],
        ['Cobalto-60', '5,3 años', 'Fuentes médicas e industriales'],
        ['Tritio', '12,3 años', '[[combustibles-de-fusion|Combustible de fusión]]; pinturas luminosas'],
        ['Estroncio-90', '29 años', 'Producto de fisión; se fija en los huesos'],
        ['Cesio-137', '30 años', 'Producto de fisión; contamina suelos durante siglos'],
        ['Carbono-14', '5730 años', 'Datación por radiocarbono'],
        ['Plutonio-239', '24 100 años', 'Material fisible'],
        ['Uranio-235', '704 millones de años', 'Material fisible natural'],
        ['Uranio-238', '4470 millones de años', 'Casi la edad de la Tierra'],
      ] },
      { t: 'h', text: 'Cadenas de desintegración' },
      { t: 'p', text: 'A menudo el núcleo que resulta de una desintegración también es inestable y vuelve a desintegrarse, y así sucesivamente. El uranio-238, por ejemplo, recorre una cadena de catorce pasos (pasando por el radio y el radón) hasta convertirse en plomo-206, que es estable. Por eso las minas de uranio contienen radio y desprenden radón, y por eso los mineros del uranio sufrieron durante décadas tasas altísimas de cáncer de pulmón.' },
      { t: 'h', text: 'Radiactividad natural' },
      { t: 'p', text: 'La radiactividad no es un invento humano. Vivimos rodeados de ella: el radón que sale del suelo, el potasio-40 de nuestros propios huesos y músculos, el carbono-14 de los alimentos, el uranio y el torio de las rocas y los rayos cósmicos que llegan del espacio. Esta *radiación de fondo* expone a cada persona, de media, a unos 2,4 milisieverts al año (véase [[unidades-de-radiacion|Unidades de radiación]]). El calor que mantiene fundido el interior de la Tierra procede, en buena parte, de la desintegración de esos elementos.' },
      { t: 'note', text: 'La radiactividad de un objeto es distinta de la radiación que recibe. Un objeto expuesto a rayos gamma o a rayos X no se vuelve radiactivo; uno expuesto a neutrones sí puede volverse radiactivo, y uno contaminado con polvo radiactivo lo es mientras el polvo siga ahí. Esta distinción es esencial para entender la [[radiacion-inicial|radiación inicial]] y la [[lluvia-radiactiva|lluvia radiactiva]] de una explosión.' },
    ],
    related: ['isotopos', 'unidades-de-radiacion', 'lluvia-radiactiva', 'efectos-en-la-salud', 'radiacion-inicial'],
  },

  // ───────────────────────────────────────────────────────────── fisión
  {
    id: 'fision',
    title: 'La fisión nuclear',
    cat: 'fund',
    order: 4,
    summary: 'La fisión es la ruptura de un núcleo pesado en dos fragmentos medianos tras absorber un neutrón. Cada fisión libera unos 200 MeV, decenas de millones de veces más que una reacción química, y nuevos neutrones que pueden provocar más fisiones.',
    tags: ['fisión', 'neutrón', 'uranio-235', 'plutonio-239', 'productos de fisión', 'sección eficaz', 'barn', 'neutrones rápidos', 'neutrones térmicos', 'moderador', 'Hahn', 'Meitner', 'Frisch', 'MeV', 'fisión espontánea'],
    blocks: [
      { t: 'p', text: 'La **fisión nuclear** es la división de un núcleo atómico pesado en dos núcleos más ligeros. En la práctica casi siempre se provoca disparando un neutrón contra un núcleo de uranio o de plutonio. El núcleo absorbe el neutrón, se deforma, se estira como una gota de agua que oscila y acaba partiéndose en dos fragmentos que salen despedidos en direcciones opuestas a enorme velocidad, acompañados de dos o tres neutrones nuevos y de radiación gamma. Es el proceso que alimenta los reactores nucleares y las [[arma-de-fision|armas de fisión]], y la primera etapa de todas las [[bomba-de-hidrogeno|armas termonucleares]].' },
      { t: 'diagram', id: 'fission', caption: 'Un neutrón alcanza un núcleo de uranio-235; el núcleo se deforma y se parte en dos fragmentos (por ejemplo, bario y kriptón), libera dos o tres neutrones y una gran cantidad de energía.' },
      { t: 'h', text: 'Por qué se parte el núcleo' },
      { t: 'p', text: 'Como se explica en [[atomo|El átomo]], dentro de un núcleo compiten dos fuerzas: la nuclear fuerte, que une a todas las partículas pero sólo a muy corta distancia, y la repulsión eléctrica entre protones, más débil pero de mayor alcance. En un núcleo tan grande como el del uranio, con 92 protones, el equilibrio es precario. Niels Bohr y John Wheeler lo describieron en 1939 con el **modelo de la gota líquida**: el núcleo se comporta como una gota cargada eléctricamente. Si recibe un pequeño aporte de energía, por ejemplo la que trae un neutrón al ser capturado, empieza a vibrar. Si se alarga lo suficiente y forma una «cintura», la fuerza fuerte ya no alcanza a sujetar los dos extremos, la repulsión eléctrica los separa y el núcleo se divide.' },
      { t: 'h', text: 'Fisibles y fisionables' },
      { t: 'p', text: 'No todos los núcleos pesados se comportan igual. En el uranio-235 y el plutonio-239, el simple hecho de capturar un neutrón aporta energía suficiente para la fisión, aunque el neutrón llegue casi parado. Estos isótopos se llaman **fisibles**. En el uranio-238, en cambio, la captura no basta: sólo se fisiona si el neutrón llega ya muy rápido, con mucha energía propia. Se dice que es **fisionable** pero no fisible. Además, cuando el uranio-238 captura un neutrón lento sin fisionarse, se transforma con el tiempo en plutonio-239: por eso se le llama **fértil** (véase [[plutonio|Plutonio]]).' },
      { t: 'p', text: 'Esta distinción explica dos hechos históricos. Por un lado, el uranio natural, que es casi todo uranio-238, no puede mantener una explosión por sí solo, y para un arma hace falta aumentar la proporción del raro uranio-235 mediante el costosísimo proceso de enriquecimiento descrito en [[uranio|Uranio]]. Por otro, el uranio-238 sí se fisiona con los neutrones muy rápidos de la [[fusion|fusión]], lo que se aprovecha en las armas de tipo fisión-fusión-fisión (véase [[bomba-de-hidrogeno|La bomba de hidrógeno]]).' },
      { t: 'h', text: 'Neutrones rápidos y neutrones lentos' },
      { t: 'p', text: 'Los neutrones que nacen en una fisión salen disparados a unos 20 000 kilómetros por segundo: son **neutrones rápidos**. Si atraviesan un material que contiene núcleos ligeros, como el agua o el grafito, chocan con ellos una y otra vez y van perdiendo velocidad hasta quedar a la temperatura del entorno, moviéndose a apenas unos kilómetros por segundo. Son los **neutrones lentos** o **térmicos**, y el material que los frena se llama **moderador**. Enrico Fermi descubrió en Roma en 1934, casi por casualidad, que los neutrones frenados al atravesar parafina eran mucho más eficaces para provocar reacciones nucleares.' },
      { t: 'h', text: 'La sección eficaz, explicada sin fórmulas' },
      { t: 'p', text: 'Los físicos miden la probabilidad de que un neutrón provoque una reacción con una magnitud llamada **sección eficaz**. La idea intuitiva es la de una diana: imagine que cada núcleo es un blanco y que su tamaño no es el geométrico, sino el «tamaño aparente» que presenta ante el neutrón. Cuanto mayor es la diana, más fácil es acertar. Ese tamaño aparente cambia muchísimo según la velocidad del neutrón: para el uranio-235, un neutrón lento «ve» un blanco cientos de veces mayor que uno rápido. Es como si al pasar despacio junto al núcleo tuviera más tiempo para ser atrapado.' },
      { t: 'p', text: 'La sección eficaz se mide en una unidad de nombre curioso, el **barn** (en inglés, «granero»), equivalente a una superficie de 10⁻²⁴ centímetros cuadrados. Su origen es una broma de dos físicos de la Universidad de Purdue en 1942: para un núcleo, esa superficie era tan grande «como la puerta de un granero». El nombre servía además como término en clave durante la guerra.' },
      { t: 'p', text: 'De aquí sale una diferencia fundamental entre reactores y armas. Un **reactor** usa un moderador para frenar los neutrones y aprovechar la gran sección eficaz de los neutrones lentos, lo que le permite funcionar con uranio poco enriquecido o incluso natural. Un **arma**, en cambio, no puede esperar a que los neutrones se frenen: la reacción debe completarse antes de que el propio calor disperse el material, de modo que funciona con neutrones rápidos y necesita material fisible muy concentrado. Un reactor no puede estallar como una bomba, aunque sí puede sufrir accidentes graves por otras causas, como en [[chernobil|Chernóbil]].' },
      { t: 'h', text: 'Qué sale de una fisión' },
      { t: 'list', items: [
        '**Dos fragmentos de fisión**: casi nunca iguales. Lo más frecuente es que uno tenga una masa en torno a 95 y el otro en torno a 140, como un kriptón y un bario, o un estroncio y un xenón. Se conocen centenares de combinaciones posibles.',
        '**Dos o tres neutrones nuevos** (unos 2,4 de media en el uranio-235). Son los que permiten la [[reaccion-en-cadena|reacción en cadena]]. Una pequeña fracción no sale inmediatamente sino segundos después, desde los fragmentos: son los *neutrones retardados*, gracias a los cuales un reactor puede controlarse.',
        '**Radiación gamma** inmediata, que forma parte de la [[radiacion-inicial|radiación inicial]] de una explosión.',
        '**Neutrinos**, que escapan sin interactuar y se llevan una parte de la energía.',
      ] },
      { t: 'p', text: 'Los fragmentos tienen demasiados neutrones para su tamaño y son intensamente radiactivos: son los **productos de fisión**. Se desintegran en cadenas de emisiones beta y gamma que pueden durar desde fracciones de segundo hasta décadas. Entre ellos están el yodo-131, el cesio-137 y el estroncio-90. En una explosión nuclear, estos productos se mezclan con el polvo y los restos de la bola de fuego y forman la [[lluvia-radiactiva|lluvia radiactiva]]; en un reactor, quedan atrapados en el combustible gastado.' },
      { t: 'h', text: 'Cuánta energía libera' },
      { t: 'p', text: 'Cada fisión de un núcleo de uranio-235 libera unos **200 MeV**. La suma de las masas de todo lo que sale es ligeramente inferior a la masa del núcleo y el neutrón iniciales, y esa diferencia se convierte en energía según E = mc². La mayor parte aparece como energía de movimiento de los dos fragmentos, que se repelen eléctricamente y salen disparados; al frenarse contra los átomos vecinos, esa energía se transforma en calor.' },
      { t: 'compare', head: ['Destino de la energía de una fisión', 'Aproximado'], rows: [
        ['Movimiento de los fragmentos (se convierte en calor)', '≈ 168 MeV'],
        ['Neutrones inmediatos', '≈ 5 MeV'],
        ['Radiación gamma inmediata', '≈ 7 MeV'],
        ['Desintegración posterior de los productos de fisión (beta y gamma)', '≈ 13 MeV'],
        ['Neutrinos (escapan)', '≈ 10 MeV'],
        ['Total', '≈ 200 MeV'],
      ] },
      { t: 'p', text: 'Para hacerse una idea de lo que significa: cuando se quema una molécula de metano o estalla una molécula de TNT, se liberan unos pocos electronvoltios. Una fisión libera doscientos millones de electronvoltios. Por unidad de masa, la fisión completa de un material fisible produce del orden de **veinte millones de veces** más energía que la misma masa de TNT. Esa diferencia, no un detalle técnico, es lo que separa una bomba convencional de una nuclear (véase [[energia-y-tnt|Energía y equivalencia en TNT]]).' },
      { t: 'compare', head: ['', 'Reacción química', 'Fisión nuclear'], rows: [
        ['Qué cambia', 'La disposición de los electrones', 'El propio núcleo'],
        ['Energía por reacción', 'Unos pocos eV', 'Unos 200 MeV'],
        ['Energía por kilogramo', 'Unos pocos megajulios', 'Decenas de millones de megajulios'],
        ['Productos', 'Moléculas nuevas, en general estables', 'Elementos nuevos, muy radiactivos'],
        ['Masa convertida en energía', 'Imperceptible', 'Alrededor de una milésima parte'],
      ] },
      { t: 'h', text: 'La fisión espontánea' },
      { t: 'p', text: 'Algunos núcleos pesados se fisionan de vez en cuando sin necesidad de recibir un neutrón: es la **fisión espontánea**, descubierta en 1940 por los soviéticos Gueorgui Fliórov y Konstantín Petrzhak. En el uranio es rarísima, pero en ciertos isótopos, como el plutonio-240, es mucho más frecuente. Cada una de esas fisiones espontáneas emite neutrones que aparecen en momentos imprevisibles, y ese pequeño detalle obligó en 1944 a abandonar el diseño de cañón para el plutonio y a desarrollar la [[implosion|implosión]] (véase también [[tipo-canon|Arma de tipo cañón]]).' },
      { t: 'h', text: 'El descubrimiento' },
      { t: 'p', text: 'La historia completa se cuenta en [[descubrimiento-de-la-fision|El descubrimiento de la fisión]]. En resumen: a partir de 1934 varios laboratorios bombardeaban uranio con neutrones creyendo obtener elementos más pesados. La química alemana Ida Noddack sugirió ese mismo año que quizá el núcleo se estuviera rompiendo, pero nadie la tomó en serio. En diciembre de 1938, en Berlín, Otto Hahn y Fritz Strassmann encontraron bario, un elemento de masa mitad que la del uranio, entre los productos. Hahn escribió desconcertado a su antigua colaboradora Lise Meitner, que había huido de Alemania por su origen judío. Durante las Navidades, paseando por la nieve en Suecia con su sobrino Otto Frisch, Meitner comprendió que el núcleo se había partido en dos y calculó, con la fórmula de Einstein, que se liberaban unos 200 MeV. Frisch tomó de la biología la palabra *fisión*, la división de una célula.' },
      { t: 'timeline', items: [
        { date: '1934', text: 'Enrico Fermi bombardea uranio con neutrones en Roma. Ida Noddack propone que el núcleo podría partirse.' },
        { date: 'Diciembre de 1938', text: 'Hahn y Strassmann detectan bario en uranio irradiado con neutrones.' },
        { date: 'Enero de 1939', text: 'Meitner y Frisch interpretan el resultado como una fisión; Frisch lo confirma experimentalmente. Bohr lleva la noticia a Estados Unidos.' },
        { date: 'Marzo de 1939', text: 'Frédéric Joliot-Curie, Hans von Halban y Lew Kowarski, en París, demuestran que cada fisión libera varios neutrones: la [[reaccion-en-cadena|reacción en cadena]] es posible.' },
        { date: 'Septiembre de 1939', text: 'Bohr y Wheeler publican la teoría de la fisión basada en el modelo de la gota líquida.' },
        { date: '1940', text: 'Fliórov y Petrzhak descubren la fisión espontánea.' },
        { date: '1944–1945', text: 'Hahn recibe en solitario el Nobel de Química; la exclusión de Meitner se considera hoy una de las grandes injusticias del premio. El elemento 109 lleva su nombre: meitnerio.' },
      ] },
    ],
    related: ['reaccion-en-cadena', 'masa-critica', 'descubrimiento-de-la-fision', 'arma-de-fision', 'uranio', 'energia-y-tnt'],
  },

  // ───────────────────────────────────────────────────────────── reacción en cadena
  {
    id: 'reaccion-en-cadena',
    title: 'La reacción en cadena',
    cat: 'fund',
    order: 5,
    summary: 'Si los neutrones de cada fisión provocan nuevas fisiones, el proceso se multiplica generación tras generación. Controlada, es un reactor; descontrolada en una fracción de microsegundo, es una explosión nuclear.',
    tags: ['reacción en cadena', 'factor de multiplicación', 'k', 'subcrítico', 'crítico', 'supercrítico', 'Szilard', 'Fermi', 'Chicago Pile-1', 'neutrones retardados', 'reactor', 'Oklo', 'generaciones'],
    blocks: [
      { t: 'p', text: 'Cada [[fision|fisión]] de uranio-235 libera dos o tres neutrones. Si al menos uno de ellos alcanza otro núcleo fisible y lo parte, se producirán nuevos neutrones que pueden repetir el proceso. Esta sucesión de fisiones que se provocan unas a otras es la **reacción en cadena**. Es la idea central de toda la tecnología nuclear: sin ella, la fisión sería una curiosidad de laboratorio que libera energía átomo a átomo; con ella, un trozo de material puede liberar en una fracción de segundo la energía de miles de toneladas de explosivo.' },
      { t: 'diagram', id: 'chain', caption: 'Generación a generación: un neutrón provoca una fisión, que libera varios neutrones, que provocan varias fisiones más. Si cada generación es mayor que la anterior, el número de fisiones crece de forma exponencial.' },
      { t: 'h', text: 'La idea de Szilard' },
      { t: 'p', text: 'El primero en imaginarla fue el físico húngaro Leó Szilard. Según su propio relato, una mañana de septiembre de 1933, esperando a que cambiara un semáforo en Southampton Row, en Londres, pensó que si se encontrara un elemento que al ser alcanzado por un neutrón emitiera dos, se podría producir una reacción que creciera sin límite. Acababa de leer que Rutherford calificaba de «tontería» cualquier idea de extraer energía de los átomos. Szilard patentó el concepto en 1934 y cedió la patente al Almirantazgo británico para mantenerla en secreto. Aún no sabía qué elemento podía servir: la fisión no se descubriría hasta cinco años después.' },
      { t: 'p', text: 'En marzo de 1939, semanas después del descubrimiento de la fisión, el equipo de Frédéric Joliot-Curie en París y, por separado, Szilard y Fermi en Nueva York comprobaron que cada fisión liberaba efectivamente más de un neutrón. La reacción en cadena era posible. Alarmado ante la posibilidad de que la Alemania nazi construyera un arma, Szilard redactó ese verano la carta que firmó Albert Einstein y que llegó al presidente Roosevelt (véase [[carta-de-einstein|La carta de Einstein]]).' },
      { t: 'h', text: 'El factor de multiplicación' },
      { t: 'p', text: 'No todos los neutrones liberados provocan una nueva fisión. Algunos escapan por la superficie del material, otros son absorbidos por núcleos que no se fisionan (impurezas, uranio-238 o cualquier otro material) y otros, simplemente, no encuentran un blanco. Lo que importa es el promedio de neutrones de cada generación que consiguen provocar una fisión en la siguiente. Los físicos lo llaman **factor de multiplicación** y lo representan con la letra *k*.' },
      { t: 'list', items: [
        '**k menor que 1 (subcrítico)**: cada generación es más pequeña que la anterior. Cualquier reacción que empiece se apaga sola. Así está, por ejemplo, el combustible nuevo almacenado de forma segura.',
        '**k igual a 1 (crítico)**: cada generación es igual a la anterior. La reacción se mantiene estable, con una potencia constante. Así funciona un reactor nuclear en marcha.',
        '**k mayor que 1 (supercrítico)**: cada generación es mayor que la anterior y la reacción crece exponencialmente. En un reactor se usa durante breves momentos para subir la potencia, de forma muy controlada. En un arma, se busca que *k* sea tan alto como sea posible.',
      ] },
      { t: 'p', text: 'Que un conjunto de material sea subcrítico o supercrítico depende de su composición, su forma, su densidad y lo que lo rodea. Es el concepto de [[masa-critica|masa crítica]], que se explica en su propio artículo.' },
      { t: 'h', text: 'El poder de las potencias' },
      { t: 'p', text: 'El crecimiento exponencial desafía la intuición. Recuerde la leyenda del inventor del ajedrez que pidió como recompensa un grano de trigo en la primera casilla, dos en la segunda, cuatro en la tercera, y así sucesivamente: al llegar a la casilla 64 no había trigo suficiente en todo el mundo. Con una reacción que duplicara el número de fisiones en cada generación, tras 10 generaciones habría unas mil fisiones simultáneas; tras 20, un millón; tras 40, un billón, y unas pocas decenas de generaciones más bastan para llegar a los billones de billones de fisiones que hacen falta para liberar la energía de una explosión nuclear.' },
      { t: 'p', text: 'Lo que convierte esto en una explosión es la rapidez. Un neutrón rápido tarda sólo unas milmillonésimas de segundo en recorrer el material y provocar la siguiente fisión, de modo que toda la secuencia de generaciones se completa en menos de un microsegundo. En ese tiempo, la energía liberada calienta el material a decenas de millones de grados, lo vaporiza y lo hace expandirse. Al expandirse, la densidad cae, se escapan más neutrones, *k* baja de 1 y la reacción se detiene. Toda la historia de las armas de fisión es, en el fondo, la lucha por mantener el material unido el tiempo suficiente para que fisione una fracción apreciable antes de dispersarse (véase [[arma-de-fision|Arma de fisión]]).' },
      { t: 'h', text: 'Reactor frente a bomba' },
      { t: 'p', text: 'Si la reacción en cadena es tan rápida, ¿cómo es posible controlar un reactor? La respuesta está en los **neutrones retardados**. Una pequeña fracción de los neutrones, menos del uno por ciento, no sale en el instante de la fisión sino segundos o minutos después, cuando se desintegran ciertos productos de fisión. Un reactor se diseña para que sólo sea crítico contando con esos neutrones rezagados; así, la potencia cambia en escalas de segundos o minutos y los operadores o los sistemas automáticos tienen tiempo de reaccionar moviendo las barras de control. Un arma, en cambio, funciona sólo con neutrones inmediatos: no espera a nadie.' },
      { t: 'compare', head: ['', 'Reactor nuclear', 'Arma de fisión'], rows: [
        ['Objetivo', 'Producir calor de forma continua durante años', 'Liberar la máxima energía en menos de un microsegundo'],
        ['Factor k', 'Mantenido en 1 de forma estable', 'Llevado bruscamente muy por encima de 1'],
        ['Neutrones', 'Lentos, frenados por un moderador', 'Rápidos, sin moderador'],
        ['Control', 'Barras de control y neutrones retardados', 'Ninguno: la reacción se detiene sola al dispersarse el material'],
        ['Combustible', 'Uranio natural o poco enriquecido', 'Uranio altamente enriquecido o plutonio'],
        ['¿Puede estallar como una bomba?', 'No; sus accidentes graves son de otro tipo', 'Es su función'],
      ] },
      { t: 'h', text: 'Chicago Pile-1: la primera reacción en cadena' },
      { t: 'p', text: 'La primera reacción en cadena controlada de la historia se logró el 2 de diciembre de 1942 bajo las gradas del estadio Stagg Field de la Universidad de Chicago, en una pista de squash. El reactor, llamado **Chicago Pile-1**, era literalmente una pila: miles de bloques de grafito, que actuaba como moderador, con trozos de uranio y óxido de uranio intercalados. Lo dirigía Enrico Fermi, con un equipo en el que figuraban Leó Szilard, Walter Zinn, Herbert Anderson y Leona Woods, la única mujer presente. Como precaución, unos jóvenes esperaban sobre la pila con cubos de solución de cadmio para apagarla si algo salía mal.' },
      { t: 'p', text: 'A media tarde, Fermi ordenó retirar poco a poco la última barra de control y, con su regla de cálculo, comprobó que la intensidad de neutrones crecía sin estabilizarse: la pila era crítica. La mantuvieron así durante unos minutos con una potencia de apenas medio vatio, menos que una bombilla, y luego la apagaron. Arthur Compton telefoneó a James Conant con una frase en clave que se hizo célebre: «El navegante italiano ha llegado al Nuevo Mundo». Fue el punto de partida práctico del [[proyecto-manhattan|Proyecto Manhattan]] y de los grandes reactores de producción de [[plutonio|plutonio]] de [[oak-ridge-y-hanford|Hanford]].' },
      { t: 'quote', text: 'El navegante italiano ha llegado al Nuevo Mundo.', by: 'Arthur Compton, al comunicar el éxito de Chicago Pile-1 (1942)' },
      { t: 'h', text: 'Un reactor natural de hace 2000 millones de años' },
      { t: 'p', text: 'En 1972, técnicos franceses que analizaban uranio de la mina de Oklo, en Gabón, observaron que tenía menos uranio-235 del normal. La explicación resultó asombrosa: hace unos 2000 millones de años, cuando la proporción de uranio-235 en el uranio natural era mucho mayor que hoy porque aún no se había desintegrado tanto, el agua subterránea actuó como moderador y varios yacimientos funcionaron como reactores nucleares naturales, de forma intermitente, durante cientos de miles de años. La naturaleza se había adelantado a Fermi.' },
      { t: 'note', text: 'Cuando una reacción en cadena se produce sin querer fuera de un reactor se habla de un *accidente de criticidad*. Han ocurrido varias decenas en laboratorios e instalaciones de combustible; no producen una explosión nuclear, pero sí un destello de radiación que puede ser mortal para quien esté cerca. Véase [[accidentes-de-criticidad|Accidentes de criticidad]].' },
    ],
    related: ['fision', 'masa-critica', 'arma-de-fision', 'proyecto-manhattan', 'accidentes-de-criticidad', 'carta-de-einstein'],
  },

  // ───────────────────────────────────────────────────────────── masa crítica
  {
    id: 'masa-critica',
    title: 'Masa crítica',
    cat: 'fund',
    order: 6,
    summary: 'La masa crítica es la cantidad mínima de material fisible capaz de mantener una reacción en cadena. No es un número fijo: depende de la forma, la densidad, la pureza y lo que rodea al material.',
    tags: ['masa crítica', 'criticidad', 'subcrítico', 'supercrítico', 'fuga de neutrones', 'geometría', 'densidad', 'reflector', 'Frisch-Peierls', 'seguridad de criticidad'],
    blocks: [
      { t: 'p', text: 'Una [[reaccion-en-cadena|reacción en cadena]] sólo se sostiene si, de media, cada fisión provoca al menos otra. En un trozo pequeño de material fisible, la mayoría de los neutrones escapan por la superficie antes de encontrar un núcleo que partir y la reacción se apaga. Si el trozo es más grande, cada neutrón tiene que recorrer más material antes de salir y aumenta la probabilidad de que provoque una fisión. Existe un punto en el que las pérdidas y las ganancias se equilibran exactamente: a la cantidad de material necesaria para alcanzarlo se le llama **masa crítica**.' },
      { t: 'diagram', id: 'critical', caption: 'A la izquierda, un conjunto subcrítico: demasiados neutrones escapan por la superficie y la reacción se extingue. A la derecha, uno supercrítico: los neutrones encuentran núcleos antes de escapar y la reacción crece. Esquema cualitativo.' },
      { t: 'h', text: 'Un número que no es un número' },
      { t: 'p', text: 'Es habitual oír hablar de la masa crítica como si fuera una cifra fija de cada material. No lo es. Es el resultado de un balance de neutrones, y todo lo que altera ese balance la modifica. En esta enciclopedia no se dan cifras, pero sí se explican los factores que intervienen, que son los mismos que estudia la seguridad nuclear en cualquier instalación que maneje material fisible.' },
      { t: 'list', items: [
        '**El material**: cada isótopo tiene su propia probabilidad de fisionarse y su propio número de neutrones por fisión. El plutonio-239 y el uranio-235 se comportan de forma distinta, y el uranio natural, en el que predomina el uranio-238, no puede alcanzar la criticidad con neutrones rápidos por mucho que se acumule.',
        '**La pureza**: cualquier impureza que absorba neutrones sin fisionarse es una pérdida. Cuanto más diluido está el material fisible, más difícil es la criticidad.',
        '**La geometría**: los neutrones escapan por la superficie, así que la forma que minimiza las fugas es la que tiene menos superficie para un volumen dado, la esfera. Un cilindro largo y fino o una lámina delgada de la misma masa pierden muchos más neutrones. Por eso la industria nuclear guarda las disoluciones de material fisible en depósitos estrechos o planos, con formas que nunca pueden ser críticas.',
        '**La densidad**: si el mismo material se comprime, los núcleos están más juntos, el recorrido de un neutrón hasta encontrar uno es más corto y escapan menos. Una masa que es subcrítica a densidad normal puede volverse supercrítica si se comprime. Este principio es el fundamento de la [[implosion|implosión]].',
        '**Lo que lo rodea**: un material que devuelva hacia dentro parte de los neutrones que intentan escapar, llamado **reflector**, reduce las fugas y, con ello, la masa necesaria. Incluso el agua o el cuerpo de una persona pueden actuar como reflector, lo que ha estado detrás de varios accidentes.',
        '**Los moderadores**: en disoluciones o mezclas con agua, los neutrones se frenan y su probabilidad de provocar fisiones cambia. Esto afecta sobre todo a las instalaciones de combustible y a los laboratorios, no a las armas.',
      ] },
      { t: 'h', text: 'Subcrítico, crítico, supercrítico' },
      { t: 'p', text: 'Un conjunto **subcrítico** no puede sostener la reacción. Uno **crítico** la mantiene estable. Uno **supercrítico** la hace crecer. Toda [[arma-de-fision|arma de fisión]] se basa en mantener el material en configuración subcrítica hasta el momento deseado y pasar entonces, muy deprisa, a una configuración muy supercrítica. Hay dos formas históricas de hacerlo: juntar piezas separadas ([[tipo-canon|tipo cañón]]) o comprimir una pieza ([[implosion|implosión]]). La velocidad de ese tránsito es esencial: si es lenta, la reacción puede empezar antes de tiempo y el material se dispersa con una potencia muy inferior a la prevista.' },
      { t: 'h', text: 'Historia: de toneladas imposibles a un arma transportable' },
      { t: 'p', text: 'Tras el descubrimiento de la fisión, el físico francés Francis Perrin propuso en 1939 la primera fórmula para estimar la masa crítica del uranio. Las primeras estimaciones, que suponían uranio natural, daban cantidades enormes, del orden de toneladas, y llevaron a muchos científicos, entre ellos Niels Bohr, a pensar que un arma práctica era casi imposible.' },
      { t: 'p', text: 'En marzo de 1940, en la Universidad de Birmingham, dos refugiados de la Alemania nazi, Otto Frisch y Rudolf Peierls, se preguntaron qué pasaría con uranio-235 casi puro y neutrones rápidos. Su conclusión, recogida en el **memorándum Frisch-Peierls**, fue que la masa necesaria era muchísimo menor de lo que se creía, lo bastante como para que una bomba cupiera en un avión. El documento advertía también de la radiactividad que dejaría y de que no habría defensa posible. Ese memorándum convenció al Gobierno británico de crear el comité MAUD, cuyo informe de 1941 impulsó a su vez el [[proyecto-manhattan|Proyecto Manhattan]].' },
      { t: 'p', text: 'Durante la guerra, los científicos de [[los-alamos|Los Álamos]] determinaban experimentalmente cuándo un conjunto se acercaba a la criticidad acumulando piezas poco a poco y midiendo los neutrones. Richard Feynman comparó uno de estos experimentos con «hacerle cosquillas a la cola de un dragón dormido», y el nombre se quedó.' },
      { t: 'h', text: 'Cuando la criticidad llega sin querer' },
      { t: 'p', text: 'Aquellos experimentos costaron vidas. El 21 de agosto de 1945, Harry Daghlian dejó caer por accidente una pieza reflectora sobre un núcleo de plutonio y murió semanas después. El 21 de mayo de 1946, Louis Slotin estaba demostrando la aproximación a la criticidad con el mismo núcleo, separando dos piezas con un destornillador, cuando éste resbaló; hubo un destello azul y Slotin murió nueve días más tarde. Aquel núcleo pasó a la historia como el «núcleo del demonio». Décadas después, en 1999, dos operarios murieron en la planta de combustible de Tokaimura (Japón) al verter a mano una disolución de uranio en un depósito no diseñado para ello. Véase [[accidentes-de-criticidad|Accidentes de criticidad]].' },
      { t: 'note', text: 'Por motivos de seguridad, esta enciclopedia no ofrece cifras de masas críticas ni de ningún otro parámetro de diseño. Los conceptos aquí explicados son los que se enseñan en cualquier curso de física nuclear y en la formación en seguridad de criticidad.' },
    ],
    related: ['reaccion-en-cadena', 'fision', 'implosion', 'tipo-canon', 'accidentes-de-criticidad'],
  },

  // ───────────────────────────────────────────────────────────── fusión
  {
    id: 'fusion',
    title: 'La fusión nuclear',
    cat: 'fund',
    order: 7,
    summary: 'La fusión une núcleos ligeros, como los del hidrógeno, en otros más pesados y libera enormes cantidades de energía. Es lo que hace brillar al Sol y la fuente de la mayor parte de la potencia de las armas termonucleares.',
    tags: ['fusión', 'termonuclear', 'deuterio', 'tritio', 'helio', 'barrera de Coulomb', 'Sol', 'Bethe', 'Eddington', 'tokamak', 'ITER', 'NIF', 'ignición', 'efecto túnel'],
    blocks: [
      { t: 'p', text: 'La **fusión nuclear** es el proceso inverso de la [[fision|fisión]]: en lugar de partir un núcleo pesado, se unen dos núcleos ligeros para formar uno más pesado. Como el producto, típicamente helio, está mucho más fuertemente ligado que los núcleos de partida, la diferencia de masa se libera como energía. Es la reacción que alimenta el Sol y todas las estrellas, la que buscan domesticar los reactores experimentales de fusión y la que proporciona buena parte de la potencia de las [[bomba-de-hidrogeno|bombas de hidrógeno]].' },
      { t: 'diagram', id: 'fusion', caption: 'Un núcleo de deuterio y uno de tritio se fusionan para formar un núcleo de helio-4 y un neutrón muy rápido. La reacción libera 17,6 MeV.' },
      { t: 'h', text: 'El obstáculo: la repulsión eléctrica' },
      { t: 'p', text: 'Todos los núcleos tienen carga positiva y se repelen. Para que dos de ellos se acerquen lo suficiente como para que la fuerza nuclear fuerte los atrape, tienen que chocar a velocidades enormes y vencer esa repulsión, llamada **barrera de Coulomb**. La forma de conseguirlo a gran escala es calentar el combustible a temperaturas de decenas o cientos de millones de grados: a esas temperaturas los átomos pierden sus electrones, la materia se convierte en un **plasma** y los núcleos se mueven tan deprisa que algunos chocan con energía suficiente. Por eso se habla de reacciones **termonucleares**: nucleares, pero desencadenadas por el calor.' },
      { t: 'p', text: 'Ni siquiera esas temperaturas bastarían según la física clásica. La fusión es posible gracias a un fenómeno cuántico, el **efecto túnel**, explicado por George Gamow en 1928: un núcleo tiene cierta probabilidad de «atravesar» la barrera aunque no tenga energía suficiente para superarla. En el centro del Sol, a unos 15 millones de grados, cada protón tarda de media miles de millones de años en fusionarse, pero hay tantos que el Sol convierte cada segundo unos cuatro millones de toneladas de masa en energía.' },
      { t: 'h', text: 'Las reacciones más importantes' },
      { t: 'compare', head: ['Reacción', 'Energía liberada', 'Comentario'], rows: [
        ['Deuterio + tritio → helio-4 + neutrón', '17,6 MeV', 'La más fácil de lograr; el neutrón se lleva 14,1 MeV'],
        ['Deuterio + deuterio → helio-3 + neutrón', '3,3 MeV', 'Una de las dos ramas de la fusión D-D, igual de probables'],
        ['Deuterio + deuterio → tritio + protón', '4,0 MeV', 'La otra rama; produce tritio'],
        ['Deuterio + helio-3 → helio-4 + protón', '18,3 MeV', 'Casi sin neutrones, pero exige más temperatura'],
        ['Cadena protón-protón (Sol)', '26,7 MeV en total', 'Cuatro protones acaban convirtiéndose en un núcleo de helio'],
      ] },
      { t: 'p', text: 'La reacción **deuterio-tritio** es la protagonista tanto en los reactores experimentales como en las armas, porque es la que se produce a menor temperatura. Por cada unidad de masa de combustible, libera unas cuatro veces más energía que la fisión del uranio. Sus neutrones, mucho más rápidos que los de la fisión, son capaces de partir incluso núcleos de uranio-238, algo que se aprovecha en las armas de tipo fisión-fusión-fisión. Los combustibles se describen en [[combustibles-de-fusion|Combustibles de fusión]].' },
      { t: 'h', text: 'Cómo se descubrió que las estrellas son reactores' },
      { t: 'timeline', items: [
        { date: '1920', text: 'Francis Aston mide que un átomo de helio pesa algo menos que cuatro de hidrógeno. Arthur Eddington sugiere que las estrellas obtienen su energía convirtiendo hidrógeno en helio.' },
        { date: '1928', text: 'George Gamow explica el efecto túnel, que permite a los núcleos superar la repulsión eléctrica.' },
        { date: '1929', text: 'Robert Atkinson y Fritz Houtermans calculan que la fusión puede producirse en el interior de las estrellas.' },
        { date: '1934', text: 'Mark Oliphant, Paul Harteck y Ernest Rutherford logran las primeras reacciones de fusión en el laboratorio con deuterio, y descubren el tritio y el helio-3.' },
        { date: '1938–1939', text: 'Hans Bethe describe los ciclos de fusión que alimentan las estrellas (Nobel de Física en 1967).' },
        { date: '1941–1942', text: 'Enrico Fermi sugiere a Edward Teller que una bomba de fisión podría encender el deuterio; nace la idea de la Super (véase [[la-super|La Super]]).' },
        { date: '1951–1952', text: 'Greenhouse George demuestra la fusión encendida por un arma de fisión; [[ivy-mike|Ivy Mike]] es la primera explosión termonuclear a gran escala.' },
      ] },
      { t: 'h', text: 'Fusión en las armas' },
      { t: 'p', text: 'En un arma no hay forma práctica de calentar el combustible a esas temperaturas salvo con una explosión de fisión. Por eso toda arma termonuclear contiene una etapa de fisión, el *primario*, que crea las condiciones para que se produzca la fusión en el *secundario*. Además, la fusión no sólo aporta energía: sus neutrones rápidos provocan fisiones adicionales. Esto se aprovecha de dos maneras: en la [[fision-potenciada|fisión potenciada]], una pequeña cantidad de combustible de fusión hace más eficiente un arma de fisión; en la [[bomba-de-hidrogeno|bomba de hidrógeno]], la fusión es la fuente principal de energía y permite potencias de megatones.' },
      { t: 'h', text: 'Fusión con fines pacíficos' },
      { t: 'p', text: 'Desde los años cincuenta se intenta producir energía eléctrica con fusión controlada. El reto consiste en mantener un plasma de cientos de millones de grados el tiempo suficiente y con la densidad suficiente para que produzca más energía de la que se gasta en calentarlo; el físico británico John Lawson formuló en 1955 la condición necesaria, conocida como *criterio de Lawson*. Hay dos grandes estrategias:' },
      { t: 'list', items: [
        '**Confinamiento magnético**: el plasma se mantiene suspendido dentro de una cámara con forma de rosquilla mediante campos magnéticos intensísimos. El diseño más extendido es el **tokamak**, ideado por Ígor Tamm y Andréi Sájarov en la URSS a principios de los cincuenta. El JET británico batió en 2023 el récord de energía producida en un solo pulso (69 megajulios) y el gran proyecto internacional **ITER**, en construcción en Cadarache (Francia), con participación europea y española, aspira a demostrar una ganancia de energía a partir de la década de 2030.',
        '**Confinamiento inercial**: una pequeña cápsula de combustible se comprime y calienta en una fracción de nanosegundo con láseres muy potentes. El 5 de diciembre de 2022, la National Ignition Facility (NIF) de Livermore, en California, logró por primera vez la **ignición**: la reacción liberó más energía (3,15 MJ) que la que los láseres depositaron en la cápsula (2,05 MJ), aunque mucho menos que la consumida por toda la instalación.',
      ] },
      { t: 'p', text: 'La fusión controlada tiene ventajas atractivas: combustible abundante (el deuterio se extrae del agua), ningún riesgo de reacción en cadena descontrolada y residuos de vida mucho más corta que los de la fisión. Pero sigue siendo un reto científico e industrial de primer orden, y la broma de que la fusión «siempre está a treinta años vista» lleva repitiéndose desde hace más de medio siglo.' },
      { t: 'compare', head: ['', 'Fisión', 'Fusión'], rows: [
        ['Qué ocurre', 'Un núcleo pesado se parte en dos', 'Dos núcleos ligeros se unen'],
        ['Combustible típico', 'Uranio-235, plutonio-239', 'Deuterio, tritio, litio'],
        ['Qué la inicia', 'Un neutrón', 'Temperaturas de decenas de millones de grados'],
        ['Energía por unidad de masa', 'Muy alta', 'Unas cuatro veces mayor (D-T)'],
        ['Residuos', 'Productos de fisión muy radiactivos', 'Pocos directos; los neutrones activan los materiales'],
        ['Uso civil', 'Centrales nucleares desde 1954', 'Experimental'],
      ] },
    ],
    related: ['combustibles-de-fusion', 'bomba-de-hidrogeno', 'fision-potenciada', 'la-super', 'fision', 'atomo'],
  },

  // ───────────────────────────────────────────────────────────── energía y TNT
  {
    id: 'energia-y-tnt',
    title: 'Energía y equivalencia en TNT',
    cat: 'fund',
    order: 8,
    summary: 'La potencia de las armas nucleares se expresa en toneladas de TNT equivalente: un kilotón son mil toneladas y un megatón, un millón. Es una convención que permite comparar explosiones muy distintas con una misma escala.',
    tags: ['kilotón', 'megatón', 'TNT', 'rendimiento', 'potencia', 'julio', 'caloría', 'ley del cubo', 'escalado', 'reparto de energía', 'comparación'],
    blocks: [
      { t: 'p', text: 'Cuando se dice que la bomba de Hiroshima tuvo una potencia de 15 kilotones, se quiere decir que liberó la misma energía que la explosión de 15 000 toneladas de **TNT** (trinitrotolueno). Esa forma de expresar la energía de una explosión, llamada **rendimiento** o **potencia**, nació durante el [[proyecto-manhattan|Proyecto Manhattan]], cuando los científicos necesitaban explicar a militares y políticos una magnitud para la que no existía referencia. Comparar con el explosivo militar más conocido era la forma más intuitiva de transmitirla.' },
      { t: 'h', text: 'Las unidades' },
      { t: 'facts', rows: [
        ['1 tonelada de TNT', '4,184 gigajulios (10⁹ calorías), por convenio'],
        ['1 kilotón (kt)', '1000 toneladas de TNT = 4,184 billones de julios'],
        ['1 megatón (Mt)', '1 000 000 de toneladas de TNT = 1000 kilotones'],
        ['1 kilotón en electricidad', 'Unos 1,16 millones de kilovatios hora'],
        ['1 gramo de masa convertido en energía', 'Unos 21,5 kilotones (E = mc²)'],
      ] },
      { t: 'p', text: 'La cifra de 4,184 gigajulios por tonelada es un convenio redondo (exactamente mil millones de calorías), no una medida del TNT real. La energía química del TNT varía ligeramente según cómo se mida, pero adoptar un valor fijo permite que todos hablen el mismo idioma. Hay que tener en cuenta además que la equivalencia se refiere a la energía total, no a los efectos: una explosión nuclear y una química de la misma energía no producen los mismos daños, porque la nuclear reparte su energía de otro modo, como se explica más abajo.' },
      { t: 'h', text: 'Por qué la nuclear es tan distinta' },
      { t: 'p', text: 'Los [[explosivos-convencionales|explosivos químicos]] liberan la energía de los enlaces entre átomos, unos pocos electronvoltios por molécula. La [[fision|fisión]] y la [[fusion|fusión]] liberan la energía que mantiene unido el núcleo, millones de electronvoltios por reacción. El resultado es que, kilo a kilo, el material nuclear rinde decenas de millones de veces más que el mejor explosivo químico. La bomba de Hiroshima pesaba unas 4,4 toneladas y liberó la energía de 15 000; la mayor bomba convencional estadounidense, la [[explosivos-convencionales|MOAB]], pesa 9,8 toneladas y libera unas 11.' },
      { t: 'compare', head: ['Explosión o fenómeno', 'Energía aproximada'], rows: [
        ['Granada de mano', '≈ 0,0002 t de TNT'],
        ['Bomba convencional Mk 84 (900 kg)', '≈ 0,6 t'],
        ['GBU-43/B MOAB', '≈ 11 t'],
        ['Explosión del puerto de Beirut (2020)', '≈ 0,5–1 kt'],
        ['Little Boy, Hiroshima (1945)', '≈ 15 kt'],
        ['Fat Man, Nagasaki (1945)', '≈ 21 kt'],
        ['Todos los explosivos de la Segunda Guerra Mundial', 'Se estima en unos pocos megatones'],
        ['Ivy Mike, primera bomba de hidrógeno (1952)', '≈ 10,4 Mt'],
        ['Tsar Bomba (1961)', '≈ 50 Mt'],
        ['Erupción del Krakatoa (1883)', 'Del orden de 200 Mt'],
        ['Terremoto de Japón de 2011 (magnitud 9)', 'Energía de las ondas sísmicas del orden de decenas de megatones'],
        ['Impacto de Chicxulub (hace 66 millones de años)', 'Del orden de 100 millones de megatones'],
      ] },
      { t: 'p', text: 'Una curiosidad ayuda a poner las cifras en perspectiva: la energía no es lo mismo que la potencia destructiva. Un kilo de gasolina contiene unas diez veces más energía química que un kilo de TNT, pero arde lentamente; el TNT es destructivo porque libera su energía en millonésimas de segundo. Y una tonelada de TNT contiene aproximadamente la energía de los alimentos que una persona consume en un año y medio. Lo terrible de una explosión, química o nuclear, es la rapidez con que se libera la energía en un volumen pequeño.' },
      { t: 'h', text: 'Dónde va la energía de una explosión nuclear' },
      { t: 'p', text: 'Una explosión química transforma casi toda su energía en onda de choque. Una nuclear la reparte entre varios mecanismos, lo que explica sus efectos particulares. Para una explosión en el aire a baja altitud, el reparto típico es el siguiente:' },
      { t: 'compare', head: ['Forma de energía', 'Fracción aproximada', 'Artículo'], rows: [
        ['Onda expansiva', '≈ 50 %', '[[onda-expansiva|Onda expansiva]]'],
        ['Radiación térmica (luz y calor)', '≈ 35 %', '[[radiacion-termica|Radiación térmica]]'],
        ['Radiación nuclear inicial (primer minuto)', '≈ 5 %', '[[radiacion-inicial|Radiación inicial]]'],
        ['Radiación residual (lluvia radiactiva)', '≈ 10 %', '[[lluvia-radiactiva|Lluvia radiactiva]]'],
      ] },
      { t: 'p', text: 'Este reparto cambia con la altura de la explosión, con la potencia y con el tipo de arma. En una [[bomba-de-neutrones|bomba de neutrones]], por ejemplo, la radiación inicial tiene más peso; en una explosión a gran altitud, casi toda la energía sale como rayos X y se genera un intenso [[pulso-electromagnetico|pulso electromagnético]].' },
      { t: 'h', text: 'La regla del cubo: diez veces más potencia no son diez veces más daño' },
      { t: 'p', text: 'El efecto más contraintuitivo de la escala nuclear es que el radio de destrucción crece mucho más despacio que la potencia. La energía de la onda expansiva se reparte en un volumen, y el volumen crece con el cubo de la distancia. Por eso la distancia a la que se alcanza una determinada sobrepresión aumenta con la **raíz cúbica** de la potencia: para duplicar el radio de destrucción hay que multiplicar la potencia por ocho, y para multiplicarlo por diez, por mil. La superficie destruida crece con la potencia elevada a dos tercios.' },
      { t: 'compare', head: ['Potencia', 'Radio relativo de la onda expansiva', 'Superficie relativa'], rows: [
        ['15 kt (Hiroshima)', '1', '1'],
        ['120 kt (×8)', '2', '4'],
        ['1 Mt (≈ ×67)', '≈ 4', '≈ 16'],
        ['15 Mt (×1000)', '10', '100'],
        ['50 Mt (Tsar Bomba)', '≈ 15', '≈ 220'],
      ] },
      { t: 'p', text: 'Esta ley tuvo consecuencias estratégicas: varias armas pequeñas destruyen más superficie que una sola grande con la misma potencia total. Por eso, a medida que los misiles se hicieron más precisos, las superpotencias abandonaron las bombas gigantescas y optaron por ojivas más pequeñas y numerosas, como las de los [[mirv|MIRV]]. Las fórmulas de escalado que utiliza este simulador para calcular los radios de cada efecto siguen este mismo principio, tomado de las obras de referencia publicadas, como *The Effects of Nuclear Weapons* de Samuel Glasstone y Philip Dolan.' },
      { t: 'note', text: 'En el simulador, la potencia se introduce en kilotones. Recuerde que la equivalencia en TNT mide energía total: dos explosiones con el mismo número de kilotones pueden diferir mucho en lluvia radiactiva según la fracción de energía que proceda de la fisión y la altura a la que se produzcan.' },
    ],
    related: ['fision', 'explosivos-convencionales', 'onda-expansiva', 'bola-de-fuego', 'explosiones-aereas-y-de-superficie'],
  },

  // ───────────────────────────────────────────────────────────── uranio
  {
    id: 'uranio',
    title: 'Uranio',
    cat: 'fund',
    order: 9,
    summary: 'El uranio es el elemento natural más pesado que abunda en la Tierra. Su isótopo 235, escaso, es fisible: alimenta los reactores nucleares y fue el material de la bomba de Hiroshima.',
    tags: ['uranio', 'U-235', 'U-238', 'enriquecimiento', 'uranio empobrecido', 'minería', 'torta amarilla', 'calutrón', 'difusión gaseosa', 'centrifugadora', 'Klaproth', 'Shinkolobwe', 'toxicidad'],
    blocks: [
      { t: 'p', text: 'El **uranio** es un metal plateado, muy denso (casi el doble que el plomo) y ligeramente radiactivo. Con número atómico 92, es el elemento más pesado que se encuentra en cantidades apreciables en la naturaleza. Está presente en casi todas las rocas, en el suelo y en el agua del mar en concentraciones minúsculas, y en ciertos yacimientos se concentra lo suficiente como para extraerlo. Durante siglo y medio fue una curiosidad usada para colorear vidrio y cerámica; desde 1939, es la materia prima de toda la industria nuclear.' },
      { t: 'facts', rows: [
        ['Símbolo y número atómico', 'U, 92'],
        ['Densidad', '19,1 g/cm³ (el plomo, 11,3)'],
        ['Isótopos naturales', 'U-238 (≈ 99,3 %), U-235 (≈ 0,7 %), U-234 (trazas)'],
        ['Semivida del U-238', '4470 millones de años'],
        ['Semivida del U-235', '704 millones de años'],
        ['Descubridor', 'Martin Heinrich Klaproth, 1789'],
        ['Primer metal aislado', 'Eugène-Melchior Péligot, 1841'],
      ] },
      { t: 'h', text: 'Historia' },
      { t: 'p', text: 'El químico alemán Martin Heinrich Klaproth identificó el uranio en 1789 en un mineral llamado pechblenda, procedente de las minas de plata de Joachimsthal (hoy Jáchymov, en la República Checa). Lo bautizó en honor del planeta Urano, descubierto ocho años antes. En 1896, Henri Becquerel descubrió la [[radiactividad|radiactividad]] precisamente con sales de uranio, y los Curie extrajeron el radio y el polonio de toneladas de pechblenda de esas mismas minas. Durante décadas, el uranio fue un subproducto de la minería del radio, usado para dar al vidrio un característico tono verde amarillento que brilla bajo la luz ultravioleta.' },
      { t: 'p', text: 'Todo cambió con el [[descubrimiento-de-la-fision|descubrimiento de la fisión]] en 1938. En 1939 Bohr y Wheeler comprendieron que el responsable de la fisión con neutrones lentos era el uranio-235, que constituye menos del 1 % del uranio natural. Durante la guerra, la mayor parte del uranio del [[proyecto-manhattan|Proyecto Manhattan]] procedió de la mina de Shinkolobwe, en el Congo Belga, de una riqueza excepcional, complementado con minas de Canadá y de la meseta del Colorado.' },
      { t: 'h', text: 'De la mina al combustible' },
      { t: 'p', text: 'Hoy los mayores productores de uranio son Kazajistán, que extrae en torno al 40 % del total mundial, Canadá, Namibia y Australia, que posee las mayores reservas conocidas. Una parte creciente se obtiene sin excavar, disolviendo el uranio en el propio yacimiento e impulsando la disolución a la superficie (*lixiviación in situ*). El mineral se procesa para obtener un concentrado de óxido de uranio de color amarillento, la llamada **torta amarilla** (*yellowcake*). En España hubo minas y plantas de tratamiento de uranio en varias provincias, sobre todo en Salamanca, hasta el año 2000, y la fábrica de Juzbado (Salamanca) produce elementos de combustible para centrales nucleares.' },
      { t: 'h', text: 'El enriquecimiento, como concepto' },
      { t: 'p', text: 'Como se explica en [[isotopos|Isótopos]], el uranio-235 y el uranio-238 son químicamente idénticos. Para aumentar la proporción del isótopo fisible, proceso llamado **enriquecimiento**, sólo puede aprovecharse la pequeñísima diferencia de masa entre ellos, poco más del 1 %. Se necesita repetir la separación una y otra vez en instalaciones enormes que consumen mucha energía, y por eso el enriquecimiento fue durante décadas el principal obstáculo para fabricar armas y sigue siendo el centro de la vigilancia internacional contra la proliferación. Los reactores comerciales utilizan uranio **poco enriquecido**, en el que el uranio-235 sigue siendo una pequeña minoría; las armas necesitan uranio **altamente enriquecido**. El organismo encargado de verificar que el uranio de uso civil no se desvía es el Organismo Internacional de Energía Atómica (OIEA).' },
      { t: 'p', text: 'A lo largo de la historia se han utilizado varios métodos, que aquí sólo se nombran:' },
      { t: 'list', items: [
        '**Separación electromagnética**: los *calutrones* de Ernest Lawrence, en la planta Y-12 de Oak Ridge, desviaban los iones de uranio con imanes gigantes. Fue el método que produjo el material de Little Boy. Por falta de cobre durante la guerra, sus bobinas se fabricaron con plata prestada por el Tesoro de Estados Unidos.',
        '**Difusión gaseosa**: hacía pasar un compuesto gaseoso de uranio a través de barreras porosas. La planta K-25 de Oak Ridge fue en su momento el mayor edificio del mundo. Dominó la producción hasta los años ochenta.',
        '**Difusión térmica**: usada brevemente en la planta S-50 de Oak Ridge en 1944 y 1945.',
        '**Centrifugación**: el método actual, mucho más eficiente. Hace girar el gas a velocidades altísimas en largos cilindros. Se desarrolló en la URSS en los años cincuenta con la participación del alemán Gernot Zippe. Por su pequeño tamaño y bajo consumo es también el más preocupante desde el punto de vista de la proliferación.',
        '**Métodos láser**: aprovechan que cada isótopo absorbe la luz de forma ligeramente distinta. Siguen en fase de desarrollo.',
      ] },
      { t: 'p', text: 'Véase [[oak-ridge-y-hanford|Oak Ridge y Hanford]] para la historia de las primeras plantas.' },
      { t: 'h', text: 'Usos civiles y militares' },
      { t: 'list', items: [
        '**Energía eléctrica**: las centrales nucleares producen en torno al 9 % de la electricidad mundial y alrededor de una quinta parte de la española. El combustible se fabrica en forma de pastillas cerámicas de óxido de uranio.',
        '**Propulsión naval**: submarinos y portaaviones nucleares usan reactores compactos que les permiten navegar años sin repostar.',
        '**Armas**: el uranio altamente enriquecido fue el material de [[tipo-canon|Little Boy]] y forma parte de muchas armas modernas.',
        '**Uranio empobrecido**: el residuo del enriquecimiento, con menos uranio-235 que el natural. Por su altísima densidad se usa en proyectiles perforantes, blindajes de carros de combate, contrapesos de aviones y blindajes contra la radiación. Su uso militar en el Golfo y los Balcanes generó una larga polémica sanitaria.',
        '**Del arma al enchufe**: entre 1993 y 2013, el programa estadounidense-ruso conocido como *Megatones por Megavatios* diluyó el uranio altamente enriquecido de miles de ojivas soviéticas desmanteladas para convertirlo en combustible de centrales; durante esos años generó alrededor de una décima parte de la electricidad de Estados Unidos.',
      ] },
      { t: 'h', text: 'Toxicidad' },
      { t: 'p', text: 'El uranio natural y el empobrecido son débilmente radiactivos, porque sus semividas son larguísimas. Su peligro principal es **químico**: como el plomo o el mercurio, es un metal pesado tóxico que, si se ingiere o se inhala en forma soluble, daña sobre todo los riñones. Como emisor alfa, su radiación es peligrosa sobre todo si las partículas se inhalan y quedan en los pulmones. El riesgo radiológico más serio de la minería no es el uranio en sí, sino el **radón**, el gas radiactivo que produce al desintegrarse: los mineros de uranio de Europa central y de Estados Unidos, entre ellos muchos trabajadores navajos, sufrieron durante décadas tasas de cáncer de pulmón muy elevadas antes de que se generalizara la ventilación de las minas. El uranio enriquecido es más radiactivo, pero su principal riesgo en la industria es el de un [[accidentes-de-criticidad|accidente de criticidad]].' },
    ],
    related: ['isotopos', 'plutonio', 'fision', 'oak-ridge-y-hanford', 'tipo-canon', 'potencias-nucleares'],
  },

  // ───────────────────────────────────────────────────────────── plutonio
  {
    id: 'plutonio',
    title: 'Plutonio',
    cat: 'fund',
    order: 10,
    summary: 'El plutonio es un elemento casi inexistente en la naturaleza que se fabrica en los reactores nucleares a partir del uranio-238. Su isótopo 239 es fisible y fue el material de la prueba Trinity y de la bomba de Nagasaki.',
    tags: ['plutonio', 'Pu-239', 'Pu-240', 'Pu-238', 'Seaborg', 'reactor productor', 'Hanford', 'Mayak', 'reprocesamiento', 'MOX', 'RTG', 'toxicidad', 'transuránido'],
    blocks: [
      { t: 'p', text: 'El **plutonio** es un metal plateado que se oscurece al aire, extraordinariamente denso y con un comportamiento físico tan extraño que los metalúrgicos lo consideran el elemento más complicado de la tabla periódica. Tiene número atómico 94. A diferencia del [[uranio|uranio]], prácticamente no existe en la naturaleza: todo el plutonio que se maneja hoy ha sido fabricado por el ser humano en reactores nucleares desde 1942. Es uno de los dos materiales fisibles con los que se construyen las armas nucleares.' },
      { t: 'facts', rows: [
        ['Símbolo y número atómico', 'Pu, 94'],
        ['Descubrimiento', 'Diciembre de 1940 – febrero de 1941, Universidad de California en Berkeley'],
        ['Descubridores', 'Glenn T. Seaborg, Edwin McMillan, Joseph Kennedy y Arthur Wahl'],
        ['Nombre', 'Por el planeta enano Plutón, siguiendo a uranio (Urano) y neptunio (Neptuno)'],
        ['Isótopo principal', 'Pu-239, fisible, semivida de 24 100 años'],
        ['Peculiaridad', 'Seis formas cristalinas distintas entre temperatura ambiente y su punto de fusión'],
      ] },
      { t: 'h', text: 'Descubrimiento' },
      { t: 'p', text: 'En 1940, Edwin McMillan y Philip Abelson obtuvieron en Berkeley el primer elemento más pesado que el uranio, el neptunio (93). Meses después, el joven químico Glenn Seaborg y sus colaboradores bombardearon uranio en el ciclotrón de Berkeley y aislaron el elemento 94. En marzo de 1941 demostraron que su isótopo 239 se fisionaba con neutrones lentos con más facilidad incluso que el uranio-235. El descubrimiento se mantuvo en secreto hasta después de la guerra. En agosto de 1942, Burris Cunningham y Louis Werner obtuvieron en Chicago la primera muestra de un compuesto de plutonio visible a simple vista, apenas una mota. Dos años después se producía a escala industrial. Seaborg y McMillan recibieron el Nobel de Química en 1951, y el elemento 106 se llama seaborgio en su honor.' },
      { t: 'h', text: 'Cómo se produce' },
      { t: 'p', text: 'El plutonio se fabrica en un reactor nuclear. Cuando un núcleo de uranio-238, el isótopo abundante y no fisible, captura un neutrón, se convierte en uranio-239, que en unos minutos sufre una desintegración beta y se transforma en neptunio-239; éste, en un par de días, sufre otra y se convierte en plutonio-239. Todo reactor de uranio produce plutonio como subproducto inevitable. La gran ventaja que vieron los científicos del [[proyecto-manhattan|Proyecto Manhattan]] es que, al ser un elemento distinto del uranio, el plutonio sí puede separarse por medios **químicos**, algo mucho más sencillo que el enriquecimiento de isótopos. Este proceso de separación del combustible irradiado se llama **reprocesamiento**.' },
      { t: 'p', text: 'Para producir plutonio con fines militares se construyeron **reactores productores** específicos: el reactor de grafito X-10 de Oak Ridge (1943), prototipo, y el reactor B de Hanford, en el estado de Washington, que alcanzó la criticidad en septiembre de 1944 y produjo el plutonio de la prueba [[prueba-trinity|Trinity]] y de la bomba de [[nagasaki|Nagasaki]]. La URSS construyó su primer reactor productor en el complejo de Mayak, en los Urales, en 1948; el Reino Unido, las pilas de Windscale; Francia, los reactores de Marcoule. Varios de estos lugares sufrieron graves accidentes y contaminación (véanse [[kyshtym|Kyshtym]] y [[windscale|Windscale]]).' },
      { t: 'diagram', id: 'isotopes', caption: 'El plutonio-239 tiene 94 protones; se forma cuando el uranio-238 captura un neutrón y sufre dos desintegraciones beta.' },
      { t: 'h', text: 'Los isótopos del plutonio' },
      { t: 'p', text: 'El plutonio que sale de un reactor nunca es plutonio-239 puro. Cuanto más tiempo permanece el combustible en el reactor, más plutonio-239 captura neutrones adicionales y se transforma en isótopos más pesados. Sus proporciones determinan las propiedades del material:' },
      { t: 'list', items: [
        '**Plutonio-238**: no sirve para armas, pero desprende tanto calor por su radiactividad que se usa en los generadores termoeléctricos de radioisótopos (RTG) que alimentan las sondas espaciales donde no llega bien la luz solar: las Voyager, Cassini, New Horizons y los róveres Curiosity y Perseverance. En los años setenta llegó a usarse incluso en marcapasos.',
        '**Plutonio-239**: el isótopo fisible de interés militar y también energético.',
        '**Plutonio-240**: se forma cuando el 239 captura un neutrón sin fisionarse. Sufre [[fision|fisión espontánea]] con relativa frecuencia y emite neutrones de forma continua. Su presencia es indeseable en un arma, porque esos neutrones pueden iniciar la reacción antes de tiempo. Por eso se distingue entre plutonio de *grado armamentístico*, producido con irradiaciones cortas para minimizar el plutonio-240, y plutonio de *grado reactor*, procedente del combustible de las centrales.',
        '**Plutonio-241 y 242**: isótopos más pesados presentes en el plutonio de grado reactor. El 241 se desintegra en americio-241, el material de muchos detectores de humo.',
      ] },
      { t: 'p', text: 'El descubrimiento de la fisión espontánea del plutonio-240 en el plutonio de los reactores, en 1944, fue una crisis en [[los-alamos|Los Álamos]]: obligó a abandonar el diseño de cañón previsto para el plutonio y a desarrollar en tiempo récord la [[implosion|implosión]].' },
      { t: 'h', text: 'Usos' },
      { t: 'list', items: [
        '**Armas**: la gran mayoría de las armas nucleares modernas usan plutonio en su núcleo o en su primario.',
        '**Combustible**: el plutonio recuperado del combustible gastado puede mezclarse con uranio para fabricar combustible **MOX** (óxidos mixtos) para centrales. También es el combustible previsto de los reactores reproductores rápidos, que producen más plutonio del que consumen.',
        '**Energía en el espacio**: el plutonio-238 de los generadores de radioisótopos.',
      ] },
      { t: 'h', text: 'Toxicidad y legado' },
      { t: 'p', text: 'El plutonio tiene fama de ser «la sustancia más tóxica conocida», lo que es una exageración: su toxicidad química no es extraordinaria. Su peligro es radiológico. Como emisor alfa, fuera del cuerpo apenas supone riesgo, porque la piel lo bloquea; pero si se **inhalan** partículas finas, éstas pueden quedarse en los pulmones o pasar a la sangre y depositarse en los huesos y el hígado, donde irradian los tejidos de forma continua durante décadas y aumentan el riesgo de cáncer. Por eso se manipula en cajas de guantes estancas. Entre 1945 y 1947, dieciocho personas recibieron inyecciones de plutonio sin su consentimiento informado en experimentos médicos del Gobierno de Estados Unidos, que no se revelaron por completo hasta los años noventa.' },
      { t: 'p', text: 'La producción de plutonio dejó una herencia ambiental enorme. El complejo de Hanford, con millones de litros de residuos líquidos de alta actividad almacenados en tanques subterráneos, es el mayor y más costoso proyecto de limpieza ambiental de Estados Unidos. En la URSS, la contaminación de Mayak y del río Techa afectó a decenas de miles de personas. Tras la Guerra Fría, Estados Unidos y Rusia declararon excedentes decenas de toneladas de plutonio militar, cuyo destino definitivo sigue sin resolverse del todo.' },
    ],
    related: ['uranio', 'isotopos', 'implosion', 'oak-ridge-y-hanford', 'kyshtym', 'fision'],
  },

  // ───────────────────────────────────────────────────────────── combustibles de fusión
  {
    id: 'combustibles-de-fusion',
    title: 'Combustibles de fusión',
    cat: 'fund',
    order: 11,
    summary: 'Deuterio, tritio y litio son los combustibles de la fusión, tanto en los reactores experimentales como en las armas termonucleares. El deuteruro de litio permitió fabricar bombas de hidrógeno sólidas y transportables.',
    tags: ['deuterio', 'tritio', 'litio-6', 'litio-7', 'deuteruro de litio', 'agua pesada', 'helio-3', 'Vemork', 'arma seca', 'criogénico'],
    blocks: [
      { t: 'p', text: 'La [[fusion|fusión]] necesita núcleos ligeros que se unan con relativa facilidad y liberen mucha energía al hacerlo. Los candidatos naturales son los isótopos pesados del hidrógeno, el **deuterio** y el **tritio**, y un metal ligero, el **litio**, que permite fabricar tritio. Su historia está ligada tanto a la investigación energética como al desarrollo de la [[bomba-de-hidrogeno|bomba de hidrógeno]].' },
      { t: 'h', text: 'Deuterio' },
      { t: 'p', text: 'El deuterio es hidrógeno con un neutrón en el núcleo. Es estable y abundante: aproximadamente uno de cada 6400 átomos de hidrógeno del agua del mar es deuterio, de modo que los océanos contienen una reserva prácticamente inagotable. Lo descubrió Harold Urey en 1931. El agua formada con deuterio, el **agua pesada**, es un excelente moderador de neutrones, y por eso tuvo un papel estratégico en la Segunda Guerra Mundial: la planta noruega de Vemork, que la producía para el programa nuclear alemán, fue objeto en 1943 de un célebre sabotaje por comandos noruegos entrenados por los británicos. Hoy se usa en reactores de tipo CANDU y como trazador en química y medicina.' },
      { t: 'h', text: 'Tritio' },
      { t: 'p', text: 'El tritio es hidrógeno con dos neutrones. Es radiactivo, emite una radiación beta muy débil y tiene una semivida de unos 12,3 años, así que en la naturaleza sólo existe en trazas que forman los rayos cósmicos. Se fabrica en reactores, sobre todo irradiando litio con neutrones. Sus usos civiles son los letreros de salida luminosos que funcionan sin electricidad, las esferas de algunos relojes y las miras nocturnas. Como su radiación apenas atraviesa la piel, es poco peligroso por fuera, aunque sí si se ingiere en forma de agua tritiada.' },
      { t: 'p', text: 'La reacción deuterio-tritio es la más fácil de encender y la más energética por unidad de masa, de ahí su importancia. Pero el tritio plantea dos problemas: es caro de producir y, como se desintegra, se pierde aproximadamente un 5 % cada año. Las armas que lo utilizan deben reponerlo periódicamente, y por eso Estados Unidos mantiene una producción de tritio en reactores de la Autoridad del Valle del Tennessee y en la planta de Savannah River.' },
      { t: 'h', text: 'Litio y deuteruro de litio' },
      { t: 'p', text: 'El litio tiene dos isótopos estables: el litio-6 y el litio-7, mucho más abundante. Cuando el litio-6 absorbe un neutrón se parte en un núcleo de helio y uno de tritio. Es decir, el litio-6 es una «fábrica» de tritio. Esto permitió una solución elegante para las armas: combinar litio y deuterio en un compuesto sólido, el **deuteruro de litio**, una sal blanca y estable. En el interior de un arma, los neutrones de la explosión convierten el litio en tritio en el mismo instante en que se necesita, y éste se fusiona con el deuterio presente.' },
      { t: 'p', text: 'La primera bomba de hidrógeno, [[ivy-mike|Ivy Mike]] (1952), usaba deuterio líquido a más de 250 grados bajo cero, lo que exigía un enorme equipo criogénico: el dispositivo pesaba unas 80 toneladas y ocupaba un edificio. Los soviéticos, por sugerencia del físico Vitali Ginzburg, apostaron desde el principio por el deuteruro de litio. Las armas que lo usan se denominan **secas**, por contraposición a las criogénicas, y son las únicas que pueden transportarse en un avión o en un misil. La primera prueba estadounidense de un arma seca, [[castle-bravo|Castle Bravo]] (1954), reveló además que el litio-7, que se suponía inerte, también participaba en las reacciones, con un resultado muy superior a lo previsto (véase [[armas-de-tres-etapas|Armas de tres etapas]]).' },
      { t: 'p', text: 'La separación de los isótopos del litio a escala industrial en la planta Y-12 de Oak Ridge, en los años cincuenta, usaba enormes cantidades de mercurio, buena parte del cual acabó en el medio ambiente. Es otro ejemplo del coste ambiental de la carrera nuclear.' },
      { t: 'h', text: 'Combustibles de la fusión del futuro' },
      { t: 'compare', head: ['Combustible', 'Ventajas', 'Inconvenientes'], rows: [
        ['Deuterio-tritio', 'La reacción más fácil; la que usarán ITER y los primeros reactores', 'El tritio hay que fabricarlo con litio; muchos neutrones que activan los materiales'],
        ['Deuterio-deuterio', 'Combustible abundante y barato', 'Requiere temperaturas mucho mayores'],
        ['Deuterio-helio-3', 'Muy pocos neutrones', 'El helio-3 es rarísimo en la Tierra; se ha propuesto extraerlo de la Luna'],
        ['Protón-boro-11', 'Prácticamente sin neutrones', 'Temperaturas aún más extremas; muy lejos de ser viable'],
      ] },
      { t: 'note', text: 'En un reactor de fusión deuterio-tritio, el tritio se fabricaría en la propia máquina rodeando la cámara con una «manta» que contenga litio, que capturaría los neutrones de la reacción. Ningún reactor ha demostrado todavía esa autosuficiencia.' },
    ],
    related: ['fusion', 'bomba-de-hidrogeno', 'isotopos', 'fision-potenciada', 'castle-bravo', 'ivy-mike'],
  },

  // ───────────────────────────────────────────────────────────── unidades de radiación
  {
    id: 'unidades-de-radiacion',
    title: 'Unidades de radiación',
    cat: 'fund',
    order: 12,
    summary: 'La radiación se mide con varias magnitudes: la actividad de una fuente (becquerel, curio), la dosis absorbida por la materia (gray, rad) y la dosis equivalente, que estima el daño biológico (sievert, rem).',
    tags: ['sievert', 'gray', 'rem', 'rad', 'roentgen', 'becquerel', 'curio', 'dosis', 'dosis equivalente', 'dosis efectiva', 'radiación de fondo', 'factor de ponderación'],
    blocks: [
      { t: 'p', text: 'Pocas cosas confunden tanto como las unidades de radiación. Hay varias porque miden cosas distintas: cuánto se desintegra una fuente, cuánta energía deposita la radiación en un material y cuánto daño biológico causa esa energía. Además conviven unidades antiguas, todavía muy usadas en Estados Unidos y en la literatura sobre armas nucleares, con las del Sistema Internacional. Este artículo las ordena.' },
      { t: 'h', text: 'Actividad: cuánto se desintegra' },
      { t: 'p', text: 'La **actividad** mide cuántos núcleos de una muestra se desintegran por segundo. Su unidad internacional es el **becquerel** (Bq), igual a una desintegración por segundo, en honor de Henri Becquerel. Es una unidad diminuta: el cuerpo humano tiene unos 4000 Bq de potasio-40 natural. La unidad antigua es el **curio** (Ci), definido originalmente como la actividad de un gramo de radio y equivalente a 37 000 millones de becquerelios. La actividad no dice nada por sí sola del peligro: depende del tipo de radiación, de su energía y de si la fuente está fuera o dentro del cuerpo.' },
      { t: 'h', text: 'Exposición: el roentgen' },
      { t: 'p', text: 'El **roentgen** (R), llamado así por Wilhelm Röntgen, el descubridor de los rayos X, mide la ionización que la radiación gamma o X produce en el aire. Se adoptó en 1928 y se usó mucho durante la Guerra Fría: los dosímetros de protección civil y los mapas de lluvia radiactiva de la época hablan de roentgens por hora. Hoy está en desuso, pero aparece en muchos textos históricos.' },
      { t: 'h', text: 'Dosis absorbida: el gray' },
      { t: 'p', text: 'La **dosis absorbida** mide cuánta energía deposita la radiación en cada kilogramo de materia. Su unidad internacional es el **gray** (Gy), igual a un julio por kilogramo, en honor del físico británico Louis Harold Gray. La unidad antigua es el **rad**, que equivale a una centésima de gray. Un gray es una cantidad de energía ridícula en términos térmicos (elevaría la temperatura del cuerpo menos de una milésima de grado), pero depositada en forma de radiación ionizante es suficiente para causar el síndrome de irradiación aguda.' },
      { t: 'h', text: 'Dosis equivalente y efectiva: el sievert' },
      { t: 'p', text: 'No toda la radiación hace el mismo daño con la misma energía. Una partícula alfa concentra su energía en un trayecto cortísimo y rompe el ADN de forma mucho más grave que un rayo gamma. Para tenerlo en cuenta, la dosis absorbida se multiplica por un **factor de ponderación** según el tipo de radiación, y el resultado es la **dosis equivalente**, que se mide en **sieverts** (Sv), en honor del físico sueco Rolf Sievert. La unidad antigua es el **rem**, una centésima de sievert.' },
      { t: 'compare', head: ['Radiación', 'Factor de ponderación (ICRP)'], rows: [
        ['Rayos gamma y X', '1'],
        ['Electrones (beta)', '1'],
        ['Protones', '2'],
        ['Neutrones', 'Entre 2,5 y 20, según su energía'],
        ['Partículas alfa', '20'],
      ] },
      { t: 'p', text: 'Un paso más allá está la **dosis efectiva**, también en sieverts, que pondera además la sensibilidad de cada órgano para estimar el riesgo global de cáncer a largo plazo. Es la magnitud que se usa en protección radiológica, en los límites legales y en las comparaciones de dosis médicas.' },
      { t: 'compare', head: ['Magnitud', 'Unidad internacional', 'Unidad antigua', 'Equivalencia'], rows: [
        ['Actividad', 'becquerel (Bq)', 'curio (Ci)', '1 Ci = 3,7 × 10¹⁰ Bq'],
        ['Exposición', 'culombio por kilogramo', 'roentgen (R)', '1 R ≈ 0,0096 Gy en tejido'],
        ['Dosis absorbida', 'gray (Gy)', 'rad', '1 Gy = 100 rad'],
        ['Dosis equivalente o efectiva', 'sievert (Sv)', 'rem', '1 Sv = 100 rem'],
      ] },
      { t: 'note', text: 'Regla práctica: para rayos gamma, que es la radiación dominante en la [[lluvia-radiactiva|lluvia radiactiva]], un roentgen, un rad y un rem son aproximadamente equivalentes, y 100 de cualquiera de ellos equivalen más o menos a 1 Gy o 1 Sv. Para efectos agudos (los que aparecen en horas o días) los especialistas prefieren hablar en grays; el sievert se reserva para el riesgo a largo plazo.' },
      { t: 'h', text: 'Valores de referencia' },
      { t: 'compare', head: ['Situación', 'Dosis aproximada'], rows: [
        ['Comer un plátano (por su potasio-40)', '0,0001 mSv'],
        ['Radiografía de tórax', '0,02 mSv'],
        ['Vuelo transatlántico de ida', '0,03–0,08 mSv'],
        ['Límite anual para el público (exposiciones artificiales)', '1 mSv'],
        ['Radiación natural media mundial en un año', '≈ 2,4 mSv'],
        ['Tomografía computarizada (TAC) de abdomen', '≈ 8–10 mSv'],
        ['Límite anual para trabajadores expuestos (UE)', '20 mSv'],
        ['Zonas de radiación natural alta, como Ramsar (Irán)', 'Hasta más de 100 mSv al año'],
        ['Primeros síntomas de irradiación aguda', '≈ 0,5–1 Gy'],
        ['Dosis letal para la mitad de los expuestos sin tratamiento', '≈ 3,5–5 Gy en poco tiempo'],
        ['Muerte casi segura', 'Más de 8–10 Gy'],
      ] },
      { t: 'p', text: 'Dos ideas ayudan a interpretar estas cifras. La primera es que importa mucho el **tiempo**: recibir 4 Gy en unos minutos puede ser mortal, mientras que la misma dosis repartida a lo largo de la vida tiene un efecto mucho menor porque las células reparan parte del daño. La segunda es que, por debajo de unos 100 mSv, el aumento del riesgo de cáncer es tan pequeño que resulta muy difícil de medir; la protección radiológica asume, por prudencia, que todo aumento de dosis supone algún riesgo, del orden de un 5 % de probabilidad adicional de cáncer mortal por cada sievert. Los efectos de la radiación sobre el organismo se tratan en [[efectos-en-la-salud|Efectos en la salud]].' },
      { t: 'h', text: 'Breve historia de las unidades' },
      { t: 'timeline', items: [
        { date: '1910', text: 'Se define el curio, en honor de Pierre y Marie Curie.' },
        { date: '1928', text: 'Se adopta el roentgen como unidad de exposición a rayos X y gamma.' },
        { date: '1953', text: 'Se introduce el rad como unidad de dosis absorbida; poco después, el rem.' },
        { date: '1975', text: 'La Conferencia General de Pesas y Medidas adopta el gray y el becquerel.' },
        { date: '1979', text: 'Se adopta el sievert como unidad de dosis equivalente.' },
      ] },
    ],
    related: ['radiactividad', 'efectos-en-la-salud', 'lluvia-radiactiva', 'radiacion-inicial', 'proteccion-civil'],
  },
];
